### ISSUE TITLE
ES.20: "Always initialize an object" should be considered with caution

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#1003]
I think **ES.20 Always initialize an object** should be considered with extreme caution and only applied if you also strictly following ES.4, ES.21, ES.22.

Consider the following example:

```cpp
 1 #include <iostream>
  2 #include <cstdlib>
  3 
  4 int main(int argc, char** argv)
  5 {
  6     // At this point we cannot provide a reasonable initialization value
  7     // for i. Actually, we have to assign an appropriate value later on
  8     // when evaluating argc.
  9     int i  = 0;  // dummy initialization to comply to ES.20
 10     
 11     switch (argc) {
 12         case 1:
 13             // ...
 14             i = 10;
 15             break;
 16         case 2:
 17             // ...
 18             // oops, forgot to assign a value to i;
 19             break;
 20         case 3: 
 21             // ...
 22             i = 30;
 23             break;
 24         // other case statements follow...
 25         default:
 26             std::cerr << "wrong argc" << std::endl;
 27             std::exit(EXIT_FAILURE);
 28     }
 29 
 30     std::cout << "i = " << i << std::endl;
 31 }
```

Without the initialization in line 9 the compiler or some static code analysis tool can warn that the variable may me used uninitialized.

```
$ g++  -O3 -Wall t.cpp
t.cpp: In function ‘int main(int, char**)’:
t.cpp:30:28: warning: ‘i’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     std::cout << "i = " << i << std::endl;
```

Therefore, I consider this rule harmful. I would reverse it. **Don't initialize an object if you don't have a reasonable initialization value at the time of its definition**

Reason: Allow compiler and static analysis tools to warn if a variable may be used uninitialized.

Of course, this situation should be avoided by following ES21, ES.22. But taken for its own it should be considered with caution. It might hide a bug, while otherwise tools can help to reveal it in an early stage.

**Comment by tlanc007** [comment]
Initializing seems safer than not.  Perhaps, this guideline could have  references to ES21, ES22 to give more context.

In your example, if Enum.2 or Enum.3 were followed, the issue could be avoided, for that case.

**Comment by franzhollerer** [comment]
Of course real code would use enums, constants or at least marcos. But this does not change the core statement of the example.

Strictly following ES.20 prevents the compiler, any static code analysis tools and even a human reviewer to warn you if there is an execution path where you don't assign a value to the variable before it is used. And actual compilers are doing a real good job in detecting this kind of bugs. The compiler cannot warn you if it sees an initialization at the definition.

I think it is safer to let the compiler warn you in an early stage. Why would you hope to reveal the problem during test and debugging, when it can be caught at compile time?

I absolutely agree that someone should follow ES.22.

> ES.22: Don't declare a variable until you have a value to initialize it with

But if this is not feasible, e.g. because you are working on an existing code base someone should not strictly follow ES.20.

I would state in addition:

**Don't initialize a variable if you don't have a reasonable value to initialize.**

Let the compiler find missing initialization. Don't mask a bug by initializing the variable with an *dummy* value.

**Comment by arvidn** [comment]
A safer way of implementing that logic would be to move the switch statement into a separate function with *return statements* instead of those assignments. It could also be put in a lambda. That way ``i`` can not only be initialized but also may be eligible to be ``const``.

That's the preferred way of doing it from my reading of the CppCore guidelines.

**Comment by franzhollerer** [comment]
I fullly agree that there are better ways to implement that logic. But it is an example how existing code looks like and will continue to live for a while.

ES.20 states:

```
The always initialize rule is a style rule aimed to improve maintainability as well as a rule protecting against used-before-set errors.
```

I think the reasoning is wrong. The compiler effectively can protect against used-before-set erros. Follwoing the *always initialze rule* inhibits this check, and therefore displace the problem it wants to protect against into runtime and testing.

I think the *object must be set before used* rule is more appropriate in some cases.

I absolutely agree with the intend of ES.20. I just want to warn that the rule may be counterproductive if someone suffers the MISRA disease and strictly enforces the rule for its own (e.g. via PC-lint).

**Comment by gdr-at-ms** [comment]
@franzhollerer  I am having hard time following your argument.  Are you observing bug/weakness in current implementations of analysis tools, or are you remarking logical consequence for analysis tools?

**Comment by franzhollerer** [comment]
I am not speaking about a bug/weakness of analysis tools. In existing code, especially if you have to maintain complicated if-then-else constructs, it is easy to intrudoce a **used-before-set error** by accident.

Compilers and static anaylsis tools are very good in detecting this bug - provided that you don't hide it with the *always initialize an object* rule.

To come back to the original example:

```cpp
  4 int main(int argc, char** argv)
  5 {
  6     // At this point we cannot provide a reasonable initialization value
  7     // for i. Actually, we have to assign an appropriate value later on
  8     // when evaluating argc.
  9     int i  = 0;  // dummy initialization to comply to ES.20
 10     
 11     switch (argc) {
 12         case 1:
 13             // ...
 14             i = 10;
 15             break;
 16         case 2:
 17             // ...
 18             // oops, forgot to assign a value to i;
 19             break;
 20         case 3: 
 21             // ...
 22             i = 30;
 23             break;
 24         // other case statements follow...
 25         default:
 26             std::cerr << "wrong argc" << std::endl;
 27             std::exit(EXIT_FAILURE);
 28     }
 29 
 30     std::cout << "i = " << i << std::endl;
 31 }
```

There is a bug in case 2. The variable *i* is not set. Thus it may contain a wrong value when used in line 30.

When ignoring rule ES.20 in line 9:

>   9     int i; //  doesn't follow *always initialize an object* rule

the compiler reveals the bug at compile time:

```cpp
$ g++  -O3 -Wall t.cpp
t.cpp: In function ‘int main(int, char**)’:
t.cpp:30:28: warning: ‘i’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     std::cout << "i = " << i << std::endl;
```

But when following the *always initialize an object* rule:

>   9     int i  = 0;  // dummy initialization to comply to ES.20

the program compiles without any error or warning.

Thus following ES.20 masks the problem. Hopefully you are testing good enough....

Beeing said, *used-before-set errors* are a well know problem. There is put much effort into compilers and tools to detect it. We should allow the tools to do their job and not annul that effort.

**Comment by gdr-at-ms** [comment]
Thanks for elaborating.  The problem isn't that ES.20.  The problem is you have a complex initialization. We considered this and many other scenarios from existing real life code and what happened to them over maintenance, and invariably landed where the rules are today.

The guidelines don't prevent compiler from doing their jobs.

**Comment by MikeGitb** [comment]
@franzhollerer: I also have found one or two bugs thanks to such a compiler warning (in one case it was actually asan), but I actually had more false positives with this than usefull warnings (and it afaik only works for builtins anyway). 

One other posibility (where applicable) is to initialize the variable to some "obviously wrong" value and assert later that the value has been changed. Of course that only provides you with feedback at runtime instead of a compiler warning, but at least, you don't risk UB.

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, complex initialization code can work, but in practice it does lead to bugs. People get this wrong, and maintain it wrong. Thanks for the great discussion, but we're sticking with the rule as written.

**Comment by MikeGitb** [comment]
@AndrewPardoe: I think no one questions that complex initialization should be avoided if possible, but are you convinced that it is actually possible most of the time and hence we don't have to worry about how to make it safer?

Lots of production code has to deal with special cases in one whay or another and in my(limited) experience, those special cases are usually what leads to complex code. Just think about parsing a date time string for example or unicode.

**Comment by viboes** [comment]
@franzhollerer When you want to follow the E.20 rule you should initialize the variable with a dummy value, but with a good one (a lambda should cover most of the cases).

@MikeGitb If the logic is much more complex (you have surely a design issue), I will suggest to comment your line so you state explicit that you understand that it is better (at least for the time being) to let it uninitialized (// NOLINT with a good explanation).

Other cases where variables are uninitialized, is where they are initialized by an out function parameter. If you can not refactor such a xxxFct function (so that you return the value) I don't think this rule is requesting you to initialize it with a dummy value, but just is suggesting your to add a comment // NOLINT uninitialized but assigned by xxxFct.

Don't let the exceptional cases let your code with a lot of uninitialized variables, which all of us recognize is a source of problems.

You could then expect that static analysis tools help you to identify not uninitialized variables that are read before assignment.

Just my 2 cts.

**Comment by quicknir** [comment]
The core guidelines does not discuss this technique, but IMHO if you use immediately evaluated lambdas (or, as they are called in other languages, immediately evaluated function expressions, IEFE), you can provide a better solution for this.

```
const auto i = [&] {
    switch (argc) {
        case 1: return 10;
        ....
    }
} ();  // ends lambda temporary, and immediately evaluates returning result
```

This also works with e.g. variables you want to set based on try-catch. Obviously you can factor this out into a  function, but there are plenty of times where the logic is small and not reusable, so moving it out of line, exposing it, and giving it a name is disadvantageous. Factoring out into a function is already available as a technique, yet often programmers will avoid it (for aforementioned reasons), and either not initialize a variable or initialize it to something meaningless. We can argue about which of these is worse, but they're both pretty bad. IEFEs essentially let you turn anything into an expression, and that can be used to avoid either one of these. As a bonus it enables const, and works for immutable or otherwise unassignable objects.
