### ISSUE TITLE
C.40 the Notes could be clearer or maybe off topic

### ISSUE THREAD

**Issue by tlanc007** [isocpp/CppCoreGuidelines#1017]
(I wanted to see what others thought before attempting a pull request)

First technically for both the first **Note** and the second **Note** (which I will call **Note1** and **Note2** respectfully) as they are a structs no constructor is needed and the fields could be initialized with say `Rec2 {7, "Foo Bar"};`

I propose deleting **Note2** and tweaking **Note1**.

Here is **Note2** as it stands:

The C++11 initializer list rule eliminates the need for many constructors. For example:

```
struct Rec2{
    string s;
    int i;
    Rec2(const string& ss, int ii = 0) :s{ss}, i{ii} {}   // redundant
};

Rec2 r1 {"Foo", 7};
Rec2 r2 {"Bar"};
```

**Note1** already making use of a member initializer list: `int i {0};`  **Note2** proceeds to say that Rec2 constructor is redundant. But the reason it is redundant isn't because of initializer list rule but because of *aggregate initialization*.  Furthermore *aggregate initialization* doesn't work on classes.

So I propose dropping **Note2** and tweaking **Note1** to read: (struct changed to class and text added after).

A constructor can be used for convenience even if a class does not have an invariant. For example:

```
class Rec {
public:
    string s;
    int i {0};
    explicit Rec(const string& ss) : s{ss} {}
    explicit Rec(int ii) :i{ii} {}
};

Rec r1 {7};
Rec r2 {"Foo bar"};
```

Note: that in the above example, `int i {0}` makes use of C++11 initializer list rule.  See **C.48**.

**Comment by cubbimew** [comment]
To be consistent, if a class does not have an invariant, then it uses the keyword struct, per [C.2](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-struct)

**Comment by jwakely** [comment]
> Furthermore aggregate initialization doesn't work on classes.

That's incorrect, it only works on aggregates, but whether something is an aggregate has nothing to do with whether it's defined as a `struct` or a `class`.

**Comment by jwakely** [comment]
I suggest closing this issue, I don't see anything to fix. The issue seems to be based on an artificial distinction between structs and classes.

The only thing I'd change about the notes would be to change "member initializer" in **Note2** to "default member initializer" (that's the correct name for what C.48 calls an "in-class initializer").

**Comment by tlanc007** [comment]
@cubbimew : Thanks.  I missed C.2.

@jwakely : Hmm.. I thought I tried an example as struct vs class and the struct worked, but the class didn't.  I'll try to dig up my example again.  If I can't reproduce it. I'll go ahead and close this out.

**Comment by cubbimew** [comment]
> The only thing I'd change about the notes

"The C++11 initializer list rule" could be made less ambiguous too. The note is showing a C++03 struct that could be improved in modern C++ due to default member initializers (C++11), default member initializers coexisting with aggregate initialization (C++14), and direct list-initialization syntax (C++11, though `Rec2 r1 = {"Foo", 7};` was valid C++98). How about "Modern C++ eliminates the need for many constructors."

**Comment by jwakely** [comment]
The only semantic difference between `struct` and `class` is whether bases and members are `public` or `private` by default. Any claim about different initialization syntax being valid is bogus.

**Comment by tlanc007** [comment]
@jwakely Yes, you are correct.  This is what I meant by differences between struct/class:

```
struct A
{
    int i;
    std::string s;
};

A a1 {};
A a2 {5};
A a3 {5, "bob"};
```

if someone just blindly says, oh, let's make this A a class and **only** changes the keywords from **struct** to **class**.  Then it won't compile as it is no longer same as the original code.  Either they need to make the member fields public or they will need to add the appropriate constructors.

Then if one is trying to use the member initializer:

```
struct A
{
    int i {2};
    std::string s;
};

A a1 {};
A a2 {5}; // fails under C++11
```

The example is fine under C++14, but won't compile under C++11.

So I felt that the example raised more questions than helped.

**Comment by jwakely** [comment]
> let's make this A a class and only changes the keywords from struct to class

Then it's not an aggregate, so aggregate initialization isn't allowed. That's not a difference between structs and classes. You get the same behaviour if you add `private` to the `struct A` version.

> The example is fine under C++14, but won't compile under C++11.

That's because of the revised definition of an aggregate, not anything to do with `struct` vs `class`.
