### ISSUE TITLE
Guidlines on how to use C++ with interrupt service routines

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#1022]
Dear C++ Core Guidline team.

I would welcome some guidelines on how to use C++ with interrupts, especially on bare meteal embedded systems.

Which data structures, containers, algorithm from the standard library can be safely used to pass data from the interrupt service routine to the main thread?

I think it is somehow related to the *Concurrency* section, but might be a subject for its own. I find it very challanging to find reliable informatin aobut this topic.

**Comment by jwakely** [comment]
I think the special requirements of bare metal systems are not suitable for the guidelines, because the details vary so much from system to system. You should ask your implementation vendor.

**Comment by phillipjohnston** [comment]
Hi Franz,

Please feel free to contact me via email for your specific embedded questions. Knowing more about your specific use case will help me provide the most useful advice. 

Here are some general interrupt guidelines that I can share with you:

* Interrupts should be handled as quickly as possible so you can resume execution on threads
* Any processing that takes significant time should be avoided
* Avoid operations with locks as you can deadlock your program in an ISR
* Avoid operations that involve dynamic memory allocations, as the implementation may require a lock and the allocation typically takes a nondeterminate amount of time

Generally, from an interrupt, you will want to keep your operations simple and should have very little data that you need to pass out of the ISR. Perhaps you want to use something like `std::atomic` (lock free) to pass a flag or value out of your ISR.

Generally, I am using an RTOS on my embedded systems. My ISRs will typically just set an event flag and clear the hardware interrupt/status register. I have other thread(s) in my system waiting to be woken by these events which handle the detailed processing in normal user space. With this model, you will be able to utilize any data structure :)

Cheers,

Phillip
Embedded Artistry <https://embeddedartistry.com/> | Newsletter <https://embeddedartistry.com/newsletter/> | Github <https://github.com/phillipjohnston>

**Comment by phillipjohnston** [comment]
@jwakely, I'm still a relatively new C++ developer, so I'm not sure on this point:

Is there a type other than `condition_variable` (which requires a lock) which allows `std::thread` to sleep and be woken by a specific value? Perhaps something based on `std::atomic`?

If there is such a thing, I would be able to draft generic/portable guidelines for interrupt handler best practices.

**Comment by franzhollerer** [comment]
Thanks @phillipjohnston for the detailed answer. What you describe is the way I do it with ordinary C.

> Is there a type other than std::condition_variable (which requires a lock) which allows std::thread to sleep and be woken by a specific value? Perhaps something based on std::atomic? I have not found any such type in my search so far.

That's coming closer to what I am looking for. With thread support there came a lot of interesting stuff to the C++ language. It would be interesting to know which of them and how they can be safely used from interrupt.

Same for containers like std::array, std::stack or std::qeueu. Is it possible to use them, and if yes under which conditions?

Or is it better to stick with C?

**Comment by phillipjohnston** [comment]
> Or is it better to stick with C?

Well, I wouldn't go that far :). I still find plenty of benefits from migrating to C++, even if I still must use the RTOS primitives for events.

> With thread support there came a lot of interesting stuff to the C++ language. It would be interesting to know which of them and how they can be safely used from interrupt.

Most of the `std::thread` stuff I have examined so far is great for the actual threading behavior, though the use of locks makes it not suitable for an ISR.

I haven't done a deep analysis of all C++ types for thread safety. Doing a brief scan, `std::bitset` and `std::atomic` seem safe. `array` seems OK too because of the static size requirement, however you could potentially run into data access race conditions if your interrupt is producing data faster than your threads are consuming data. Other than `std::array`, containers utilize dynamic memory allocation so are not really suitable for ISRs.

I think the current native C++ ISR difficulties stem from syncing the threads to the ISR event - based on what I know at the present time, there's not a great way to block on a condition without utilizing a `lock`. Perhaps I should try creating a library that could tackle this use case.

**Comment by cubbimew** [comment]
Is this issue about "bare metal embedded systems" (which?) or about RTOS (which)? For the latter, I would point out that the standard C++ threading model currently lacks the concept of scheduling priority (and priority inheritance/priority protection, etc), and so it doesn't work with the RTOS I am familiar with, LynxOS.

**Comment by MikeGitb** [comment]
The closest thing standard c++ has to the concept of interrupts and isrs are asynchronous signals and signal handler and you are not allowed to use any of the standard library containers. You can read the details here: http://en.cppreference.com/w/cpp/utility/program/signal.

Keep in mind: This is not only a question of atomicity of an operation (which is hard enough), but also about compiler optimizations that might reorder or completely eliminate an operation.

**Comment by franzhollerer** [comment]
> Is this issue about "bare metal embedded systems" (which?) or about RTOS (which)? 

Sorry, I was imprecise. I am involved in both kinds of applications. Some are bare metal, some with RTOS. Thus speaking for me, advices on both are welcome.

> The closest thing standard c++ has to the concept of interrupts and isrs are asynchronous signals and signal handler and you are not allowed to use any of the standard library containers.

@MikeGitb to my understanding the singals and signal handler in C++ are wrapping to the features provided by a POSIX complaint OS. They only work on a hosted implementatin. Right?

I am more interested in guidlines for freestanding implementations.

Anyway, the discussion gave me some interesting points and ideas I can further work on. Thanks to everone for the input.

**Comment by MikeGitb** [comment]
@franzhollerer: Correct, the c++ standard doesn't know anything about ist, so strictly speaking, any advice can only ever be dependent on your particular platform or compiler.

However, from a compiler's perspective, an interrupts are has very similar to asynchronous signals: They can appear at any point in time and an optimizing can't be expected to maintain a consistent state of all variables that may be reachable by an isr, in memory, at all times. 
Hence, as a rule of thumb,  you can assume that similar restrictions apply, which more or less means: Only use (lockless) atomics and/or std::atomic_signal_fence.

That being said, just like inter-thread communication has worked before c++ standardized the notion of threads, compilers allowed you to safely work with isrs for decades and they are unlikely to turn previously well defined behavior into undefined behavior just because c++11/14/17 came around (just as it is unlikely that they won't break multi-threaded code that is posix compliant but has data races according to c++11). So if you look up the documentation of your toolchain, there will most likely be more information about the topic than what you can find in the standard (which is afaik zero).

**Comment by gdr-at-ms** [comment]
This is highly dependent on the `bare metal` and the operating system.  Most of these have an interface in C that can be used from C++.  The C++ standards have nothing specific in this area, though the lock free functionalities might come useful.

**Comment by jwakely** [comment]
@phillipjohnston http://wg21.link/p0514 proposes adding something that might be what you're looking for.

**Comment by jwakely** [comment]
As stated above, advice on using C++ on bare metal systems is not suitable for the core guidelines, as any advice would be non-portable and not useful to most readers of the guidelines.

**Comment by phillipjohnston** [comment]
Thanks for the link Jonathan, that's exactly the kind of thing I'm looking for :)

Cheers,

Phillip
