### ISSUE TITLE
Prefer using an implementation of optional over using floating-point NaN?

### ISSUE THREAD

**Issue by louis-langholtz** [isocpp/CppCoreGuidelines#1028]
What do other coders think of a suggestion like: **Prefer using an implementation of `optional` over using a floating-point NaN for optionally valid values.**?

My initial thoughts on this are along the lines of what I suspect is similar to suggestions in favor of using the upcoming `std::optional`, like making the intention explicit. Beyond those however, is avoiding the inconsistent behavior one can get with `NaN` values between "non-signalling" and "signaling" NaNs, or finding that NaN values compare as not equal until using fast-math. Or avoiding overloading the meaning of `NaN` where the `NaN` could have also come from results of floating-point operations.

While `std::optional` isn't available till C++17, `boost::optional` and other implementations of an *optional* like template class are also available before it.

Beyond my initial thoughts, I suppose a problem with this as a suggestion, could be that it's not general enough. Maybe instead a guideline along the lines of: **Prefer using an implementation of `optional` over using a sentinel value as an indicator of a non-valid value.**

Here's a StackOverflow Q&A related to this: [Usage of std::optional vs. “unused/default” values](https://stackoverflow.com/questions/43528308/usage-of-stdoptional-vs-unused-default-values).

**Comment by egeerardyn** [comment]
I agree with you that sentinel values can be bad, but I only think this is the case when sentinel values are ambiguous and do not behave in the proper way. E.g. the integral value "-1" is often used as a sentinel value meaning "absent" or "invalid", but the problem with such values is that:

1. It is ambiguous: when you encounter "-1", does it mean "negative one" (i.e. valid) or "invalid"?
2. It obeys the rules of normal math, which is not what "invalid" values would obey (e.g. invalid + value = invalid). To overcome this, one would need to check at each operation whether the sentinel is present and act accordingly, i.e. one effectively has to create a different type for it (and at that point, indeed `optional` is a very good candidate.

However, in the case for `NaN` in floating point types, I do not think it makes a lot of sense to advocate putting floating point numbers in optionals in general to avoid `NaN`. `NaN` already unambiguously encodes that a value is invalid and it obeys quite sane rules with respect to other values and other `NaN` values. Also, for me a typical use case of `double` is within a `vector` or `valarray`: wrapping each element in an `optional`  is really inefficient, whereas the `NaN` already provides very similar functionality (but it does require some experience with floating point math).

So I do support your suggestion: **Prefer using an implementation of optional over using a sentinel value as an indicator of a non-valid value.**, but I do not agree with your floating point example.

**Comment by egeerardyn** [comment]
I agree with you on the fact that in interfaces/return values, using
`optional<double>` is clearer and better states the intent than a NaN value
(so is preferable). So the same goes for the reformulated guideline.

I don't really see the portability issues, since I would guess that any
platform with a modern c++ compiler should also support IEEE754, but I
might be mistaken on that.

Sent from my phone

On Aug 22, 2017 00:03, "Louis Langholtz" <notifications@github.com> wrote:

Thanks for joining the conversation on this!

I agree with what you're saying. I wouldn't want to wrap a valarray of
floats in optional either and I think your point, that float is already an
explicit optional in the compact sense
<https://akrzemi1.wordpress.com/2015/07/15/efficient-optional-values/>, is
a valid one by the definition of IEEE 754
<https://en.wikipedia.org/wiki/IEEE_754>.

When I was considering NaN vs. optional, I was thinking in different terms
than this.

I was thinking in terms of explicitly using a NaN value (like the value of
std::numeric_limits::quiet_NaN()) in a returned instance of a class having
additional fields, to indicate that the entire returned object was invalid.
Additionally it was for code where an exception wasn't appropriate and the
code was being designed to be portable. In such a context, the explicitness
of NaN seems decreased. Decreased by virtue of the additional fields and by
virtue of IEEE 754 not being guaranteed for all platforms the code might
run on. This versus optional<Foo> that is.

In light of your input, how about the following refinement of the
suggestion you supported: *Prefer using an implementation of optional over
coming up with your own sentinels for indicating invalid values*.

Otherwise, without such a refinement, I could see the guidelines being
applied to suggest exactly what we've agreed it'd be unappealing for: when
the value already has a well defined sentinel for indicating it's invalid.

Again, thank you for your involvement; I appreciate it very much.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/isocpp/CppCoreGuidelines/issues/1028#issuecomment-323864713>,
or mute the thread

**Comment by gdr-at-ms** [comment]
Most people who use floating point for a living are used to, and understand `NaN`s.  They will just ignore such a recommendation.

**Comment by louis-langholtz** [comment]
@gdr-at-ms I should have edited the title apparently. No idea if the new title would make any difference in the outcome but at least the new title more accurately reflects the gist of where this issue evolved to.
