### ISSUE TITLE
Change ES.87 to mention differences between ints and bools

### ISSUE THREAD

**Issue by AndrewPardoe** [isocpp/CppCoreGuidelines#1032]
Also, some systems don't have 0 as a success code.

**Comment by hsutter** [comment]
Capturing the issue: Comparison against bool (including conceptually a pointer comparison of "not nullptr") is fine to say tersely, such as `if(found)` rather than `if(found==true)` or `if(p)` instead of `if(p!=nullptr)` or `if(p!=0 /*here 0 is not an integer, it's the null pointer constant*/)`.

However, comparisons against an integer value are what cause problems, such as `if(strcmp(...))` which does not mean "if equal" (as already captured in a "bad" example) or `if(something_that_returns_error_code())` where a return value of `0` means `success` and it's easy to invert the meaning.

So it's the implicit integer comparison to mean `!=0` that causes pitfalls in practice, and being explicit reminds the programmer to think about the meaning of the comparison. Whereas with the implicit boolean comparison to mean `==true`/`!=nullptr` those additional boilerplate expressions are just noise and not known to be pitfalls.

**Comment by BjarneStroustrup** [comment]
Example and comments added
