### ISSUE TITLE
running the core guidelines checker(s) in a browser? 

### ISSUE THREAD

**Issue by kcc** [isocpp/CppCoreGuidelines#1039]
Hi. 
Is there a way to run core guidelines checker(s) from VS++ in a browser?
This might be useful for the folks w/o easy access to the VS++ installation (like me). 

If it's not possible, what's the simplest one-liner to install a bare bones toolchain and one-liner to run the checker (from command line)?  
The closest I found is [this page](https://blogs.msdn.microsoft.com/vcblog/2017/08/15/how-to-use-the-c-core-guidelines-checker-outside-of-visual-studio/) by @AndrewPardoe but it's not a one-liner :(

**Comment by neilmacintosh** [comment]
For the future: this question is probably best asked over at the VS feedback website, or using our cppcorecheck@microsoft.com alias as it is about a vendor-specific tool, rather than the Core Guidelines generically.

To answer your question: not right now, no.
The page you referred to from Andrew is (AFAIK) the "simplest" path to installing a bare bones MSVC toolchain for command-line use.

**Comment by kcc** [comment]
Thanks! I've contacted @AndrewPardoe separately.
