### ISSUE TITLE
ES.46: Uses narrow instead of narrow_cast

### ISSUE THREAD

**Issue by parsley72** [isocpp/CppCoreGuidelines#1045]
ES.46 says:

> The guideline support library offers a narrow operation for specifying that narrowing is acceptable and a narrow ("narrow if") that throws an exception if a narrowing would throw away information

The first narrow should be narrow_cast.

**Comment by jwakely** [comment]
There's no need to report both an issue and a pull request, just create a pull request (explaining the issue in the P/R description if needed). This just gives us two tickets to deal with instead of one.

Also, if you must do it this way (e.g. because the issue already existed anyway before you create a pull request to fix it) putting "Fixes #1045" in the pull request description will automatically close the issue when the P/R gets merged.

**Comment by tomisaacson** [comment]
Sorry, Github confuses me!
