### ISSUE TITLE
Not convinced about F.7 (take T* or T& arguments rather than smart pointers)

### ISSUE THREAD

**Issue by BillyClem** [isocpp/CppCoreGuidelines#1058]
I am not sure yet I want to take F.7 as gold. Or maybe I do not yet internalize the accompanying note "We can catch dangling pointers statically"

Anyway, my hesitation is based on observations here in the wild.
1. T* using shared_ptr -- code author projects no use cases where raw pointers could designate non-shared T*
2. The clients of the interfaces that have T* or T& args will definitely not look around to see best or common ways to call the interfaces
3. These folks will simply new up an instance to pass, which is not what the author wanted in #1

**Comment by jwakely** [comment]
I don't understand what you've written, could you clarify?

1. What does "T* using shared_ptr" refer to?  Using `T*` has nothign to do with shared or non-shared, it designates non-owning.  
2. What do you mean? If the function takes a pointer or a reference then obviously you pass something to it by pointer or reference. Why do you need to look anything up to understand that?  
3. That violates [I.11](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ri-raw), and is just a terrible terrible idea. Why would somebody do that?

**Comment by jwakely** [comment]
See  also [R.30](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rr-smartptrparam)

**Comment by galik** [comment]
I feel that functions that only care about *using* the object should not be given the `std::shared_ptr<T>` they should receive a *reference* or *raw pointer* so that the application is free to **also** use `std::unique_ptr<T>` as well **value** instantiations of T (say on the stack or in a container).

This is important because, as far as safety goes, using container/stack based **values** is safest. Failing that `std::unique_ptr<T>`, and only if you absolutely must `std::shared_ptr<T>`. By taking a smart pointer you force the caller to **always** use pointers and you **prevent** the user from expressing other kinds of ownership (whether *unique* / *shared* / container / stack) if they need to call that function.

I think the crucial thing is learning modern pointer philosophy. Raw pointers are fine as are references. But they should **never** be used to **own** (or manage the lifetime) of an object. They should **always** be thought of as *non-owning* accessors of a resource whose lifetime is managed by something else (a container, a smart pointer, the stack, etc...). So the *fate* of an object should never be entrusted to a raw pointer however raw pointers (and references) can be used to access objects (within the objects lifespan) without a problem.

**Comment by BillyClem** [comment]
Thanks @jwakely  and @galik . I looked at R.30 ... I'll try to clarify -- my bad - I meant to start with a shared_ptr<T> . The preference being advanced, which I am still trying to internalize, is that as long as ownership is being safely handled, some functions that simply use the object should be able to declare T* or T& .

@galik , I understand the explanation, thanks. And I am not in love with declaring shared_ptr<T> and passing it that way.  Despite these excellent rationale, I am still worried about large scale implementation with programmers of varying skill. I spend virtually all of my time working in this environment, and I have seen good intentions disintegrate. Probably I can't adequately express this. In any case, it will be fine to close this issue, which is just about my reservations, not disagreeing at all that ideally people should code as laid out in the guidelines.

**Comment by jwakely** [comment]
Closing then.
