### ISSUE TITLE
Performance vs Safety During Bounds Checking and in General

### ISSUE THREAD

**Issue by jayeshbadwaik** [isocpp/CppCoreGuidelines#1070]
The cpp core guidelines  encourage use of bounds checking access `.at()` over a more performant `[]` as written [here](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rsl-bounds). As shown [here](https://godbolt.org/g/VCdK4M), the issue with this is not just that the performance is less but that certain optimizations like using SIMD instructions are disabled due to the bounds checking.  

My question is, should cppcoreguidelines have a subsection of core guidelines which do not affect performance? There is already a section which describes  how to increase performance. But I feel that is orthogonal to this above issue. What would be good is grouping guidelines into performant and non-performant. This is useful when using `clang-tidy` like tools where you don't have to manually filter out the warnings that do and do not affect performance.

**Comment by JonasToth** [comment]
The Guidelines encourage you to remove the need of bound checking as well.
So instead of using indices use iterators, that can be optimized like
unchecked access.

1. Use algorithms for your use case -> iterators, ranges improve readability
2. Use bound checked access
3. Use unchecked access after proving the need for it

Am 05.11.2017 10:28 vorm. schrieb "Jayesh Badwaik" <notifications@github.com

**Comment by MikeGitb** [comment]
JonasToth: Doesn''t really make a difference, the guidelines encourage you to use bounds checked iterators (as e.g. with gsl::span)

**Comment by MikeGitb** [comment]
There was some discussion about this over at the gsl repo: https://github.com/Microsoft/GSL, but I can't find the specific issue right now. IIRC, the impression I had was that the general opinion was somewhere between "it doesn't matter in real code" and "compilers will be able to figure it out eventually". 

Personally, I'm using my own version of an array view, that - by default, in release mode - only checks bounds when subspans are created and suppresses the warnings otherwise.

**Comment by jayeshbadwaik** [comment]
Are you referring to [this discussion](https://github.com/Microsoft/GSL/issues/402)?

**Comment by galik** [comment]
Or maybe [this discussion here](https://github.com/Microsoft/GSL/issues/376)?

@MikeGitb Funny, I also am developing my own version of span with different criteria (I wonder how many people are doing that). But as long as you can turn bounds checking off in release builds with `GSL_UNENFORCED_ON_CONTRACT_VIOLATION` then `gsl::span` actually runs very fast. So I am not sure how far I will get with my version.

Personally I think the guidelines should recommend `gsl::at` (which can turn bound checking off for release builds) rather than `container::at`. It must have been put in the library for a reason no? 

Personally I would like to see more emphasis on *assertions* (which `gsl::at` essentially uses) because they don't effect performance at runtime.

**Comment by maikel** [comment]
@galik Alot I guess. Just track the official span proposals ([latest](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0546r0.html), I think). People doing this are mostly interested in multi dimensions and or other special access needs - GPU or whatever, I don't really know. But IMO one could use AccessProperties to control the amount of bound checking you need which would be nice because it would be an uniform interface for all these cases.

All this is out of scope of the GSL, IMO. If bound checking poses too much overhead on your algorithm one simply shouldn't use `gsl::span`. I made good experience with range-v3's span implementation, which doesn't do anything but conversion constructors with `-DNDEBUG` enabled.. SIMD worked for me.

**Comment by MikeGitb** [comment]
@galik: Well, using my own array view (it is not a drop-in replacement for gsl::span) actually predates the gsl and there are other design decisions I'm not completely happy with. For a company / public project however, I'd certainly pick one of the gsl implementations out there (Some projects still don't allow c++14, so the MS Version is not really an option there, but gsl-lite looks nice).

The big problem with `GSL_UNENFORCED_ON_CONTRACT_VIOLATION` is that it turns off all contract checking - not just when iterating over a span. Most of the time I'm completely happy with runtime contract checking and the overhead it imposes.

**Comment by neilmacintosh** [comment]
I can't help but wade in here (at least briefly).

@jayeshbadwaik I'm not sure your suggestion makes sense to me. Performance is highly context-dependent. I have seen some guidelines have no impact on performance on some compilers, but block an optimization on others. So I doubt the idea of identifying "performance-impacting" guidelines in the abstract holds.

In short, I think you need to write clear, correct and robust code first. Then measure and "degrade for efficiency" when absolutely necessary, and in a way that reflects the specific performance constraints of your environment.

I thought @JonasToth captured the spirit of the Guidelines on this topic very well. 

@maikel I would encourage you to identify if bounds-checking is a significant overhead with a particular compiler and `span` implementation and then contact the vendors of both to let them know when that is the case. Good quality user feedback encourages implementations to get better!

I'd point to some of the recent source changes @annagrin made to the Microsoft GSL implementation to enable better optimization of certain `span` scenarios as an example of how specific feedback leads to improvements.

@galik actually the guidelines do recommend using `gsl::at()`. It's in the location that @jayeshbadwaik linked to at the top of the thread. Also: I hope not too many people are busy implementing their own variants of `span`. I like that multiple implementations exist, but having lots of slightly different interfaces is a different thing, and ends up being its own source of error. I have seen the codebases where everyone once "had" to invent their own string class. ;-)

**Comment by AndrewPardoe** [comment]
Thank you for starting a good discussion! We're closing this issue in favor of a scoped issue to recommend how one should use `at()`.
