### ISSUE TITLE
Add rule to prefer namespaces to classes as a way to group free functions

### ISSUE THREAD

**Issue by tmr232** [isocpp/CppCoreGuidelines#1071]
When grouping related free functions, one can either use a namespace or a class.
As far as I understand, using a namespace is the preferred way to go.
Should this not be in the guidelines?

**Comment by cubbimew** [comment]
There was a somewhat related discussion in #837. In particular, it pointed out that there are cases where a group of functions makes sense as a set of static members of some struct: `std::numeric_limits` and `std::char_traits`)

**Comment by jwakely** [comment]
How would I tell a template like `basic_string` to use a set of free functions from your namespace instead of a set of free functions from my namespace?

A type like `char_traits<T>` can be passed as a template argument, a namespace can't. It would be possible to pass a tag type as the template argument and have all the free functions take the tag type as an argument to enable finding the free functions by ADL, but that's not necessarily an improved API.

**Comment by tmr232** [comment]
I did not think about those use cases. Point taken.
Thanks!
