### ISSUE TITLE
span spec suggestions

### ISSUE THREAD

**Issue by jeroenakershoek** [isocpp/CppCoreGuidelines#1097]
I've been going over the spec of span (P0122R5) and ran into some small things

First, the span currently says that subspan requires:
`(offset == 0 || offset > 0 && offset < size()) && (count == dynamic_extent || count >= 0 && offset + count <= size())`

However, this does not include the case where `( offset == size() && count == 0 )`, which is allowed by the GSL implementation and tests. I expect that allowing this is intended, but current specification wording does not.

Also, I was wondering about some things regarding the addition of unique_ptr support to span.
It uses std::unique_ptr<element_type> or std::unique_ptr<element_type*> which doesn't allow unique_ptrs with custom deleters. Is there any reason why these wouldn't/couldn't be allowed?

**Comment by neilmacintosh** [comment]
Thanks for the comments @jeroenakershoek. Addressing them in reverse order:

Adding `unique_ptr` and `shared_ptr` support to `span` was an experiment that I'm going to undo shortly (and remove from the spec). While it looks useful at first glance, there are plenty of conversion problems it creates in practice.

You are correct. The present `subspan()` implementation does allow you to retrieve the entire span, and the wording of the paper should do the same. I'll get that fixed in the next update, thanks!
