### ISSUE TITLE
Fix Pro.safety: Type-safety profile

### ISSUE THREAD

**Issue by AraHaan** [isocpp/CppCoreGuidelines#1110]
On Windows casting ``LRESULT`` to ``LONG`` for ``SetWindowLongPtr`` in The Windows API emitts an warning if:

1. Using an C Style cast on it.
2. Using ``static_cast``
3. ``dynamic_cast``, ``const_cast``, and ``reinterpret_cast`` emitts compile error ``error C2440: 'const_cast': cannot convert from 'LRESULT' to 'LONG'`` for not only ``const_cast`` but also on ``dynamic_cast``, and ``reinterpret_cast``.

What should be appeneded to Type.1 label b on that section is this:
```
Except for Windows Operating System API related types like LRESULT and LONG needs to be casted with static cast or C style cast to avoid compile errors.
```

I will also propose an PR fix for this as this is insane noise on my VS2017 compiler because I wanted other warning types for C++ related things. Suppressing this warnings is infeasible too as it then gives no benefit over C because I hate pragma's.

**Comment by AndrewPardoe** [comment]
Thanks for the suggestion. A little background for non-Windows programmers: `LRESULT` is a typedef of `LONG_PTR` which, in turn, is typedefed to `long` or `__int64`. [Reference](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx).

First, if a change were to be made, we'd make it in the actual rules referenced, such as  an edit to [ES.48](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-casts), rather than that Profile summary text.

Second, does [ES.49](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-casts-named) handle the case that you're discussing? Or does the Windows API require that you use a C-style cast here?

**Comment by AraHaan** [comment]
Iguess ES.49 might actually work here with some testing and bashing the compiler.

**Comment by ChrisGuzak** [comment]
Isn't this case satisfied by doing multiple casts?

**Comment by AndrewPardoe** [comment]
Thank you for the suggestion. Per our editors' discussion, we don't see a need to single out the Windows API here. Also, Chris Guzak's suggestion is correct.
