### ISSUE TITLE
Improving T.61 wording

### ISSUE THREAD

**Issue by johelegp** [isocpp/CppCoreGuidelines#1146]
[T.61: Do not over-parameterize members (SCARY)](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#t61-do-not-over-parameterize-members-scary) is missing for something that is marked as SCARY.

> **Reason** A member that does not depend on a template parameter cannot be used _except for a specific template argument_. This limits use and typically increases code size.

I think the cursive part would be better understood if it read "without specifying a template argument that it does not use." We could also pluralize the whole sentence, like
> **Reason** A member that does not depend on some template parameters cannot be used without specifying template arguments that it does not use. This limits use and typically increases code size.

Secondly, in the first, bad example, the default template argument should use `<>` instead of `{}`.
Also, its following example isn't marked as "**Example, good**."
Finally, there are also two ???s.

**Comment by cubbimew** [comment]
A link explaining what SCARY means for the wider audience could help too (I believe it was first used in [n2911](http://www.open-std.org/jtc1/sc22/WG21/docs/papers/2009/n2911.pdf))

**Comment by beinhaerter** [comment]
Thanks @cubbimew for the link. Looking only at T.61 I did not get the issue. But looking at the PDF it's getting much clearer (even when only looking over the document and not reading it in detail).
I believe it would really help to extend section T.61 about information that (sticking to the sample code) Link will be instantiated for every instantiation (combination of T and A) of class List and that this duplicates code unnecessary because List only depends on T and only needs to be instantiated for every type T used in a List<T,A>.

**Comment by AndrewPardoe** [comment]
Thanks for pointing this out! Bjarne, can you finish your thoughts on this issue by substituting text for the ??? ?

**Comment by BjarneStroustrup** [comment]
Added reference to the SCARY paper
