### ISSUE TITLE
Inconsistency in a convention used for class names in examples

### ISSUE THREAD

**Issue by yuyu2172** [isocpp/CppCoreGuidelines#1148]
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#note-359

In most of the examples, classes are named in `Class_name` style.
However, in the example pointed by the link, `ClassName` style is used.
Isn't this an inconsistency?

Also, nl10 states that camelCase should be avoided if possible, so this example violates this rule as well.
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#nl10-avoid-camelcase

**Comment by blakehawkins** [comment]
I agree it's an inconsistency. May I suggest making a PR with a section in https://github.com/isocpp/CppCoreGuidelines/blob/master/CONTRIBUTING.md#document-style-guidelines ?

**Comment by AndrewPardoe** [comment]
Please see our comments on PR #1149. Thank you for the suggestion but we are declining it.

**Comment by yuyu2172** [comment]
> Per our editor's discussion, the point of this example is that HashTable is not necessarily a recommended style, but one that is used. There is no standard style.
It might also be a little strong to recommend just Stroustrup's style for everyone.
Thank you for the suggestions, but we are declining this PR.

Thank you so much for your comment.

I agree that it is too strong to recommend one style.
However, as I mentioned [previously](https://github.com/isocpp/CppCoreGuidelines/issues/1148#issue-302154285), many styles would contradict with NL.10.
If I read the rule literally, PascalCase for classes should be avoided when it is possible. I am a bit confused because from your comment there is an exception to this rule.

I would like two modifications:
1. resolve this contradiction with NL.10. as I mentioned above.
2. If multiple styles are permitted, it would be better to list them explicitly in NL.8. I did not get an impression that the style with PascalCase for classes was permitted from the current draft. 


Since the issue has been closed, this discussion may have not proceeded here. If that is the case, I am sorry.

**Comment by jwakely** [comment]
The example is showing a commonly-used style, and saying why it doesn't violate NL.5 

Examples of other styles used in real code do not all have to conform to the style recommended by the guidelines. In fact, it would be impossible to talk about some real world examples if we could only use ones that are already following all the guidelines!

The point is not "this is a good style, and we recommend it", the point is "this style does not violate NL.5".

Maybe we could add a note to NL.7 pointing to NL.10, but I think that would distract from the point of NL.5, because as Andrew said, the point is not to proscribe a single style which must be followed by everybody.

I wish people would stop spending so much time debating the naming and layout conventions, which are really not the most important part of the guidelines.
