### ISSUE TITLE
E.15 Could also recommend using `throw;`, without argument, to rethrow

### ISSUE THREAD

**Issue by mihayls** [isocpp/CppCoreGuidelines#1165]
"E.15: Catch exceptions from a hierarchy by reference" recommends to catch by reference but do not warn that re-throwing by calling `throw e` won't do what one would expect from something _looking like a "reference"_.

So in the following example re-throwing `e` will end in the `catch (const exception& e) {`, not `catch (const runtime_error& r)` event the initial exception was `runtime_error`.

```
void f()
{
	try {
		// ...
		throw runtime_error("oops!");
	}
	catch (const exception& e) {
		// ...
		throw e;   // don't: may 'slice'
// do		throw;
	}
}

int main()
{
	try	{
		f();
	}
	catch (const runtime_error& r) {
		cout << "runtime_error: " << r.what() << "\n";
	}
	catch (const exception& e) {
		cout << "exception: " << e.what() << "\n"; // OOPS! didn't expected be here
	}
	return 0;
}
```

**Comment by jwakely** [comment]
> re-throwing by calling `throw e` won't do what one would expect from a _"reference"._

Well it does exactly what happens if you throw any other reference: it throws a copy of the operand.

    int i = 0;
    int& e = i;
    throw e;

This doesn't throw "by reference" either. And `throw e` doesn't mean "rethrow" when `e` happens to be bound to the active exception, the only way to rethrow is `throw` without an operand.

But if this catches people out it could be worth mentioning. How about simply:

#### Note

To rethrow a caught exception use `throw;` not `throw e;`. Using `throw e;` would throw a new copy of `e` (sliced to the static type `std::exception`) instead of rethrowing the original exception of type `std::runtime_exception`. (But keep [Don't try to catch every exception in every function](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Re-not-always) and [Minimize the use of explicit `try`/`catch`](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Re-catch) in mind.)

**Comment by mihayls** [comment]
Looks good, but it still requires the quite long example. Also `std::runtime_error` not `runtime_exception`.

**Comment by AndrewPardoe** [comment]
Adding @jwakely's note directly per our discussion today.
