### ISSUE TITLE
CP.61: This should probably wait for the executors

### ISSUE THREAD

**Issue by imre-palik** [isocpp/CppCoreGuidelines#1234]
In the problem domains I tend to work, and how they are currently standardised, I haven't managed to come up with a good usecase for std::async().  So potentially I just simply don't understand this rule.  But as far as I'm concerned, right now it contradicts to CP.41, what I tend to follow religiously.

**Comment by MikeGitb** [comment]
I'd also rather strike this rule. A more practical an less error prone suggestion is to use a proper / established tasking library or whatever the current framework you are working in offers anyway.

**Comment by hsutter** [comment]
Editors: `std::async` is flawed but still useful in practice for many teams. It's simple and the item seems to have the correct caveats. We do agree with the subject line that this should be updated once we have executors, and since those seem to be coming reasonably soon we should rewrite the item at that point.

**Comment by imre-palik** [comment]
Could you please at least add an example where std::async is useful?

I've never seens it used in any of the codebases I worked on, and I was also unable to come up with such an example myself.  (Though I could use it with executors ...)

**Comment by MikeGitb** [comment]
> but still useful in practice for many teams. 

Is it? That is an honest question. I'M be only seen a small number of production quality code based so far, but every single one that employed Concurrency or parallelism in some form used a full fledged framework for it. 
The problem is not that std::async` has flaws, but that - most of the time  - you easily can get something significantly better.

No one is suggesting to ban std::asynchronous, but should it really be a core c++ guideline to use such a flawed abstraction, when better alternatives are available?
