### ISSUE TITLE
T.meta new rule proposal

### ISSUE THREAD

**Issue by imre-palik** [isocpp/CppCoreGuidelines#1235]
T.119 Keep your metaprograms small.

Reason: Excessive metaprograms tend to be hard to maintain, and slow to compile.

Enforcement: Flag symbols with names longer than 1 kilobyte

**Comment by hsutter** [comment]
Editors: We sympathize, but the rules can't really be enforced -- to comply with the rules people will resorts to short unreadable names and macros which only makes it worse, and some people will complain about it because it has a number in it. Besides, a 1K limit likely wouldn't compile Boost.

That said, really, we do sympathize, and we think the answer is not to try to ban TMP but actually give people the tools they need to write the code directly without resorting to TMP which is what they probably already want anyway (`constexpr` functions, the coming-soon `constexpr!` functions, concepts, etc.).
