### ISSUE TITLE
wrong link in SS-bounds to Res-simple

### ISSUE THREAD

**Issue by beinhaerter** [isocpp/CppCoreGuidelines#1253]
The section SS-bounds has three links "[Keep pointer arithmetic simple](#Res-simple)".
I can't find neither "Keep pointer arithmetic simple" nor "Res-simple" or something similar.
Is Res-simple missing or should it be a different link?
Would it make sense to add a "<a name="Res-simple"></a>Keep pointer arithmetic simple" in the section "S-unclassified To-do: Unclassified proto-rules"?

**Comment by cubbimew** [comment]
I suspect this was meant to be a link to [ES.42 Keep use of pointers simple and straightforward](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es42-keep-use-of-pointers-simple-and-straightforward) because

1. The line in Bounds.1 next to that mysterious Res-simple ("Don't use pointer arithmetic. Use span instead:") matches the first line of ES.42 ("Use gsl::span instead. [...]. Pointer arithmetic is fragile and easy to get wrong")
2. In its last line, ES.42 actually claims to be part of Pro.bounds

**Comment by beinhaerter** [comment]
@cubbimew Thanks. I agree with your findings and I'll prepare a PR.

**Comment by hsutter** [comment]
Fixed with PR merge, thanks!
