### ISSUE TITLE
ES.40: Avoid complicated expressions needs clarification

### ISSUE THREAD

**Issue by will-meig** [isocpp/CppCoreGuidelines#1261]
```
auto t1 = 0 <= x;        // bad: unnecessarily verbose
auto t2 = x < max;
if (t1 && t2)            // ...
```

This example is not clear to me. Is it saying that we shouldn't use variables to give names to expression? Or just that we should not use extremely bad names like "t1" and "t2"?

In the example above, "0 <= x" and "x < max" are straightforward tests. And "t1" and "t2" are meaningless. So of course, that's bad to introduce "t1" and "t2".

"t1" and "t2" could be renamed "x_more_than_zero" and "x_less_than_max". Then that's clear that is it useless. The names are verbose and you need to check to be sure that they are what they say.

There are cases, however where I think it makes sense to introduce explaining variables. Namely, in the opposite case where the expressions are complex and the names are more meaningful. Here's a somewhat contrived example:

```
const bool is_user_logged_in = authorisation.is_ok() && cookie.token().is_valid() && !session.is_expired();
const bool is_password_reseted = reset_request_status == Status::Done && reset_request_result == Result::OK;
if (is_user_logged_in && is_password_reseted)
```

In that case short of rewriting, the rest of the code, it is, I think, more readable with the additional variables.

It should be clear if the rule is against both versions or only the first one.

**Comment by jwakely** [comment]
You're ignoring the context, see the previous line in the example:

     if (0 <= x && x < max)   // OK

It's saying that you should not try to "simplify" that because it's already as simple as it can be. The note before the example gives more context: ignorance of operator precedence is not an excuse for breaking up simple expressions into pieces.

> In the example above, "0 <= x" and "x < max" are straightforward tests.

Right, that's the point.

>  And "t1" and "t2" are meaningless.

True, but the naming isn't the point.

> There are cases, however where I think it makes sense to introduce explaining variables.

Yes of course. The Enforcement section touches on that "How complicated must an expression be to be considered complicated? Writing computations as statements with one operation each is also confusing."

> It should be clear if the rule is against both versions or only the first one.

It seems clear to me. The rule is about avoiding complicated expressions. `(0 <= x && x < max)` is not a complicated expression, so should not be refactored to avoid it.

On the other hand, this would be a complicated expression, and should be avoided:
`(authorisation.is_ok() && cookie.token().is_valid() && !session.is_expired())
&& (reset_request_status == Status::Done && reset_request_result == Result::OK)`

The example needs to be taken in the context of the surrounding text, not just in isolation.

**Comment by will-meig** [comment]
Thanks for the clarification. And the very quick feedback!

Even with the context it wasn't that clear to me. But maybe that's just me...

**Comment by hsutter** [comment]
Editors call: This seems to be addressed. Thanks!
