### ISSUE TITLE
exceptions to "ES.63: Don't slice"

### ISSUE THREAD

**Issue by arvidn** [isocpp/CppCoreGuidelines#1283]
It seems to me that [ES.63: Don't slice](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es63-dont-slice) could be refined by allowing slicing in some situations.

Specifically, if the derived class:

1. only has one base class
2. does not have any data members of its own
3. does not have any virtual functions

Examples of this come up when "decorating" classes with strong types. For example, deriving `std::vector` to provide a strong type as the index. The derived class only provides additional type safety, no data members. It seems safe to "slice" such object into the base class, `std::vector`.

**Comment by hsutter** [comment]
Editors call: We feel this is brittle under maintenance. If someone edits the class and adds a virtual function or a data member they'll silently start to see problems.

For the example, if the derivation is to get additional type safety, allowing slicing removes that safety, doesn't it? Also vector may not be a strong motivating example for a type that is copied and therefore sliced, since vectors are probably rarely copied.

If there is a more compelling example, please comment below and ask to reopen. Thank you.

**Comment by MikeGitb** [comment]
The much bigger problem is that the example doesn't actually show a problematic case of slicing slicing. It shows copy construction of a shape. If it makes sense to construct a shape at all (otherwise it should not have a public constructor) then this is perfectly fine as in you get exactly what you expect (a shape object) nothing more, nothing less.. 

Where slicing is a problem is if you **assign** to an object through its base class e.g.

    void assign(const shape& src, shape& dest) {
        dest = src;
    }

 Now `assign( circle1, circle2)` would compile, but not the whole state is transferred.

**Comment by cubbimew** [comment]
@MikeGitb a pull request would be nice

**Comment by MikeGitb** [comment]
@cubbimew: Or someone with commit access could copy paste above lines and make the change in less time than it takes me to boot my computer and clone the repository. 

Sorry if this sounds rude, but my previous experiences show that the maintainers here (and at the gsl repo) tend to disagre with my opinions and PRs (not that I made many), which tells me that I probably don't have the necessary experience and/or skillset to contribute here. So I made the decision not to get involved beyond the occasional comment I can write from my smartphone while commuting. Anything else seems to be just wasting everybody's time.

**Comment by jwakely** [comment]
You can edit the file and submit a pull request through the web UI (although editing the huge `.md` file might be a problem on a phone).

**Comment by arvidn** [comment]
For reference, there's another similar example of deriving `std::vector` in [a tour of C++](https://isocpp.org/files/papers/4-Tour-Algo-draft.pdf) chapter 4, page 104 (at least in the draft). That code would likely suffer from similar slicing warnings according to ES.63.

**Comment by hsutter** [comment]
Thanks @MikeGitb!

IMO slicing is equally a problem for copy construction as for copy assignment. The key is the "copy" part. But I agree your example is another good one, and have expanded the example to include it.

**Comment by BjarneStroustrup** [comment]
The vector example in Tour++ could lead to slicing, but there are no actual slicing. We can't prevent all potential problems without getting into serious complications.

**Comment by MikeGitb** [comment]
@jwakely: 
>  (although editing the huge .md file might be a problem on a phone).

Yes, that is exactly the problem. 

@hsutter: I have to admit,  I still don't see,  why the copy construction is a problem (provided that it makes sense to create a Shape object in the  first place),  but as I said: Me disagreeing with one of you / the guidelines isn't uncommon and I'll defer to your judgement. 

@Bjarne: Isn't that exactly what arvin has said? He is advocating to not warn in cases such as the one in your book.
