### ISSUE TITLE
C.60 first example issue

### ISSUE THREAD

**Issue by thePETEWguy** [isocpp/CppCoreGuidelines#1315]
In C.60, in the first example, std::swap produces a stack overflow

**Comment by neithernut** [comment]
From a first glance, the following line causes a recursion:

    auto tmp = x;

**Comment by neithernut** [comment]
The problem should be resolvable by simply supplying a copy ctor for `Foo`.

**Comment by thePETEWguy** [comment]
I provided a copy ctor, but the problem persists.

My class:    

    class Foo {
    public:
	    Foo() = default;
	    Foo(const Foo& rhs);
	    Foo& operator=(const Foo& rhs);
	
	    int x = 42;
    };

    Foo::Foo(const Foo& rhs) {
	    std::cout << "Copy constructor" << std::endl;
	    x = rhs.x;
    }

    Foo& Foo::operator=(const Foo& rhs) {
	    std::cout << "Copy assignment" << std::endl;
	    auto tmp = rhs;

	    std::swap(*this, tmp);
	    return *this;
    }

The output is the following:

    Copy assignment

    Copy constructor
    Copy constructor

    Copy assignment
    Copy constructor

    Copy constructor

    Copy assignment
    Copy constructor
    ...

**Comment by neithernut** [comment]
... because the default `std::swap` will also use the copy ctor and assignment. In this case, you have to supply your own overload for `std::swap` which is using neither move nor copy construction/assignment.

Yep. To me it looks like the example could the improved. Adding all the pieces necessary would inflate the example quite a bit. Maybe some hints or notes on parts which must be supplied for this to actually work would be useful. It demonstrates a quite useful technique but leaves out some important details which are easy to miss if you don't know the idiom already. A reference to a more exhaustive explanation of the technique might also be an option.

**Comment by neithernut** [comment]
Note: contrary to my first hunch, a copy-constructor is not necessary in this example. As far as I understand, generated copy ctors never use overloaded assignment operators anyway. And the generation of a copy ctor is not prevented in any way, so the statement `auto tmp = x;` does definitely not cause any recursion.

Note to self: confirm your hunches before posting, even if you are just on your way.

So the only problem with the example really is the usage of the default `std::swap`. @cubbimew's proposed solution should be sufficient.

**Comment by hsutter** [comment]
Sounds good, thank you.
