### ISSUE TITLE
F16 Size thresholds?

### ISSUE THREAD

**Issue by loic-joly-sonarsource** [isocpp/CppCoreGuidelines#1319]
While I agree with the general direction of this rule, I have some issues with the enforcement (with the objective of developing automated tools to enforce the rule). For instance:
* Why `4 * sizeof(int)` as the threshold? Does it come from benchmarks? From internal knowledge of compilers? From enforcing the rule on real code bases, at trying to find some compromise?
* What does _size_ really mean here? `sizeof`? I'm not sure, because it would mean the following class should be passed by value...
```
template<class T> 
class ValuePtr {
  T* ownedObject;
  ValuePtr(ValuePtr const &o): ownedObject(o.ownedObject->clone()) {}
};
```
Should we consider the full size of the object? But then how to compute it? Should we just consider that a class with a user-defined copy constructor if probably better passed by const reference, no matter its size?

**Comment by neithernut** [comment]
> Why 4 * sizeof(int) as the threshold?

Disclaimer: I don't know. But off the top of my hat, there may be two reasons why `4 * sizeof(int)` makes sense:
 * on most platforms, you'd expect pointers (which is used for passing values by reference) to have "about" the same size as an `int`. Clearly, if the object passed is of the same size, you gain nothing by passing it by reference but you pay each time you dereference it. Large objects on the other hand will inflate the stack frame and require a copy operation.
Where the exact sweet spot is probably depends on the specific function, e.g. the number of times the value is dereferenced. Maybe someone counted machine instructions on some architectures, maybe someone just said "four" makes sense.
* on some platforms, the calling convention is to pass a specific amount of arguments/data via registers (I think it was "four" on x86-Linux) rather than the stack. Also, small objects may be completely stored inside registers. As you'd expect an `int` to have the size of a register, this may give you a maximum size of `4 * sizeof(int)` to be storable in/passable via registers.

> What does size really mean here?

Obviously the size of the "entire" object. This is also apparent from some of the examples involving `std::string` (at least if you ignore small-vector optimization). On how to compute that: I don't know. At least for stuff in the STL, you could have assumptions built into your tool. You could also try to build some heuristics for detecting owned pointers (e.g. look for `new` and/or `delete`) and declare objects of these types "large".

**Comment by neithernut** [comment]
I just looked through the history in the hope I would find some rationale in the commit message or at least who came up with the "four". Turns out that it originally stems from the "Initial checkin" commit (947cf3affcdfc392a316a32f73cdea7383ae55bd, tag v0.1). The line was only moved and style-fixed since then.

**Comment by loic-joly-sonarsource** [comment]
Hello @neithernut, thank you for your help.
I think that for now, I will just tell in the tool that if the object has a user-defined copy constructor, it should be passed by const reference, no matter its size.

**Comment by hsutter** [comment]
I would suggest expressing it in terms of pointers, not integers, and say `2*sizeof(void*)`. That covers pairs of iterators, pairs of pointers, and such. (On 64-bit platforms it's common to have int be half the size of a pointer for historical reasons.)

It's just a heuristic, but as for actual measurements, my understanding is that this an efficiency threshold in some ABIs including the Itanium ABI. Niall Douglas did extensive measurements for Boost.Outcome pass-by-value on various platforms and IIRC found this (2-pointer-sized) to be a sweet spot.

**Comment by hsutter** [comment]
It also came up in discussions about `span` and compiler vendors told us that a 2-pointer-sized object would be likely to be passed efficiently by value.

**Comment by hsutter** [comment]
Editors call: We agree, commit pushed. Thanks!
