### ISSUE TITLE
C.130 Issues in example

### ISSUE THREAD

**Issue by oleksandrkozlov** [isocpp/CppCoreGuidelines#1423]
Below example from [C.130](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rh-copy) has several issues:
``` cpp
class B {
public:
    virtual owner<B*> clone() = 0;
    virtual ~B() = 0;

    B(const B&) = delete;
    B& operator=(const B&) = delete;
};

class D : public B {
public:
    owner<D*> clone() override;
    virtual ~D() override;
};
```
1.  The signature of the `clone` method contradicts with [Con.2.](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconst-fct) Therefore the method should be `const`.
2. The `B` class contradicts with "rule of five" [C.21](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-five).
3. A pure virtual destructor is redundant in the `B` class because there is already a virtual function.
4. The destructor of the `D` class contradicts with [C.128](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rh-override). The `virtual` keyword is redundant. But actually, the destructor itself contradict with "rule of zero" [C.20](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-zero). The destructor isn't needed at all.
5. It’s impossible to implement the `B::clone` method with a deleted copy constructor of the `B` class because the copy constructor of the `D` class is implicitly deleted as well (see [build error](https://godbolt.org/z/RS4hIH)).

``` cpp
owner<D*> D::clone()
{
    return new D{*this};
}
```

The same issue with an example in [C.21](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c21-if-you-define-or-delete-any-default-operation-define-or-delete-them-all).

``` cpp
class ClonableBase {
public:
  virtual unique_ptr<ClonableBase> clone() const;
  virtual ~ClonableBase() = default;
  ClonableBase(const ClonableBase&) = delete;
  ClonableBase& operator=(const ClonableBase&) = delete;
  ClonableBase(ClonableBase&&) = delete;
  ClonableBase& operator=(ClonableBase&&) = delete;
};
```

The `clone` method doesn't make sense here, because it’s impossible to implement it.

Therefore, taking into account all the above and already opened issue https://github.com/isocpp/CppCoreGuidelines/issues/1151, I propose the following example for [C.130](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rh-copy):

``` cpp
class B {
protected:
    B(B&&) = default;
    B(const B&) = default;
    
    B& operator=(B&&) = default;
    B& operator=(const B&) = default;
    
public:
    virtual ~B() = default;

    virtual owner<B*> clone() const = 0;
};

class D : public B {
public:
    owner<D*> clone() const override;
};
```

And also I propose to update the example that I mentioned from [C.21](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-five).

**Comment by MikeGitb** [comment]
Please yes. In particular the deleted copy and assignment operators in the current are plain wrong (as discussed in #1151.

A few requests though: 

1) In your example, `D` can not be constructed at all. There should probably be a defaulted default constructor added to `B` and `D`
2) The signature of the clone function should imho be `std::unique_ptr<B>` clone() const`.
 There are situations, where you want to make use of the covariant return types and hence can't use smart-pointers, but that should be the exception, not the rule. 

3) It might make sense to also show the actual implementation of `clone`, which nicely demonstrates at least one reason, why you usually do want (protected) copy constructors in the base class.
4) Personally I'd make `D` final. Otherwise, chances are far too high that someone inherits from `D` and forgets to also implement `clone()` or that slicing happens. If one needs an extensible class hierarchy, I'd recommend to go the `AbstractD` route similar to what I've shown here :https://github.com/isocpp/CppCoreGuidelines/issues/1151#issuecomment-371983428
4) I'm I the only one who finds B and D (instead of Base andDerived) not immediately obvious?

**Comment by oleksandrkozlov** [comment]
> 1. ... There should probably be a defaulted default constructor added to B and D @MikeGitb 

I agree about adding a default to `B`, but why is it needed in `D`?

> 2. The signature of the clone function should imho be `std::unique_ptr<B> clone() const`. @MikeGitb 

In this case, [the reason for C.130](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#reason-132)  should be changed as well. Because now it's not clear either `unique_ptr<B>` or `owner<D>` should be used by default and why.

> 3. It might make sense to also show the actual implementation of clone @MikeGitb

Isn't an implementation of `clone` trivial?

```
owner<D*> clone() const override
{
    return new D{*this};
}
```
or
```
unique_ptr<B> clone() const override
{
    return make_unique<D>(*this);
}
```

> 4. Personally I'd make `D` `final`. @MikeGitb

If someone inherits from `D` it will be mean that `D` can be used polymorphically. Therefore [C.67](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c67-a-polymorphic-class-should-suppress-copying) can be applied to `D` as well. In this case, making default operations protected in `D` should solve the issue.

> 5. I'm I the only one who finds B and D (instead of Base and Derived) not immediately obvious? @MikeGitb

It may be not obvious because different names are used in different examples. In one rule `Base` and `Derived` are used, in other - just `B` and `D`. It would be nice to have an agreement about naming in examples.

**Comment by beinhaerter** [comment]
@oleksandrkozlov 

> A pure virtual destructor is redundant in the B class because there is already a virtual function.

Why? It seems I am missing something. When you delete the virtual destructor then you would only have a non-virtual one and deleting a `B*` would only call the destructor of B, wouldn't it?

> return make_unique<D>(*this);

This calls the copy-ctor of D which does not exist because there is no copy-ctor for B. Compiler output:

>memory(2042,66): error C2280:  'D::D(const D &)': attempting to reference a deleted function
>foo.cpp(65): message :  compiler has generated 'D::D' here
>foo.cpp(65,1): message :  'D::D(const D &)': function was implicitly deleted because a base class invokes a deleted or inaccessible function 'B::B(const B &)'
>foo.cpp(54,2): message :  'B::B(const B &)': function was explicitly deleted

**Comment by oleksandrkozlov** [comment]
> Why? It seems I am missing something. @beinhaerter 

I was talking about a **pure** virtual destructor, my point is that a **default** virtual destructor is enough.

> This calls the copy-ctor of D which does not exist @beinhaerter 

That's why special operations shouldn't be `deleted`, they should be `default` and `protected`. Please see an [example](https://godbolt.org/z/3IzPiv).

**Comment by beinhaerter** [comment]
OK, understood. Thanks.

**Comment by MikeGitb** [comment]
> I agree about adding a default constructor to B, but why is it needed in D?

I guess my assumption was that D could not be constructed otherwise - I may be wrong. 

> Isn't an implementation of clone trivial?

Yes it is, but if you look at the issue I linked , it seems that some people expect (at least from the top of their head) `D::clone` to be implemented in terms of `B::clone` and a DC I said, it perfectly demonstrates one reason,  why copy constructors should not be deleted. 

> If someone inherits from D it will be mean that D can be used polymorphically. Therefore C.67can be applied to D as well. In this case, making default operations protected in Dshould solve the issue.

Sure, but one should be picked. Either it represents the leaf in a hierarchy, in which case it imho should be final, implement clone and have public special member functions, or an intermediate node in which case the special member functions should be protected, and clone should not be implemented (and hence D would be abstract). 

I know this opinion is not necessarily shared by other c++ developers though.

**Comment by cubbimew** [comment]
this may be a subtask of #1635

**Comment by cubbimew** [comment]
closing this one due to https://github.com/isocpp/CppCoreGuidelines/pull/1851

**Comment by oleksandrkozlov** [comment]
Thanks for the update, but there is still the redundant destructor ` ~D() override {};` in [C.130](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c130-for-making-deep-copies-of-polymorphic-classes-prefer-a-virtual-clone-function-instead-of-public-copy-constructionassignment)  and the example [C.21](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c21-if-you-define-or-delete-any-default-operation-define-or-delete-them-all) is still not fixed.

**Comment by cubbimew** [comment]
@oleksandrkozlov make a PR dropping the destructor, they get looked at before issues.
As for C.21, I'd add a comment to #1635 which we kept open for other clone-related problems.

**Comment by oleksandrkozlov** [comment]
@cubbimew Sure.
PR: https://github.com/isocpp/CppCoreGuidelines/pull/1855
comment: https://github.com/isocpp/CppCoreGuidelines/issues/1635#issuecomment-968314208
