### ISSUE TITLE
Suggestion: detail C.164 or create a new rule for constness vs. explicitness in conversion operators

### ISSUE THREAD

**Issue by moretromain** [isocpp/CppCoreGuidelines#1431]
When defining both explicit const and implicit non-const conversion operators, constness takes precedence over explicitness, and the compiler might choose an unexpected non-const implicit conversion operator over a reachable const explicit one, which is in that case mistakenly considered as more appropriate.

Clumsy example here:
https://godbolt.org/z/8VJbEq

This is just emphasizing C.164, which mentions avoiding using implicit conversion operators. But maybe this rule could be extended by stating that one shall define both const and non-const versions of explicit conversion operators when possible.

Or maybe there is enough here to create a new rule about explicit conversion operators ?

This const vs. explicit thing caused me massive headaches by the past, and now I systematically define both const and non-const versions of explicit conversion operators, especially the bool one, which is often implemented as a response to a "serious need".

I'd be glad to contribute to a more elegant and appropriate example and explanation.

**Comment by jwakely** [comment]
This isn't a problem I've ever encountered, probably because I wouldn't have two conversion operators to different types that would both be viable for a given conversion sequence, and generally don't write non-const conversion operators anyway. Doing either of those things seems like the problem, not the lack of const/non-const overload pairs.

> one shall define both const and non-const versions of explicit conversion operators when possible.

That seems like a bad rule. It's absolutely not necessary for most explicit conversion operators to be overloaded, because many (most?) classes have at most one conversion operator, and if it's the only one then there's no point overloading it for non-const.

Although the following is too complicated to be useful, I think a better guideline would be:

 - Avoid implicit conversion operators, **especially** if you also have explicit conversion operators.
 - If that's not possible, avoid implicit conversion operators when there are other conversion operators for types that are convertible to each other. e.g. Don't have an implicit conversion to `int` as well as a conversion (either implicit or explicit) to `bool`.
 - If that's not possible, avoid mixing both const and non-const conversion operators. e.g. don't have `operator int();` and `operator bool() const;`.
 - if that's not possible, overload const conversion operators with a non-const version, so some other non-const conversion to a different type won't be unintentionally used in non-const contexts.

i.e. using a const/non-const overload pair should be the last resort, not something to do by default.

**Comment by moretromain** [comment]
I think you're right here, having a rule that defines the usages and combinations of implicit/explicit/const altogether doesn't bring a viable solution since the problem really is the presence of multiple conversion operator in the same class, no matter how they are qualified.

I think the rule itself says enough, **Avoid implicit conversion operators**, but maybe there could also be a note about explicit operators like:

- An `explicit `conversion operator doesn't take precedence over any existing `implicit` one. In some contexts, the `implicit `operator is still chosen over the `explicit` one, resulting in even more unexpected and surprising results. In any case, `implicit` conversion operators should be avoided.

And you're right, specifying those contexts might be too complicated to be useful, and when it comes to explicit operators, I guess this guildeline becomes: `explicit` conversion operators don't make `implicit` ones ok. 

My point is just that a note that reminds that `explicit` is not a fix for `implicit` could help the newcomers, and be a good thing to remember.

**Comment by hsutter** [comment]
Editors call: Thanks for the note. We've reviewed it, and we think it's best as it stands -- we agree that the rule itself covers this, as you say, and while the additional note would be true we're trying to keep each guideline relatively concise and not document all possible corner cases.
