### ISSUE TITLE
should SF.6, SF.7 exempt using namespace std::literals?

### ISSUE THREAD

**Issue by ChrisGuzak** [isocpp/CppCoreGuidelines#1440]
[SF.6](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#sf7-dont-write-using-namespace-at-global-scope-in-a-header-file) and [SF.7](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#sf6-use-using-namespace-directives-for-transition-for-foundation-libraries-such-as-std-or-within-a-local-scope-only) say no using namespace use in .h files.

It seems `using namespace std::literals;` should be allowed as this is needed to use the literals and according to a college they is safe now and in the future.

should these be updated to list this as an exception?

**Comment by cubbimew** [comment]
Same reasoning applies: such headers would be impossible to use alongside libraries that define their own literals.

**Comment by jwakely** [comment]
But those libraries have to use names prefixed with an underscore, so shouldn't clash with any in `std::literals`.

**Comment by cubbimew** [comment]
@jwakely indeed, good point.

**Comment by ChrisGuzak** [comment]
is this worth noting this as an exception? if so I can prepare a PR.

**Comment by MikeGitb** [comment]
Why does the standard library not put them into the global namespace?

**Comment by hsutter** [comment]
Editors call: It seems there is no conflict because as @jwakely mentioned the non-underscore suffixes are reserved for the standard. @ChrisGuzak yes please submit a PR. @jwakely is it true that everything in namespace `std::literals` is guaranteed not to conflict with code that observes the underscore requirement? That is, the standard didn't put anything else in that namespace that could cause a problem?

**Comment by jwakely** [comment]
There's nothing in `std::literals` except UDL operators and other inline namespaces. The UDLs are all named `operator""x` for some `x`. Those should not clash with anything in user code, because users are required to name their own UDLs `operator""_x` instead.

The inline namespaces could in theory conflict:

````
#include <chrono>

struct chrono_literals { static int i; };
int chrono_literals::i = 0;

using namespace std::literals;

int main()
{
  return chrono_literals::i;  // error: std::literals::chrono_literals or ::chrono_literals?
}
````
