### ISSUE TITLE
Override on derived class destructors

### ISSUE THREAD

**Issue by TomMettam** [isocpp/CppCoreGuidelines#1446]
`If a base class destructor is declared virtual, one should avoid declaring derived class destructors virtual or override. `

Why is this?

Using `override` on a derived class destructor provides protection against the base class destructor accidentally being made non-virtual, thus introducing subtle, hard to detect and hard to diagnose memory leaks. @

**Comment by johelegp** [comment]
See https://github.com/isocpp/CppCoreGuidelines/issues/721#issuecomment-246453707.

**Comment by TomMettam** [comment]
Okay, so based on that thread, there only real reason is that it's unusual. As far as I can tell, doing so has absolutely zero practical negative implications.. and a very useful positive impact. So my question still stands, really.

**Comment by MikeGitb** [comment]
What annoys me the most is that it is an absolutely needless exception to an otherwise straightforward rule: "Virtual functions should be marked with exactly one of virtual, override or final".

C++ guidelines already have far too many exceptions (most of the time for good reason) - we don't have to artificially complicate them further.
