### ISSUE TITLE
I.27 code snippet issue (move constructor should be default-ed in .cpp, not in .h)

### ISSUE THREAD

**Issue by sasha-gil** [isocpp/CppCoreGuidelines#1471]
A code snippet illustrating I.27 ("For stable library ABI, consider the Pimpl idiom") correctly places "= default;" definitions of widget's destructor and move assignment operator to .cpp part of the snippet, but does not do so for widget's move constructor (it is defined with "= default;" right in the .h part of the snippet). This is incorrect: there will be compile errors as soon as a client piece of code starts using widget's move constructor, the situation is similar for all 3 special member functions (all 3 have to be defined via "= default;" in .cpp part of the snippet).

**Comment by jwakely** [comment]
Yes, unfortunately the `unique_ptr` destructor is instantiated in the move constructor, even though there's no possible code path that would use it.

**Comment by oleksandrkozlov** [comment]
@sasha-gil I guess the example was copy-pasted from [Pimpl - cppreference.com](https://en.cppreference.com/w/cpp/language/pimpl). In that example, a `widget` is created like below
```cpp
widget w(7);
````
But in case if we want to move, or for instance, use [AAA](https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/), a move operator should be implemented in `*.cpp` as well.

```cpp
auto w = widget{7};
````

Otherwise, a compiled error happens: `error: invalid application of ‘sizeof’ to incomplete type ‘widget::impl’`

I like that `Meyers15` has a separate rule for this: 

> Item 22. When using the Pimpl Idiom, define special member functions in the implementation file.

**Comment by cubbimew** [comment]
cppreference updated

**Comment by hsutter** [comment]
Editors call: Thanks Sergey, please fix this one too. :)
