### ISSUE TITLE
Default arguments for constructors

### ISSUE THREAD

**Issue by FraserRoss** [isocpp/CppCoreGuidelines#1475]
I would like to suggest spliting C48 into two guidelines.  A new guideline can be extracted from it called something like "Avoid default arguments with constructors".  This guideline would be found easier because it will be in the contents list.

**Comment by oleksandrkozlov** [comment]
> Avoid default arguments with constructors @FraserRoss 

It implies overloading that contradict with [F.51: Where there is a choice, prefer default arguments over overloading](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f51-where-there-is-a-choice-prefer-default-arguments-over-overloading).

  Because if we have a constructor with default arguments
``` cpp
class X
{
    int i;
    int j;
    int k;

public:
    X(int ii = 1, int jj = 2, int kk = 3) : i{ii}, j{jj}, k{kk} { }
};
```

We can create instances of the class like below
``` cpp
auto x0 = X{9, 8, 7};
auto x1 = X{9, 8};
auto x2 = X{9};
auto x3 = X{};
```

But if we avoid default arguments in the constructor and want to have the same usage as above, we have to overload constructors. And unfortunately, it's impossible to use delegating constructors in this case.
``` cpp
class X
{
    int i = 1;
    int j = 2;
    int k = 3;

public:
    X() = default;
    X(int ii) : i{ii} { }
    X(int ii, int jj) : i{ii}, j{jj} { }
    X(int ii, int jj, int kk) : i{ii}, j{jj}, k{kk} { }
```

IMHO, the code with default arguments looks more straightforward.

**Comment by FraserRoss** [comment]
What C48 says at the top is mostly right but it doesn't lead to the shortest code as you have demonstrated.  You have got 3 arguments to always pass increasing the overhead.  With your second class X the default values are clear, argument passing is minimised and the choice of constructors is clear.

**Comment by hsutter** [comment]
Editors call: C.48 doesn't try to ban default arguments to constructors, it just says to consider an in-class initializer may be more appropriate (or it may not).
