### ISSUE TITLE
New guideline request: Prefer a single function which takes a safe encapsulating type to overloads

### ISSUE THREAD

**Issue by mguid65** [isocpp/CppCoreGuidelines#1492]
Prefer using a single function which takes a type which can be constructed or converted from other types to having several overloads.

Example
Avoid having these

    void foo(const char * c);
    void foo(const char * c, size_t count);
    void foo(const std::string& s);

When they could potentially be covered by this

    void foo(std::string_view sv)

**Comment by beinhaerter** [comment]
Regarding strings there already are guidelines when to use `const char*`, `string`, `czstring` or `string_view`. Do you have a good example for your new guideline with other types?

**Comment by mguid65** [comment]
There must be other examples, none that I can thing of off the top of my head. These also assume that constructors and implicit conversion operators have no side effects. 

Also some more information about the reasoning behind this:
I just made a change in my companies code base which changes multiple overloads of string types to string_view. The problem was that the functions were all required to do slightly different things just to set a member variable. This was definitely unnecessary complexity.

One type I could possibly think of is the upcoming span, but it should also warrant its own set of guidelines like strings.

Example
Avoid having these

    template<class ValueType>
    void foo(const std::vector<ValueType>& vec);
    template<class ValueType>
    void foo(const std::array<ValueType>& arr);

When they could potentially be covered by this

    template<class ValueType>
    void foo(std::span sp)

**Comment by sankurm** [comment]
The suggestion to use: 
`void foo(std::string_view sv);`
instead of:
`void foo(const char * c);`
has performance overhead if the function could work without having to calculate length.

**Comment by mguid65** [comment]
In practice if you have a `const char * c` you may need to call strlen or do a linear walk of the cstring checking for `\0` anyway which is the same behavior of string_view in that case.

Here is an example where the value is used to set an offset in an optimized dynamic sized string message:

    struct msg {
      uint16_t len;
      uint16_t data;

      inline void init() {
        std::memset( static_cast<void *>(this), 0, sizeof(msg));
        len = sizeof(msg);
      }

      inline void set_data_sv(std::string_view sv) {
        data = len;
        char* dest = reinterpret_cast<char*>(this) + len;
        memcpy(dest, sv.data(), sv.length());
        dest[sv.length()] = '\0';
        len += sv.length() + 1;
      }

      inline void set_data_char_ptr(const char* c) {
        data = len;
        auto sz = strlen(c);
        char* dest = reinterpret_cast<char*>(this) + len;
        memcpy(dest, c, sz);
        dest[sz] = '\0';
        len += sz + 1;
      }
    } __attribute__ ((packed));

Don't comment about the safety of this, it is completely unsafe and requires the user to allocate their own buffer to hold the message.

**Comment by sankurm** [comment]
> In practice if you have a `const char * c` you may need to call strlen or do a linear walk of the cstring checking for `\0` anyway which is the same behavior of string_view in that case.
> 
There is a _may_ in the above. There are cases where linear scan of the entire c-string is undesirable. 

It will be undesirable to apply the suggested guideline to realistic `std::basic_string` member functions like these: 
```
int compare(const CharT* s) const;
basic_string& operator=(const CharT* s);
```
My small point: The 1st of the 3 examples in the initial suggestion doesn't directly fit this 'Prefer' guideline. That example would fit only a 'Consider' kind of a guideline.

**Comment by mguid65** [comment]
In that case I would amend my guideline to "Consider simplifying overload sets using safe covering conversions"

**Comment by sankurm** [comment]
I can see a number of new ones needed relating to ranges. I saw Herb mention, in another issue, that many new ones relating to the newer C++20 features were coming. 
For the current point in discussion, I would prefer the following stronger guideline where the key take-away is in the guideline title. 

//New suggestion for [Functions](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-functions) section
**F.xx1: Use `View` or `Range` concepts to pass half-open sequences instead of passing containers or a pair of iterators** 
The above case of passing `std::span` in place of `std::vector` and `std::array` looks equivalent to a specialization for [`ContiguousRange`](https://en.cppreference.com/w/cpp/ranges/ContiguousRange) when the function takes a `Range`. 

//Already present and good advice
**[F.24](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-range): Use a span<T> or a span_p<T> to designate a half-open sequence**
**[SL.str.2](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rstr-view): Use `std::string_view` or `gsl::string_span` to refer to character sequences**

//Change in below `gsl::string_span` to `std::span`
**[SL.str.11](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rstr-span): Use `std::span` rather than `std::string_view` when you need to mutate a string**

F.xx1 could well be in the [T.concepts](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#tconcepts-concept-rules) section, or better still, in a new T.ranges section.

**Comment by mguid65** [comment]
Referring to suggestion for [Functions](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-functions) I would suggest a slight alternative
**F.xx1: Use Range concepts to pass whole containers to algorithms instead of passing a pair of iterators**

**Comment by sankurm** [comment]
@mguid65 A small note: Not every use of container is strictly in the sense of a sequence. Passing container is not avoidable for examples like this: 
```
template<typename T>
std::vector<T> save_storage(std::vector<T>&& v) {
    v.shrink_to_fit();
    return v;
}
```
Thus, guideline F.xx1 is applicable only to the use of a container in the sense of a sequence.

**Comment by mguid65** [comment]
@sankurm I agree with that, my point was more about using new range algorithms instead of the iterator overloads if you intend to operate on the entire container like:

    ...
    std::vector<int> vec{ 3,2,1 };
    std::sort(vec.begin(), vec.end());
    ...

if you use the new range algorithms, you could make the code more understandable and concise like:

    ...
    std::vector<int> vec{ 3,2,1 };
    std::::experimental::ranges::sort(vec);
    ...

**Comment by jwakely** [comment]
> In practice if you have a `const char * c` you may need to call strlen or do a linear walk of the cstring checking for `\0` anyway which is the same behavior of string_view in that case.

Sometimes, but definitely not always.

Replacing those overloads with a single one taking `string_view` is probably inappropriate if the functions do something that requires a null-terminated string, e.g. because it's passed to another API you don't control, such as `fopen`. Given the original overload set, `void foo(const char * c)` can call `fopen(c, mode)`, and `void foo(const std::string& s)` can call `fopen(s.c_str(), mode)`, but `void foo(const char * c, size_t count)` might need to do `foo(std::string(c, count))` which has to copy the data and potentially allocates memory. For `foo(string_view)` you don't have a null-terminated string so always need to copy into a new (potentially allocated) buffer. This problem doesn't always apply, but certainly needs to be kept in mind if writing a guideline on the subject.

**Comment by hsutter** [comment]
Editors' call: The cleanest rule is to 'use an appropriate abstraction' but that's very general. The argument also applies to `span`. The rule needs to be written carefully because `string_view` isn't for null-terminated strings.
