### ISSUE TITLE
Adding CTAD to span

### ISSUE THREAD

**Issue by JordanMaples** [isocpp/CppCoreGuidelines#1497]
Requested in GSL PR microsoft/GSL#729

**Comment by jwakely** [comment]
What (if anything) needs to change in the guidelines though?

**Comment by MikeGitb** [comment]
Well, initially the Idea was for the guidelines to specify or at least document the GSL, as the gsl was supposed to be a library that could be implemented by different people just as the standard library.

I don't think anyone ever took this seriously,  but at least Herb added some documentation to this repo, that could be updated.

**Comment by jwakely** [comment]
But `span` is in the working draft for the C++ standard now. That already specifies the deduction guides for `span`. Adding that to the guidelines as well seems redundant.

**Comment by hsutter** [comment]
Editors' call: Normally when a GSL type is standardized we drop the GSL type. In this case, we're not withdrawing GSL span because some users rely on checking, which std::span doesn't do. But we should make gsl::span as close as possible to std::span, including adding CTAD and changing signed to unsigned for index_type.

See also #1504 and #1511.
