### ISSUE TITLE
Consider updating gsl::span to std::span

### ISSUE THREAD

**Issue by JordanMaples** [isocpp/CppCoreGuidelines#1504]
Microsoft::GSL has an implementation of span that differs from the standard. The differences are primarily about checking. We should consider updating the documentation in the CoreGuidelines to use std::span.

Today the Guidelines only mention C++17 features, this would imply adding documentation concerning C++20 features.

**Comment by hsutter** [comment]
Editors' call: Normally when a GSL type is standardized we drop the GSL type. In this case, we're not withdrawing GSL span because some users rely on checking, which std::span doesn't do. But we should make gsl::span as close as possible to std::span, including adding CTAD and considering changing signed to unsigned for index_type.

See also #1504 and #1511.
