### ISSUE TITLE
Lifetimes I and II - v0.9.1
More than two ' means the same as two '.

### ISSUE THREAD

**Issue by LiZhenhuan1019** [isocpp/CppCoreGuidelines#159]
There may be some problems.Think about this.

	using v_t=vector<int>;
	using vv_t=vector<v_t>;
	using vvv_t=vector<vv_t>;
	vvv_t vvv{{{5}}};
	vvv_t *pvvv=&vvv;//pset(pvvv) = {vvv}
	vv_t *pvv=&vvv[0];//pset(pvv) = {vvv'}
	v_t *pv=&vvv[0][0];//pset(pv) = {vvv''}
	int *p=&vvv[0][0][0];//pset(p) = {vvv'''},that is,{vvv''}
	pv->clear();//KILL(vvv'''),that is,KILL(vvv'')
	                   //pset(pv) = {invalid}
	                   //pset(p) = {invalid}

So Why should more than two ' mean the same as two '?The information will be lost.

**Comment by neilmacintosh** [comment]
The analysis needs to bound the depth of dereferences it is prepared to track so that it can deterministically terminate in cases where it is not possible to statically determine how deep a chain of dereferences may go (for example, inside a loop).

Losing precision by limiting the number of dereferences to two does mean that sometimes we might report more errors than are ideal (as in your example). However, we can always revise that limit to a number we think is optimal based on experience running the analysis over real world code and examining time/space costs vs. false positives. For now, two seems like a reasonable place to start.

**Comment by LiZhenhuan1019** [comment]
I got it.Thank you very much!
