### ISSUE TITLE
Clarification wanted: I.2 "Avoid non-const global variables" rule - is function-local static variable global?

### ISSUE THREAD

**Issue by LebedevRI** [isocpp/CppCoreGuidelines#1599]
Hello.
In https://reviews.llvm.org/D70265 the clang-tidy check to diagnose that guideline was implemented.

But now, there's confusion as to what it should actually be diagnosing.
In particular, i argue that diagnosing the following would be a false-positive:
https://godbolt.org/z/2QMemL
```
void bar(int*);

void foo() {
  static int a;
  bar(&a);
}
```

```
<source>:4:14: warning: variable 'a' is non-const and globally accessible, consider making it const [cppcoreguidelines-avoid-non-const-global-variables]
  static int a;
             ^
```

Some clarification is welcomed.

**Comment by shaneasd** [comment]
It's sort of funny from an information hiding point of view. On the one hand it's as limited as you can get in that it can only be accessed by one function (something private can't boast). On the other hand from anywhere in the code you can call that function and potentially alter the behavior of all other calls anywhere else in the code which I would call a global variable.

It seems clear that ```int& foo() { static int a = 0; return a; }``` is for all practical purposes a global variable and so I would say that in at least some cases a function-local static variable is still global in that all the bad things in I.2 apply to it. In fact, I vaguely recall Titus Winters saying that this is actually the recommended approach for creating singletons at google (because of more guarantees around the initialization of function local statics compared to vanilla globals though I don't recall the specifics)

Whether your example is a false positive might depend on exactly what bar does. However I would argue that it's not a false positive. Presumably since bar takes an ```int*``` not a ```const int*``` then it is in some may modifying its input. Presumably since foo doesn't use ```a``` for anything except calling bar then the behavior of bar is also dependent on ```a```. If both of these facts are true then bar is both reading from and writing to ```a``` in effect. The two problems identified in I.2 are
- hidden dependencies
- data races
I think it's debatable whether there are hidden dependencies here. With documentation (or a more information function name) on foo it could be made quite explicit that successive calls to foo will affect subsequent calls.
However I think there's quite clearly a data race here. two threads calling foo could have disastrous consequences without thread safety being built into bar (which doesn't know it's being called from foo).

I think if you have a global variable and you can replace it with a function local static then that's probably an improvement but it's still effectively a global as far as I.2 is concerned.

**Comment by hsutter** [comment]
Editors' call: Function local statics are covered under I.3. A function local static is static and its lifetime is global (not stack) but its name is not globally visible unless we escape the name via pointer, such as a Meyers Singleton, and then I.3 applies.
