### ISSUE TITLE
Should there be a rule to prefer `explicit` with `operator bool()`?

### ISSUE THREAD

**Issue by aidan-gallagher** [isocpp/CppCoreGuidelines#1673]
`operator bool() const` can allow nonsense operations.

C++11 introduced
`explicit operator bool() const`
This can be contextually converted to a bool in `if`, `for` and `while` statements. It will require explicit conversion in other scenarios .

Links to a better explanation
https://stackoverflow.com/questions/4600295/what-is-the-meaning-of-operator-bool-const
https://www.artima.com/cppsource/safebool.html

**Comment by cubbimew** [comment]
isn't it already covered by [C.164: Avoid implicit conversion operators](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ro-conversion ) ?

**Comment by johelegp** [comment]
There seems to be no rule that generalize [C.160](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c160-define-operators-primarily-to-mimic-conventional-usage) and [C.100](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c100-follow-the-stl-when-defining-a-container),  something along the lines of "following conventions". So that if you're defining an `operator bool()` for the same purposes as existing facilities, you do as they do and make it `explicit`.

**Comment by aidan-gallagher** [comment]
> isn't it already covered by [C.164: Avoid implicit conversion operators](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ro-conversion) ?

I think it does. 
It's my fault for searching for `operator bool` instead of `explicit operator` when looking for the appropiate rule.

I'm happy to close this.

**Comment by hsutter** [comment]
Editors call: Thanks!
