### ISSUE TITLE
R.3 incomplete reasoning about make_gadget example

### ISSUE THREAD

**Issue by rafzi** [isocpp/CppCoreGuidelines#169]
>In addition to suffering from then problem from leak, this adds a spurious allocation and deallocation operation, and is needlessly verbose. If Gadget is cheap to move out of a function (i.e., is small or has an efficient move operation), just return it "by value:'

It should be noted that you usually can return by value even if the class is not cheap to move, because every major compiler does NRVO. So for this example I would suggest to unconditionally suggest returning by value (Except when you really need pointer semantics, but a Note already mentiones that below).

Returning by value yields really simple code and should not be discouraged like that.

**Comment by AndrewPardoe** [comment]
Discussed 11/30/2015.

**Comment by hsutter** [comment]
I'm not so sure we should be citing NRVO. Even with NRVO enabled, it can't elide all copying cost, whereas passing a reference to a caller-allocated BigPOD does do that (and should be thought of as "in-out" because there is something coming "in", namely the storage).

Added some text to R.3 to cross-reference F.20 which already notes the caller-allocated-out pattern as an "in-out" alternative.
