### ISSUE TITLE
gsl::narrow for non totally ordered types

### ISSUE THREAD

**Issue by JohelEGP** [isocpp/CppCoreGuidelines#1726]
MS's GSL implementation of `gsl::narrow` is more restrictive than the C++ Core Guidelines specify. I'd like it to work for my use case.

> The C++ Core Guidelines simply [specify `gsl::narrow`](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#gslutil-utilities) as `narrow // narrow<T>(x) is static_cast<T>(x) if static_cast<T>(x) == x or it throws narrowing_error`. The implementation uses relational operators, so I can't do `gsl::narrow<point<unsigned>>(point<int>{})` for my `point` type.
> -- https://github.com/microsoft/GSL/issues/900

But they'd like a nod from here before proceeding (https://github.com/microsoft/GSL/issues/900#issuecomment-725716386).

**Comment by shaneasd** [comment]
Does it make sense for gsl::narrow to try and anticipate custom types and facilitate or does it make more sense for you to define your own narrow method for your own type (whose implementation presumably depends on gsl::narrow). I don't know the answer but we define a narrow method for our units types which is modeled after gsl narrow and that seemed very reasonable at the time. ADL makes the two methods compatible in the uncommon circumstances where you care.

I wonder how you would define narrow for types that didn't have relational operators keeping in mind that ```point<unsigned>(0xffffff)``` is presumably equal to ```point<signed>(0xffffffff)``` due to overflow/promotion in the comparison. Any suggestions?

My opinion is that your point type is necessarily excluded because your point type does not and cannot define ```operator<``` in a predictable way but ```operator<``` is required in order for narrow to work correctly of mixed sign types but that the appropriate solution to this problem is for you to define a narrow method for your type which performs a component-wise gsl::narrow. I also think that, therefore, the core guidelines spec (such as it is) for gsl::narrow could be better written either to remain very prescriptive of how narrow works but updated to match the actual implementation or instead be a description of what narrow is attempting to achieve leaving the implementation to the authors. Normally I would prefer the latter but because of how low level it is and the implications of which operators from its template arguments it uses the former might make more sense in this case.

**Comment by johelegp** [comment]
Thank you. I agree with you.

Here's MS's `gsl::narrow` [as of this comment](https://github.com/microsoft/GSL/blob/a47352cb2a05cc2684877d8a55077d092f20574b/include/gsl/narrow) and [on `master`](https://github.com/microsoft/GSL/blob/master/include/gsl/narrow).
```C++
template <class T, class U>
    constexpr T narrow(U u) noexcept(false)
{
    constexpr const bool is_different_signedness =
        (std::is_signed<T>::value != std::is_signed<U>::value);

    const T t = narrow_cast<T>(u);

    if (static_cast<U>(t) != u || (is_different_signedness && ((t < T{}) != (u < U{}))))
    {
        throw narrowing_error{};
    }

    return t;
}
```
The spec only uses `==`. This implementation has additional logic added in https://github.com/microsoft/GSL/pull/262/, which isn't reflected in the spec. But ES.46 calls out
> `narrow` ("narrow if") that throws an exception if a narrowing would throw away information

which would make this quote and MS's implementation more useful and in line with what one would expect of `gsl::narrow`.

That said, implementing `narrow` for my own type got me thinking that I'd be doing the `using std::narrow; narrow(whatever);` dance, as with `std::swap`, in generic contexts. Perhaps `gsl::narrow` should be a CPO.

**Comment by shaneasd** [comment]
I don't love the "throw away information" definition either because when you convert from char to int you throw away information (the information being that the value will definitely fit in a char without having to be checked) but I wouldn't consider that a narrowing conversion. It's just not the kind of information that's being referred to here. I might have a go at a pull request making the various sources consistent and see what traction it gets.

Remainder of my post is off topic from the key issue.

Regarding your last comment, I'd be surprised if your generic contexts were so frequent that the "dance" you mentioned became too onerous but it's hard to say. One thing to keep in mind is that this solution will work for all types that have a narrow overload not just yours and the ones gsl::narrow works for. This may or may not be relevant to you. If by CPO you mean complete partial ordering then wikipedia isn't helping my understanding but from context I speculate that you mean simply defining operator< in  a consistent way (e.g. x<x || x==x && y<y sort of thing). If that's the case I suggest either disallowing floating point template arguments or carefully considering how the x==x condition would affect your results in the presence of floating point error.

**Comment by johelegp** [comment]
The CPO is to have `gsl::narrow` resolve to your type's `narrow` via ADL, similar to how you can use `std::ranges::swap(x)` rather than `using std::swap; swap(x)`.

**Comment by shaneasd** [comment]
oh I see. Perhaps.

**Comment by hsutter** [comment]
Editors call: We agree and are updating the specification of `narrow` to cover signedness promotions.

**Comment by JohelEGP** [comment]
Unfortunately, it's not clear whether you mean to allow non-integer like types or not.
