### ISSUE TITLE
Unclear whether rule F.5 is about the inline keyword or the inline concept

### ISSUE THREAD

**Issue by pauljansen42** [isocpp/CppCoreGuidelines#1731]
Rule F.5 is about "If a function is very small and time-critical, declare it inline". The question is whether the rule applies to the keyword inline or the concept of inlining (i.e. putting definitions in header files). Since the font in the synopsis is different it suggests that it is about the keyword. The same holds for the first paragraph. But later on function templates are considered exceptions, whereas this is certainly about the inline concept and not the inline keyword. I have asked several people about this and nobody could tell me which one was meant. Please make this clear and if needed split up the rule one for the use of the inline keyword and one for the inline concept.

**Comment by shaneasd** [comment]
I think the point about the function templates is that most member function templates will, by necessity, have their definition in a header file. As such, since "Member functions defined in-class are inline by default." that means these member function templates will be inherently inline whether or not they conform with the rule. I think the exception is basically saying don't worry about these function templates because there's nothing you can do to prevent them breaking the rule.

I think the key is that it says to "**declare** it inline". To me this means using the inline keyword.

Not saying this couldn't be clearer.

**Comment by pauljansen42** [comment]
OK, thanks. Then there are 2 small questions left:
1. Could you please change the font of the word "inline" at the end of the last exception to make clear it is about the keyword?
2. Concerning the enforcement. So it is sufficient to check for the "inline" keyword and not for functions that are defined in-class that are more than three statements (implicitly inline)?

**Comment by shaneasd** [comment]
1.
Do you mean this exception?
> Function templates (including member functions of class templates A<T>::function() and member function templates A::function<T>()) are normally defined in headers and therefore inline.

That's not about the keyword? You don't have to use the keyword in that context because it's implicit. That particular occurrence of the word is about the inline concept not the keyword. As such I think the font choice is correct.

2.
Actually I suspect the intended reading of that enforcement is to flag all functions over three lines that are either marked inline or could be declared out of line (such as class member functions). In other words  basically anything inline that isn't one of the above exceptions.

**Comment by pauljansen42** [comment]
Thanks for your answers! In both answers you indicate that it is not only about the inline keyword but also about the inline concept. Why is the synopsis and the enforcement of the rule then using only the inline keyword? Do you understand the confusion for me and also for others? So my suggestion remains: either split up the rule one for the inline keyword and one for the inline concept or revise it to make things clear.

**Comment by pauljansen42** [comment]
Any updates on this?

**Comment by hsutter** [comment]
Editors call: We agree and will update this. Thank you!
