### ISSUE TITLE
Rule F.6 different phrasing between index and actual

### ISSUE THREAD

**Issue by Skewjo** [isocpp/CppCoreGuidelines#1750]
Trying to wrap my head around the use of ```noexcept``` and I ran into this. Which of these is generally considered to be more correct? 

Index:
![noexcept_might_CG](https://user-images.githubusercontent.com/4118039/108572174-54bade80-72d7-11eb-862b-9637889636db.PNG)

Actual: 
![noexcept_must_CG](https://user-images.githubusercontent.com/4118039/108572181-5d131980-72d7-11eb-8169-d5c092e950c8.PNG)

**Comment by JuliusBrueggemann** [comment]
Unless I'm misinterpreting it, the phrasing in the index is wrong. Every function that **might** exit via a `return` statement is a function that **might** not throw, which is basically all functions. But only few functions **must** exit via a `return` statement (instead of an exceptions being thrown).

For a simple example:
```c++
int foo(int i)
{
    if(i > 0)
        return i;
    else
        throw std::invalid_argument("");
}
```
This function **might** not throw (it does not throw if `i > 0`). But it **might** do throw (if `i <= 0`), so declaring it `noexcept` would be wrong.

**Comment by jwakely** [comment]
Yes, the index is obviously wrong.
