### ISSUE TITLE
Restrict rule C.133 to non-const protected data

### ISSUE THREAD

**Issue by pauljansen42** [isocpp/CppCoreGuidelines#1755]
Rule C.133 states "Avoid protected data". The motivation is about possible changes made by children of the class thus possibly making it hard to guarantee class invariants. But this only holds for the non-const parts. So what is wrong with const protected data? So my recommendation is to either specify the motivation why const protected data should be avoided as well in the rule or restrict the rule to non-const protected data.

**Comment by pauljansen42** [comment]
Is there any news about this?

**Comment by scraimer** [comment]
Putting `protected` constants inside a class indicates that there's there's some functions in the class that use those constants to perform operations. If only child-classes have access to those constants, then the same argument in C.133 still holds: the child classes have to use those constants in the same way that the parent class did.

But wouldn't it be better for those constants to be `private` to the class, and make use of them in a member function of that class? You can keep that function `protected`, and call it from child classes.

If you want to re-implement or extend that work in the child class or a containing class, I suggest it would be better to make those constants `public`, to allow also encapsulation, and explicitly show that the parent class cannot control the re-use of those constants. Which it cannot.

**Comment by hsutter** [comment]
Editors call: We considered this and we think the existing rule is what we want to say. Const data members are problematic in general, regardless of accessibility; for example, they break assignment. And protected and public data members should be treated consistently because the problems with both are the same, that an unbounded amount of code has access to them, and so if we did make such a change we should make it also for public const data; but we don't currently have motivating examples for why const public or protected data would be useful.
