### ISSUE TITLE
Add clarification to Con.1

### ISSUE THREAD

**Issue by stayprivate** [isocpp/CppCoreGuidelines#1785]
Con.1: By default, make objects immutable
...
Function arguments are rarely mutated, but also rarely declared const. To avoid confusion and lots of false positives, don't enforce this rule for function arguments.

void f(const char* const p); // pedantic
void g(const int i);        // pedantic
...
------------------------------------

These examples are prototypes/decl, not the definition.  Internaly some are interpreting the lack of example as saying const should not be used for argument passed by copie/value in definition as well. Other are saying "by default make objets immutable" as applying to argument passed by copie/value. 

I've never seen code using const for argument passed by copy/value, in definition.

--------------------------------------

What is recommended?  I personnaly like const in definition, it tells the reader/maintainer,  the variable will not be modified.

**Comment by MikeGitb** [comment]
I also don't see, why function arguments should be treated any different than regular variable definitions in that respect. 

Realistically however, I think a tool should have separate flags to enable/disable warnings about non-const local variables and non-const function parameters. Such a check will be incredibly noisy anyway when applied to an existing code base and it would be beneficial to clean it up one kind at a time.

**Comment by jwakely** [comment]
> Such a check will be incredibly noisy anyway

Which is why they should be treated differently. You answered your own question didn't you? Using const for function parameters is less common, and confuses some people (many people don't realise it has no meaning on a non-defining declaration, only on the definition, and having it mismatched between declaration and definition also confuses). That's why the guideline says not to enforce it for function parameters. The trade off between additional const-ness and potential confusion needs to be considered for each codebase, not enforced uniformly.

**Comment by MikeGitb** [comment]
>Which is why they should be treated differently. You answered your own question didn't you?

Sorry, I wasn't clear: I meant the guideline should be the same for both, but as I said: There should be separate flags for the two cases. 


The "such a check" was meant to refer to any check that warns on non-const variables. Regardless of whether they are parameters or function locals. I.e. even if you "only" warn on function local variables you'll get an abundance of warnings.

**Comment by hsutter** [comment]
Editors call: Ok, we made one of them a definition. Thanks!
