### ISSUE TITLE
.clang-format?

### ISSUE THREAD

**Issue by BenFrantzDale** [isocpp/CppCoreGuidelines#1790]
This may be out of scope for this project, but it would be great if these guidelines included a `.clang-format` file to as a "nudge" toward a consensus formatting style and to help reduce bikeshedding. Presumably `BreakBeforeBraces: Stroustrup` would be one of the rules? Feel free to close if this is out of scope.

**Comment by hsutter** [comment]
Editors' call: There is an "NL" section for naming and layout suggestions, but we deliberately hold back from mandating any particular style.

**Comment by tvercaut** [comment]
I know this issue has been closed as out-of-scope (consistently with https://github.com/isocpp/CppCoreGuidelines#background-and-scope) but I wasn't sure where else to ask a follow-up question.

I am wondering if there is any known compatibility issue between CppCoreGuidelines and any predefined style availlable in clang-format (LLVM, GNU, Google, Chromium, Microsoft, Mozilla, WebKit):
https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options

Alternatively, if at least one of the predefined clang-format styles is known to be compatible with CppCoreGuidelines that would be enough for me.

**Comment by MikeGitb** [comment]
The Core guidelinrs don't prescribe any style, so I don't see how there could be any incompatibility.

**Comment by tvercaut** [comment]
Thanks. I saw a few rule that could be considered style (e.g. [NL.20](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#nl20-dont-place-two-statements-on-the-same-line), [SF.4](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf4-include-h-files-before-other-declarations-in-a-file)) which is why I was asking before choosing a style but indeed these are unlikely to clash with any style guidelines.

Also, with apologies as this goes even more out of scope, what I was a bit less clear on was whether clang-format with say the google style would enforce rules that are a bit less stylistic in nature from the [Google Style Guide](https://google.github.io/styleguide/cppguide.html), e.g. anything beyond the "formatting" parts, which may clash with the CppCoreGuidelines.

My question also stemmed from reading this note in the core guidelines:
> http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#rfrules-coding-rules
> [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html). Geared toward C++17 and (also) older code bases. Google experts are now actively collaborating here on helping to improve these Guidelines, and hopefully to merge efforts so these can be a modern common set they could also recommend.
