### ISSUE TITLE
Add an exception to ES.46 for contextual conversion to bool

### ISSUE THREAD

**Issue by hsutter** [isocpp/CppCoreGuidelines#1797]
Editors call: In Es.46, we should consider not flagging a conversion to bool used only to perform a boolean test (e.g., `if (myint)`). We do want to continue flagging attempts to convert to assign a boolean value (e.g., 'mybool = myint;` should require a `narrow`).

**Comment by shaneasd** [comment]
I've never understood the reasoning behind treating non-boolean types as boolean in conditions. I always assumed it was a holdover from before there was a dedicated boolean type but there seems to be a general consensus that it's still fine. I'll be interested to see what explanation is given for what separates those two cases. Would also be interesting to know where precisely the line is drawn (e.g. is ```if(myint && yourInt)``` acceptable.

Note that ES.87 strongly disagrees with me for pointers but appears to contradict the editors' more recent decision here regarding integers.

**Comment by MikeGitb** [comment]
I think for types that have an explicit null/invalid state (pointers, optional, result) it is a matter of convenience and readability `if( p && p->c == 5){ ...}; ` vs `if( p != nullptr && p->c == 5) {...}`. 

For integers I would certainly assume that it has its roots in c-tyle APIs (in particular posix) where a value other than zero means that an error has occured (which unfortunately is the exact opposite from APIs that return a valid pointer/optional on success). However, as such C-APIs are still a common thing to interact with, I don't think it really is a "holdover". Not arguing in favor of that latter technique,, explaining, where I believe it comes from.

**Comment by jwakely** [comment]
It allows things like:

```
if (ostream::sentry s{*this})
  ...
```

instead of:


```
ostream::sentry s{*this};
if (s)
  ...
```

Admittedly, since C++17 you can do:


```
if (ostream::sentry s{*this}; s)
  ...
```

But I don't think that's necessarily better in all cases.

**Comment by shaneasd** [comment]
Thanks. I think those are good points. However they seem to revolve around a theme of brevity. Personally I find ```if (myOptional.has_value())``` clearer than ```if(myOptional)``` and, within reason, I would choose clarity over brevity for a goal of readability. I find the same for ```if(myInt != 0)``` or ```if (myPtr != nullptr)```. That wont always be the case perhaps and for some perhaps the opposite is true (both in terms of the tradeoff between brevity and clarity and whether or not my preferred option is actually clearer) but effectively ES.87 and the proposed change to E.46 is telling me that my way is wrong which implies it's not simply a question of preference or that I'm significantly in the minority and so should change my approach with a view to more unity in approach.

With all of this in mind it seems arbitrary to me to draw the line at integers. Within the language their conversion to bool is as well defined as these other types and everything else comes down to convention and the reader. I'm not asserting that it is arbitrary. I'm just suggesting that 
- the proposed modification include an explanation for what makes integers special
- ES.87 be modified accordingly with any modification made to ES.46

**Comment by neithernut** [comment]
It's not only a mere point of brevity imo, but also a feature you can use for improving safety (in conjunction with an "inline" declaration). Consider for example with a function `auto get_foo() -> std::option<foo>`:

```c++
if (auto foo = get_foo()) {
   foo->bar();
}
foo->bar(); // Compiler error
```

vs.

```c++
auto foo = get_foo();
if (foo.has_value()) {
    foo->bar();
}
foo->bar(); // Runtime error, likely a segfault
```

Of course, you could achieve the same with monadic interfaces such as a `map(std::function<O(T)>) -> O`, but many types (including STL types) of interest don't provide such interfaces. And it's not really an option for (primitive) pointer types, at least not on C++20 and likely not in the future.

**Comment by jwakely** [comment]
> However they seem to revolve around a theme of brevity

No. It's about limiting the scope of the variable to the region where it is valid and needs to be declared. That's a semantic change, not just a shorter way to say the same thing.

**Comment by shaneasd** [comment]
Sure but as @jwakely points out above you can write ```if (auto foo = get_foo(); foo.has_value())``` in c++17 which gives the same scope for foo as ```if (auto foo = get_foo())```. Why would you choose the second option over the first? Presumably because you believe its brevity makes it more readable?

**Comment by neithernut** [comment]
Yes, you can since C++17. I think I misinterpreted [your comment](https://github.com/isocpp/CppCoreGuidelines/issues/1797#issuecomment-868960399). To me it read like you'd prefer an initialization before the `if`, and that'd definitely make more of a difference than the amount of code you have to read/write.

For me, personally, it's not that much a matter of brevity but more a habit: the major part of my experience stems from a time before C++17, which was released "just" four years ago. The same will be the case for any "senior" C++ developer. That being said, the guidelines aren't targeted at _experienced_ developers exclusively.

If we follow your argument, I'd argue that the goal should be to make code expressive (as stated several times (?) in the guidelines). Regarding this, you wrote:
> I would choose clarity over brevity for a goal of readability.

I believe most will agree with you here. However, something being more explicit doesn't necessarily make it more expressive. Otherwise we probably wouldn't use `auto` that much. With a type for which the semantics aren't obvious, I'd definitely see myself favor query methods over conversion to `bool`. However especially for types like `std::optional` and `std::shared_ptr` I really don't see how even developer hatchlings could misunderstand what `if (auto foo = get_foo())` does. For `std::optional`, the extra call to `has_value()` just adds more code I have to read, contributing to a "wall of text" look. For `std::shared_ptr`, you don't even have a dedicated query function (that I'm aware of) and I'd argue that `foo.use_count() > 0` is even less intuitive than the conversion.

**Comment by shaneasd** [comment]
I believe for shared_ptr the equivalent check would be ```!= nullptr```.

You're absolutely right that brevity can improve readability and perhaps you're right about the tradeoff in this circumstance. Effectively bool, pointer, smart pointer, optional, and int all have a sort of zero value corresponding to a ```{}``` initialization and which they will convert to ```false``` iff they are equal to. The question is where you should draw the line in terms of when to make the conversion explicit.

The guidelines as written have (for ES.46 and ES.87)
Explicit: int
Implicit: bool, pointers, optional (though only implicitly)

The proposed change would be
Explicit:
Implicit: bool, pointers, optional, int (nice in its consistency to be fair)

My preference (which may seem arbitrary given bool) is
Explicit: pointers, optional, int
Implicit: bool

Really everything else is just providing context for my opinion on int which is what this issue is about. The current guidelines (ES.87) make what I consider to be a compelling argument for why int->bool conversions should be explicit (included at the end for convenience). My request is that if ES.46 is modified in the proposed way that an equally compelling justification be given countering this point and that ES.87 be updated accordingly.

![image](https://user-images.githubusercontent.com/23055764/123534220-213d0480-d74e-11eb-967e-c82c377a05ee.png)

**Comment by bgloyer** [comment]
I took a whack at this one in #1824.

In the example I used a pointer in the condition instead of an int because that seems more typical and maybe has more consensus.

**Comment by jwakely** [comment]
>Why would you choose the second option over the first?  Presumably because you believe its brevity makes it more readable?

Yes, more explicit/verbose does not necessarily mean more readable. If the shorter form is idiomatic and well understood (as it should be, because it's been valid since day one of C++) then the verbosity just adds noise.

**Comment by jwakely** [comment]
@neithernut 

> For std::shared_ptr, you don't even have a dedicated query function (that I'm aware of) 

The `get()` member returns a pointer, which can be used in a Boolean context, or explicit comparison to `nullptr` does the same thing as conversion to bool.


>and I'd argue that `foo.use_count() > 0` is even less intuitive than the conversion.

It would be wrong. It's possible to have a `shared_ptr` that owns a null pointer but has a non-zero use count. So you can't use `use_count() > 0` to test whether it's safe to dereference.

**Comment by MikeGitb** [comment]
> Effectively bool, pointer, smart pointer, optional, and int all have a sort of zero value corresponding to a {} initialization and which they will convert to false iff they are equal to. The question is where you should draw the line in terms of when to make the conversion explicit.

There is an important difference between pointer/optional types and ints, namely the semantic information tied to it. With optional and pointer types, it is unambiguously clear that if they convert to `false`, they can't be dereferenced (and usually it also means the function that created them failed). So false corresponds to some fail state and true means the processing on the happy path can continue.

With ints, the semantic meaning of 0 is not always the same. If they e.g. represent the number of bytes received, a value of 0 / false is a c aile state (you can't continue with the processing) whereas vwith error code style usage (or the mentioned posix APIs) a value of 0 often (but not always) means OK.

So I'd argue, that there is no improvement in clarity from 

    if( p ) { // use p (happy path) }

to 

    if( p != nullptr ) { // use p }

There is a significant improvement  between

    if( !i  ) { // do something (error handling? happy path?) }

and 

     if ( i == RESULT_OK ) { // do something (happy path)  }

**Comment by neithernut** [comment]
> > For std::shared_ptr, you don't even have a dedicated query function (that I'm aware of)
> 
> The `get()` member returns a pointer, which can be used in a Boolean context, or explicit comparison to `nullptr` does the same thing as conversion to bool.

Yes, comparison to `nullptr` should indeed be equivalent to a conversion to `bool`. I overlooked that possibility. I actually excluded `std::shared_ptr::get` on purpose since I didn't find anything mandating that it returned `0` or a value equivalent to `nullptr` after a _quick_ search, though I doubt that any sane STL implementation would have `std::shared_ptr::get` return a "valid-looking" pointer for an empty `shared_ptr`.

> > and I'd argue that `foo.use_count() > 0` is even less intuitive than the conversion.
> 
> It would be wrong. It's possible to have a `shared_ptr` that owns a null pointer but has a non-zero use count. So you can't use `use_count() > 0` to test whether it's safe to dereference.

Huh. I didn't realize it was possible to construct a non-empty `shared_ptr` from a `nullptr`. I should probably have paid more attention.

**Comment by jwakely** [comment]
>  I didn't find anything mandating that it returned `0` or a value equivalent to `nullptr` after a _quick_ search, though I doubt that any sane STL implementation would have `std::shared_ptr::get` return a "valid-looking" pointer for an empty `shared_ptr`.



http://eel.is/c++draft/util.smartptr.shared.const#2

> Huh. I didn't realize it was possible to construct a non-empty `shared_ptr` from a `nullptr`. I should probably have paid more attention.

http://eel.is/c++draft/util.smartptr.shared.const#7

**Comment by bgloyer** [comment]
> 
> Really everything else is just providing context for my opinion on int which is what this issue is about. The current guidelines (ES.87) make what I consider to be a compelling argument for why int->bool conversions should be explicit (included at the end for convenience). My request is that if ES.46 is modified in the proposed way that an equally compelling justification be given countering this point and that ES.87 be updated accordingly.
> 
> ![image](https://user-images.githubusercontent.com/23055764/123534220-213d0480-d74e-11eb-967e-c82c377a05ee.png)

The integer case is interesting because it depends on what kind of integer it is.  For me, something ````if (numItems)```` is fine and should be allowed (but certainly not required) while something like ````if (statusCode)```` would be better as ````if (statusCode == Something::OK)````.  Not sure how to explain that in a rule - maybe it violates using 0 as a magic number?  Looks like the Note in 87 could be clairified some.

**Comment by BenjamenMeyer** [comment]
Re: Brevity - brevity is good only in so far as things are properly communicated; however, often brevity is at odds with communication and only makes code worse. Be expressive and explicit and there will be less issues with the code, fewer bugs.

Re: `if (i)`

This has several issues, not the least of which is brevity:
1. does `i` even convert to a conditional value?
2. when refactoring/updating will `i` still be able to properly convert to a conditional value?
3. it is obvious to the maintainer that `i` really should convert to a conditional value?
4. what value is properly being tested for? invalid pointer? general conditional? a enum default that ends up at zero?

Writing code is about communication. If you're not communicating both with the compiler and with other developers via the code (actual) and comments (intent) then the code will be broken quickly, have lots of bugs, and leave people wondering about what is going on, which bug to fix and how to prioritize them.

Brevity is usually at odds with all of this; that's not to say that the code shouldn't be short where possible, but don't lose information in the process. IOW, do as little work as needed but be as communicative about it in the process. `if (i)` is extremely lossy in all the wrong ways.

**Comment by jwakely** [comment]
I don't understand all the silly fear of using a feature of the language the way it's meant to be used.

What part of `explicit operator bool() const;` in a class definition makes you think any of 1, 2 or 3 would not be true?

If it's part of the class API, then refactoring that removed it would not be refactoring, it would be an API change (or break, if unplanned).

**Comment by BenjamenMeyer** [comment]
> I don't understand all the silly fear of using a feature of the language the way it's meant to be used.
> 
> What part of `explicit operator bool() const;` in a class definition makes you think any of 1, 2 or 3 would not be true?
> 
> If it's part of the class API, then refactoring that removed it would not be refactoring, it would be an API change (or break, if unplanned).

It's not simply about using a feature of the language, but about the clarity of the code to readers.
Sometimes, and I've found this increasingly true since and including with C++11, features of the language are removing clarity and context that previously existed and actively work against developers.

So the following is not good to have around:
```
if (x) {
   ...
}
```

since `x` might get auto-converted properly or improperly - e.g if `x` returns a non-zero value is it really what the writer intended? This is corrected by having an explicit conditional statement as well as comments:
```
// purpose/intent of what is going on
if (x == myNamespace::SomeValue) {
}
```

Not only does this help across compilers, but it also helps across time, dev teams, etc. It creates maintainable code, not just working code.

**Comment by jwakely** [comment]
So don't give your type a conversion to `bool`.

For types that have it, objecting to its use is silly. "I don't know what this expression does!" It uses the `explicit operator bool() const` member, which presumably **does the right thing for testing if it's valid**. If you can't define "the right thing" for the type, maybe it shouldn't be contextually convertible to bool. If the type's designer defined it, then it should be safe to use. If you need a comment to explain it, the API is bad.

Verbosity does not always improve clarity. Apparently you feel differently, but I think you're in the minority here.

**Comment by BenjamenMeyer** [comment]
> Verbosity does not always improve clarity. Apparently you feel differently, but I think you're in the minority here.

Nor does lack of verbosity.

Code covers what is actually done.
Comments cover intent.
Both are *required* to make maintainable code.

And yeah, I know devs hate to write comments. Code isn't everything.

**Comment by beinhaerter** [comment]
> Editors call: In Es.46, we should consider not flagging a conversion to bool used only to perform a boolean test (e.g., `if (myint)`). We do want to continue flagging attempts to convert to assign a boolean value (e.g., 'mybool = myint;`should require a`narrow`).

Just for clarification: if the conversion is done on a `return`-ed expression like in 
```
bool is_empty(const std::vector<char>& v)
{
    return v.size();
}
```
then this is considered a conversion that shall be flagged!?

Maybe PR#1824 can be enhanced to clarify that.

**Comment by jwakely** [comment]
That is not a [contextual conversion to `bool`](https://en.cppreference.com/w/cpp/language/implicit_conversion#Contextual_conversions), so is not covered by the exception that is the topic of this issue.

**Comment by hsutter** [comment]
Editors call: Accepted the PR, thanks!
