### ISSUE TITLE
C.35 - incomplete enforcement, should apply to all base classes, not only those with virtual functions

### ISSUE THREAD

**Issue by carlosgalvezp** [isocpp/CppCoreGuidelines#1831]
Hi,

Rule C.35 is fine as it is, however the enforcement is  incomplete:

> **Enforcement**
> A class with any virtual functions should have a destructor that is either public and virtual or else protected and non-virtual.

The purpose here is to prevent undefined behavior. UB happens anytime a child is deleted via a pointer to the base class, and the base class has no virtual dtor:

https://timsong-cpp.github.io/cppwp/n4140/expr.delete#3

> In the first alternative (delete object), if the static type of the object to be deleted is different from its dynamic type, the static type shall be a base class of the dynamic type of the object to be deleted and **the static type shall have a virtual destructor or the behavior is undefined.** 

Therefore, the enforcement shouldn't care at all if the base class has virtual functions or not. Simply, if a class is inherited from (i.e. it's a base class), it shall have public virtual / protected non-virtual dtor.

Tools like clang-tidy are implementing checks based on the text of this rule, and they only trigger when the base classes have virtual functions. Therefore they don't catch the following UB:

https://godbolt.org/z/P1hj6Whsr

It would be good to update the "Enforcement" part of this rule, so clang-tidy checks can also detect the above mentioned UB.

**Comment by MikeGitb** [comment]
One problem is that without whole program analysis, there is no way to proof, that a class is not being inherited from and if you  conservatively consider any class not marked final as being inherited, you'd probably get a humongous amount of false positives.

The other thing is that inerhiting from a class without a virtual dtor is not inherently an error. It only becomes an error, when its deleted through the base class pointer as you pointed out. But for example, if you create all instances on the stack, as member of another class, manage it by a `shared_ptr<Base>` or a `unique_ptr<Derived>`, you don't need a virtual dtor and if there aren't any other virtual functions in the class, then adding a virtual dtor comes with some cost (e.g. increase in size, otherwise trivial class are no longer tivial, which impacts code gen etc.).

I'd support having a separate, optional check that any class should either be final or have a virtual/protected dtor, but I doubt it is useful as a general on-by-default check.

**Comment by carlosgalvezp** [comment]
Thanks for the quick reply!

I definitely agree with not being over-defensive and marking everything final / adding virtual/protected dtor. I'm no expert at all in how this could be implemented, but why would whole program analysis be needed? Tools typically look at one .cpp file at a time. This .cpp file either will define classes or get them from a number of headers, transitively. The tools will see the contents of all these headers, so they would be able to see that a given class is inherited from, or?

```
// foo.cpp
#include "derived.h"

int main()
{
    Base* base = new Derived{};
    delete base;
}
```

```
// derived.h
#include "base.h"

class Derived : public Base
{};
```
```
// base.h
class Base
{};
```

Perhaps this is not the forum to discuss implementation. I agree a separate check would make sense!

**Comment by hsutter** [comment]
Editors call: The reason for the Enforcement being narrower is because it's locally checkable. We generally don't know if a class without virtual functions is going to be used as a base class. However, we can add another Enforcement where when seeing a derived class we enforce that the base class (which we now know locally is a base class) is following the rule. Thanks!

**Comment by carlosgalvezp** [comment]
Looks great, thanks a lot!
