### ISSUE TITLE
C.44 conflicts with RAII

### ISSUE THREAD

**Issue by svebert** [isocpp/CppCoreGuidelines#1934]
[C.44: Prefer default constructors to be simple and non-throwing](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c44-prefer-default-constructors-to-be-simple-and-non-throwing)
MS VC compiler complains with checker warning C26455 DEFAULT_CTOR_NOEXCEPT when my class has a custom default constructor which may throw. Microsoft points me to Core guideline C.44.
Even after reading some stackoverflow issues relating to this dilemma, I can't understand the deeper sense behind C44. Why are move operations affected by my custom default constructor? Move is related to the move constructor.
Any class, which handles hardware resources or something similar has the chance to fail on construction. Maybe the database server is down, the disk memory is not large enough for allocations, COM port is not available, etc. I find it very reasonable, that a class controlling/handling such resources throws on construction, if something goes wrong. I really like the RAII principle and I really like to throw in constructors.
I also do not understand why the custom default constructor (=constructor without arguments) is something "special" in this regard, compared to other constructors with parameters.
To work around C44, i have to introduce Initialize()/Uninitialize() functions. For me this is unessescary boiler plate code.

Finally "prefer default constructors to be simple" is just saying nothing. Each and every line of code should be as simple as possible. This is nothing special about default constructors.

**Comment by MikeGitb** [comment]
Note that the Rule says "Prefer" not "always do X".

That aside: 

> Maybe the database server is down, the disk memory is not large enough for allocations, COM port is not available, etc. 

The implication here is that a default constructed object should not open a COM port, database connection or allocate dynamic memory.  Imho that makes sense for most types, as you probably would want to specify what port to open/which database to connect to and as the memory requirement of a default constructed type is (usually) know at compiletime, there is rarely a need for dynamic memory allocation.

But again: I read it as a recommendation. Not a hard rule.

**Comment by jwakely** [comment]
> Why are move operations affected by my custom default constructor?

They're not *affected* by it. The point is that it's difficult to have a valid moved-from state if you don't have a cheap default constructed state. A sensible state for an object that has been moved from is the default constructed state.

> Any class, which handles hardware resources or something similar has the chance to fail on construction. Maybe the database server is down, the disk memory is not large enough for allocations, COM port is not available, etc.

Why are you doing that in a **default** constructor? Don't you need to pass in connection details for the database, or a COM port name? If those are hardcoded into your default constructor (or obtained from global variables) then that's a questionable design decision. It makes the type hard to test and hard to reuse.

> To work around C44, i have to introduce Initialize()/Uninitialize() functions. For me this is unessescary boiler plate code.

That should not be necessary.

> Finally "prefer default constructors to be simple" is just saying nothing. Each and every line of code should be as simple as possible.

It doesn't say "as simple as possible", it says simple. As in not do much work. Leave that for non-default constructors that take parameters and create (or take ownership of) resources determined by the parameters.

But if you don't want to follow that style in your code, that's fine. Suppress the warning. That doesn't make it bad advice, just not for you.

**Comment by jwakely** [comment]
>   But why it is a recommendation, if it destroys RAII?

It doesn't destroy RAII, that's utter nonsense. Look at the RAII types in the standard library: none of them acquires resources in their **default** constructor. Does `unique_ptr` have a default constructor that allocates an object? No, the default constructor creates an empty object. Does `unique_lock` have a default constructor that owns and locks a mutex? No, it has a default constructor that creates an empty object. Does `vector` or `string` allocate resources in the default constructor? No.

It's a guideline because the recommendation is to **not** acquire resources in your default constructor. That doesn't mean "don't acquire resources" or "don't manage resources using RAII" and to claim it does is ridiculous.

> Is RAII not recommended anymore?

Of course it is - are you trolling?

**Comment by svebert** [comment]
> They're not _affected_ by it. The point is that it's difficult to have a valid moved-from state if you don't have a cheap default constructed state. A sensible state for an object that has been moved from is the default constructed state. That doesn't work if your default constructor does lots of work, opening database connections or allocating memory.

This is my class:

```
class A
{
public:
  A::A(){
    m_vData.resize(1000);
  };
private:
 std::vector m_vData;
}
```
as memory could be limited, resize may throw, thus the constructor A() may throw. Also my understanding, that the compiler generates for class A a default move constructor.
First case:
`A b = std::move(A());`
Either the auto generated move constructor is used (which will not throw) or copy elision is used (which uses the default constructor and may throw). As no moved-from object exists, i do not see any problem with an exception in the default constructor.
`A a;
A b = std::move(a);`
If first line throws, second line will not run. So no problem. 
If second line runs, a is moved into b, b is moved into a (swap). Thus the default constructor is called to construct b. From my understanding b should be constructed before the swap. Otherwise the swap can't work. If constructing throws, nothing will be swapped, so there is no problem with the moved-from state.

I do not see a problem with a throwing custom default constructor.

**Comment by svebert** [comment]
> Maybe you are just confused about RAII? Look at the relevant section of the guidelines: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rr-raii
> 
> Do you see work being done by default constructors in the example using `Port` and `lock_guard` types? Clearly RAII doesn't require allocating/opening resources in a default constructor.
> 
> As I already said, if you choose to ignore the guideline and use a form of RAII that _does_ do work in the default constructor, that's your choice. It doesn't make it a bad guideline.

I don't understand the positive effect of the guideline. I just see a restriction and I do not understand the reasoning behind it. 
If I implement the "heavy work" in a constructor with parameters A(a, b, c) and implement a default constructor via constructor delegation with some default parameters A() : A(a=1, b=2, c=3), I violate this C44 guideline.

**Comment by jwakely** [comment]
> As no moved-from object exists, i do not see any problem with an exception in the default constructor.

So you're saying that because you can show an example where something doesn't happen, that you never need to think about whether it happens in other cases? That's ... interesting.

> If second line runs, a is moved into b, b is moved into a (swap).

Nothing gets swapped. A move is not a swap.

> If I implement the "heavy work" in a constructor with parameters A(a, b, c) and implement a default constructor via constructor delegation with some default parameters A() : A(a=1, b=2, c=3), I violate this C44 guideline.

Yes, because you've still got a default constructor doing "work" which is what the guideline suggests (not requires!) to avoid. Is that really so hard to understand? Moving the work into another function that is still used by the default constructor doesn't change anything. The suggestion is to do:

    A() noexcept { } // does nothing
    A(int, int, int) { /* acquire resources */ }

i.e. do not acquire resources in the default constructor. Have a different constructor that you use when you want to acquire resources. The guideline even shows a case exactly like this (`Vector1`).

But if that doesn't make sense in your program, you don't have to follow the guideline. It says "prefer" to do it.

**Comment by svebert** [comment]
Ok. So... I do not "prefer" C.44 ....

I still strongly suggest, that this "core guidline" is not reasonable. 
What are my options:
* ignoring it
* not using custom default constructors
* introducing internal "initialized/not-initialized" state (which is what I understand as conflict to RAII).

**Comment by shaneasd** [comment]
If you genuinely believe that the advice given in C.44 is not appropriate why are you asking msvc to issue a warning for it? Can't you set up static analysis profiles where you explicitly specify which rules you want checked?

Personally I think @jwakely makes a compelling argument for why you should follow C.44 but if you're convinced that you shouldn't and looking for options to stop visual studio issuing C26455 then not asking it to check C26455 seems like it should be on your list.

**Comment by bgloyer** [comment]
>  I also do not understand why the custom default constructor (=constructor without arguments) is something "special" in this regard, compared to other constructors with parameters.

This here is the key.  The default constructor is special because other things (such as move operations) will create empty versions of your type using the default constructor.  If the default constructor throws, it causes trouble for those things.  You do have a good point about the wording. The reseasoning of the rule says it "simplifies error handling and reasoning about move operations" which it true but requires a deep understanding of C++ understand.  Maybe we can add some of the discussion here?

For your class, there are a few options:
- Pass the size in as a parameter in a different constructor and have the default constructor create an empty object
- If the size is really always 1000, use a std::array instead of vector which would make it noexcept (assuming the type it is containing is noexcpt default constructable - another example of why C.44 is important)
- Create the vector empty in the default constructor and resize it at first use.

**Comment by jwakely** [comment]
> This here is the key. The default constructor is special because other things (such as move operations) will create empty versions of your type using the default constructor.

That's not accurate. When you move from an object the default constructor is not used. Move operations will often create empty versions of your type, but not by using the default constructor.

The point is that it's useful to have a simple "empty" state that maintains all invariants and is easy (and efficient and safe) to obtain. Move operations will typically leave an object in that state, e.g. after it has been moved from, a `unique_ptr` is empty.

Furthermore, having an "empty" state that is not the same as the "default" state (i.e. the one create by the default constructor) is not recommended. It makes our type harder to reason about. Imagine if `std::string` had both an 'empty string' state corresponding to a zero-length string, `""`, and also a 'null' state corresponding to `c_str() == nullptr`. Every bit of code using `std::string` would have to be prepared to handle null pointers as well as empty strings.

So the point of C.44 is that for types with such an empty state, it probably makes sense for the default constructor to be *one way* to get an object in that state (there might be other ways too, like a `clear()` member or `reset()` member). Otherwise you have to reason about "empty" states and "default" states as two separate values. Usually, having such a distinction between those states is not helpful. So the guideline says to prefer a default constructor that establishes a cheap, non-throwing "empty" state.

**Comment by svebert** [comment]
> If you genuinely believe that the advice given in C.44 is not appropriate why are you asking msvc to issue a warning for it? Can't you set up static analysis profiles where you explicitly specify which rules you want checked?

I am not asking msvc to warn me about it. It warns me without asking! Of course, I can silence this warning. But I usually try to fix all warnings, because usually there is a deeper and sensible reason for it.

**Comment by jwakely** [comment]
No, you don't **have to** do anything. It's a guideline, it says "prefer", you can choose to ignore it.

I've said that repeatedly. If you don't like the guideline or it doesn't apply to some of your classes, you don't have to follow it. It seems like you're just looking for an argument and wasting everybody's time.

**Comment by BenjamenMeyer** [comment]
> > > If you genuinely believe that the advice given in C.44 is not appropriate why are you asking msvc to issue a warning for it? Can't you set up static analysis profiles where you explicitly specify which rules you want checked?

> > I am not asking msvc to warn me about it. It warns me without asking! Of course, I can silence this warning. But I usually try to fix all warnings, because usually there is a deeper and sensible reason for it.

** snip **
> I've said that repeatedly. If you don't like the guideline or it doesn't apply to some of your classes, you don't have to follow it. It seems like you're just looking for an argument and wasting everybody's time.

Perhaps a tooling issue? This is one reason I don't like the `black` linter in the Python world b/c you can't override things; and folks tend to take guidelines as rules that must be followed especially when tooling presents it as such, so they stop thinking (as desired here).

$0.02 FWIW

**Comment by MikeGitb** [comment]
AFAIK, msvc doesn't warn on core guideline violations.  You have to activate the code analysis engine in VS (https://docs.microsoft.com/en-us/cpp/code-quality/using-the-cpp-core-guidelines-checkers?view=msvc-170). Admittedly, I don't remember,  if this is enabled by default in Visual Studio (which is not the and as msvc btw.)
