### ISSUE TITLE
Why is rule R.13 needed if we have rules R.20, R.22 and R.23?

### ISSUE THREAD

**Issue by pauljansen42** [isocpp/CppCoreGuidelines#1990]
R.13 checks for expressions with multiple explicit resource allocations. However, the standard forbids explicit resource allocations. According to the examples in the description of R.13, using make_shared multiple times in an expression is fine. So if you use only make_shared and make_unique, which is highly recommended by the Core Guidelines, then the situation described in R.13 will never occur. So why do we have that R.13 rule, if it is already forbidden by other rules?

From experience I can tell that if you have a rule "Don't do X", you shouldn't have other rules about X because it causes confusion and might even result in justifying to use X because there is a rule about it.

What is your take on this?

**Comment by beinhaerter** [comment]
From my understanding R.13 is not only about `shared_ptr` and `unique_ptr`, it is about all resource allocations. Thus `make_shared` and `make_unique` alone are not sufficient.

> However, the standard forbids explicit resource allocations.

I guess you mean "the CoreGuidelines" instead of "the standard", but where did you read that? The CoreGuidelines request not to use `malloc` or naked `new`, but they do not forbid explicit resource allocations in general. They strongly suggest to use a resource manager object though (R.1, R.12).

**Comment by neithernut** [comment]
Basically what @beinhaerter said: resource allocation is not limited to memory.

If you follow R.20, R.22 and R.23 you would indeed not end up with the example in R.13. However, consider a dev who needs to fiddle with OS resources such as file descriptors (or handles). If the resource is not managed by some object responsible for freeing the resource (RAII) then you have the same problem. I assume the example in R.13 ended up this way because when writing examples you usually prefer something that's already there rather than introducing something new (such as POSIX system calls).

You _could_ argue that the problem goes away if you consistently use the RAII pattern _and_ encapsulate the allocation if you ever have to allocate some resource. However, in some situations allocation is not encapsulated in the creation of the manager object (imagine a general manager object for file descriptors of any type with a ctor taking just an `int fd`) or you may need to create such an abstraction yourself. If you find yourself in such a situations, R.13 applies.

**Comment by pauljansen42** [comment]
Thanks for the clear explanation. I understand its value now. However, I still think that using a different example would have helped. So consider this issue as a request to use another example to make sure this rule is clear to everyone.

Side note. We are implementing the C++ core guideline as a company in a code checker and for rule R.1 we flag all kinds of non RAII allocations, so it looks to me like that it is very unlikely that rule R.13 will fire in case you follow the other rules.

**Comment by BjarneStroustrup** [comment]
specific rules are useful for comprehension and enforcement, where the implications of general rules covering them are not obvious to all
