### ISSUE TITLE
C.65 Counter example for “valid but unspecified” state for the standard-library containers

### ISSUE THREAD

**Issue by ecorm** [isocpp/CppCoreGuidelines#2023]
[C.65](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#c65-make-move-assignment-safe-for-self-assignment) has the following note:

> **Note** The ISO standard guarantees only a “valid but unspecified” state for the standard-library containers. Apparently this has not been a problem in about 10 years of experimental and production use. Please contact the editors if you find a counter example. The rule here is more caution and insists on complete safety.

Here is such a counter-example: containers providing a guarantee to not invalidate iterators (depending on allocator) for move-assignment, as proposed in https://cplusplus.github.io/LWG/issue2321.

If a self-moved-assigned container does not preserve its state, then it follows that it cannot always provide the guarantee of not invalidating iterators.

**Comment by ecorm** [comment]
The use case of preserving iterators also affects [C.62](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c62-make-copy-assignment-safe-for-self-assignment). If the object is a container providing an iterator interface, altering its state during self-copy-assignment will invalidate the iterators of the right-hand-side operand.

**Comment by ecorm** [comment]
See my post here in the C++ std-proposals mailing list concerning the contradiction between "valid, but unspecified state" versus iterator preservation for self-move-assignment: https://lists.isocpp.org/std-proposals/2023/01/5439.php

**Comment by hsutter** [comment]
Editors call: We think you are agreeing with our stricter rule, correct?

**Comment by ecorm** [comment]
> Editors call: We think you are agreeing with our stricter rule, correct?

I do agree with it. I was merely trying to contribute a counter example as requested in the following remark:

> The ISO standard guarantees only a “valid but unspecified” state for the standard-library containers. Apparently this has not been a problem in about 10 years of experimental and production use.

If you don't agree that expecting iterators to be preserved after a move-assignment is a potential problem for standard library containers, then please disregard my proposed counter example.

Apart from the counter example, I have the following remarks concerning the text of C.65:

(1) The `// this line is redundant` comment is incorrect if `Foo` exposes iterators or pointers to its underlying `string s`, as standard library containers are (not yet) required to preserve iterators upon move assignment.

(2) The text is confusing with the `// this line is redundant` comment, followed by the note that says

> There is no known general way of avoiding an `if (this == &a) return *this;` test

Which lead me to question whether I perform the `if (this == &a) return *this;` test or not.

**Comment by jwakely** [comment]
You wrote:

> I'm not interested in learning the bureaucracy involved in writing my own standard library defect report, 

All it takes is sending an email, which you already managed to do when saying that.
https://cplusplus.github.io/LWG/lwg-active.html#submit_issue

**Comment by jwakely** [comment]
> Which lead me to question whether I should perform the `if (this == &a) return *this;` test or not.

If you implement move-assignment in such a way that self-move is a no-op anyway, then there's no need for the explicit test. If your implementation of move-assignment would result in data loss on self-move, and you want to avoid that, you should add the explicit test.

For example, you could implement it by transferring the contents of the rvalue operand to a local variable, `tmp`, then free the contents of `*this` (which will now be empty in the case of self-move, because you transferred them to `tmp`, then transfer from `tmp` to `*this`. This implementation Just Works :tm: for self-move, and so there's no need for an explicit test.

But this kind of implementation might not always be possible in the general case. Or it might be suboptimal for the common not-self-move case, so you might prefer the explicit test. It depends on the container implementation.

**Comment by jwakely** [comment]
> You wrote:
> 
> > I'm not interested in learning the bureaucracy involved in writing my own standard library defect report,
> 
> All it takes is sending an email, which you already managed to do when saying that. https://cplusplus.github.io/LWG/lwg-active.html#submit_issue

Since one of the issues is still open, i.e. not approved or part of the standard, I don't think a new issue is needed anyway. We don't open issues against other open issues, only against what's actually in the standard. I'll add a note to [LWG 2321](https://wg21.link/lwg2321) pointing out that it needs to take account of the changes made by [LWG 2839](https://wg21.link/lwg2839).

**Comment by ecorm** [comment]
> All it takes is sending an email, which you already managed to do when saying that.
https://cplusplus.github.io/LWG/lwg-active.html#submit_issue

Ah, sorry. I didn't realize it would be that simple. I'm wary of dealing with committees for all sorts of things, not just C++. :grin:

> If you implement move-assignment in such a way...

Thanks for the clarification. I think it (or something similar) should be added to the Guidelines.

> Since one of the issues is still open, i.e. not approved or part of the standard, I don't think a new issue is needed anyway. We don't open issues against other open issues, only against what's actually in the standard.

Would sending an email as per https://cplusplus.github.io/LWG/lwg-active.html#submit_issue still have been the correct procedure, then?

**Comment by jwakely** [comment]
Yes, you can use the same address to request a comment to be added to an issue discussion. Please take a look at the 2321 note to check I didn't misrepresent you.

**Comment by ecorm** [comment]
> Please take a look at the 2321 note to check I didn't misrepresent you.

Looks good, thanks!

**Comment by BjarneStroustrup** [comment]
Thanks
