### ISSUE TITLE
Create a build step/system targeting e-book version of the Guidelines

### ISSUE THREAD

**Issue by engreimor** [isocpp/CppCoreGuidelines#204]
Maybe one can put some effort at creating a build step over the guidelines targeting the creation of a epub and/or mobi files. It would be handy to have the latest guidelines release over my reader.

As a "short-cut", Amazon delivers a tool which generates books from html files targeting kindle devices. Calibre project has multiple converters for electronic books.

**Comment by weisert** [comment]
I tried [this](http://pandoc.org/epub.html). Looks fine.

**Comment by engreimor** [comment]
seems good. should we use make to "automagically" build the guidelines epub?

**Comment by hsutter** [comment]
The license allows you to make derivative works like ebooks for your personal or internal business use.
We're thinking about other ways of providing ebooks.

**Comment by rlunaro** [comment]
Ok, this issue is closed but I want to let you know that I've created a kindle version of this guidelines. I've requested a pull request to introduce the changes in the build system. On top of that, you can check out my project at https://github.com/rlunaro/CppCoreGuidelines which has the necessary modifications. 

Problems that still have to be fixed: 
- creation of epub doesn't work, but derivative kindle version does 
- I am thinking in ways to create a proper Table of Contents out of the .md file itself, with no more modifications
- The table of contents now is createad by hand, should be created programmatically
