### ISSUE TITLE
Separation of enforceable and non-enforceable recommendations -- we need an index for advice

### ISSUE THREAD

**Issue by KayEss** [isocpp/CppCoreGuidelines#205]
I was looking at #170 and I've been thinking about enforcement for F.52 and F.53. We don't yet have enforcement for the latter two, but I think they're amenable to working out what the rules would be such that a tool can tell us when we make a mistake.

The proposed rule in #170 is a completely different beast -- I can think of no way that a tool can advise on this. For the closure rules a developer will find them when their tools point them at the rule, but for this one that isn't going to happen.

Surely that means that eventually we're going to need some index of non-enforceable rules so that developers can be pointed at them by other people, and presentation and navigation of the non-enforceable ones is going to need to be different as the discovery mechanism needs to be through a completely different mechanism?

I can see many not bothering to read through the enforceable ones, instead relying on the tools to tell them, much like many developers treat the standard. But we'll eventually need a culture of reading the non-enforceable ones so some separation seems sensible.

**Comment by hsutter** [comment]
This is a good suggestion and we try to mark the level of effort required to enforce a given Enforcement, and will keep trying to improve this over time.

There is a range of degrees of enforceability. We expect that over time the enforcement will change. We are trying to label them (e.g., Easy, Difficult) but there are not just two well-delineated classes of enforcement. We also don't want to group by enforceability because related rules will then be separated.

We think that what you really want to know is "which rules does my tool enforce" so the list people will most want is the list provided by their tool vendor. We have N levels of enforcement/enforceability and M different tools.
