### ISSUE TITLE
Discourage the use of enumerations to emulate polymorphism.

### ISSUE THREAD

**Issue by andre-caldas** [isocpp/CppCoreGuidelines#2059]
In the section about enumerations, I think it should be mentioned that enumerations shall not be used to emulate polymorphism.

Things like...
```
class FakePolymorphic
{
private:
  enum typeEnum {
    SIMPLE,
    MAP,
    ARRAY,
    RANGE,
  };

  // Those have different meanings according to typeEnum.
  int var1;
  int var2;
  int var3;

public:
  bool isSimple() const;
  bool isMap() const;

  void doSomething() {
    if(isSimple()) {...}
    if(isMap()) {...}
    if(isArray()) {...}
    if(isRange()) {...}
  }
};
```

One concrete example:
https://github.com/FreeCAD/FreeCAD/blob/642b8b319625f7d737a09c5a0f87516d9ccb63c3/src/App/ObjectIdentifier.h#L152

https://github.com/FreeCAD/FreeCAD/blob/642b8b319625f7d737a09c5a0f87516d9ccb63c3/src/App/ObjectIdentifier.cpp#L621

**Comment by hsutter** [comment]
Editors call: We understand the comment, but unfortunately sometimes this is needed: (a) to implement variant-like behavior, and (b) to use `std::variant` because `std::variant` does not allow giving the alternatives names and so it's a common pattern to declare an `enum` right beside the variant to give names to the alternatives.
