### ISSUE TITLE
Extending or Removing do-while avoidance rule

### ISSUE THREAD

**Issue by the-moisrex** [isocpp/CppCoreGuidelines#2064]
The do-while statement is a useful construct for implementing loops that must execute at least once. The do-while statement is not inherently more confusing or error-prone than other loop statements, as long as it is used with proper indentation and braces. Therefore, the rule ES.75 should be either removed or extended to allow do-while statements in cases where they improve readability and expressiveness.

In the **Reason** second of ES.75, it states: `Readability, avoidance of errors. The termination condition is at the end (where it can be overlooked) and the condition is not checked the first time through.`; I'm gonna tackle each of these statements here:

- **Readability**: There's only one way we can use `do { ... }`, it doesn't reduce readability. `for(;;) { ...; if (..) break;}` is a lot scarier than do-while.
- **avoidance of errors**: most of the errors there is because the user needed to use a normal while loop not a do-while
- **The termination condition is at the end (where it can be overlooked)**: do-while requires a condition; some of the alternatives do not. This means with do-while the developers at least won't forget to put the termination condition.
- **the condition is not checked the first time through**: I'm pretty sure that is the main talking point of do-while statement and that's why it's useful.

I propose either remove ES.75 completely, or add more constraints to it. For example, "Avoid do-while statements where other loops are better choices"

C++ Core guideline have grown a lot, so has the `NOLINT` comments in my codes.

**Comment by LegalizeAdulthood** [comment]
I also thought it weird that the core guidelines were telling me not to use do/while loops as they are perfectly valid and normal for all the reasons stated above.

**Comment by MikeGitb** [comment]
Can you provide an example?

**Comment by the-moisrex** [comment]
> Can you provide an example?

There are plenty of examples, you can just `grep` for it. Most of them are valid use-cases.

**Comment by MikeGitb** [comment]
Just saying, it might be easier for you to convince the maintainers if you could give a specific example where while is noticeable worse than do while or for loops.

It also helps to come to a understanding of each other's view, because what you consider a valid usecase might not be considered one according to the maintainers and vice versa.

Personally I have no skin in the game,  because I can't even remember when I last wrote a do while loop.

**Comment by the-moisrex** [comment]
There's a good discussion about this on [this stackoverflow](https://stackoverflow.com/questions/994905/is-there-ever-a-need-for-a-do-while-loop); plenty of examples too.

I understand Bjarne Stroustrup has discouraged it, but there are just plenty of cases where do-while is just the best choice because when I see `do {` I absolutely know it's supposed to run at least once, there are no alternatives that actually states that intent immediately other than `for(;;)` + `break` which I think it's a lot easier to understand do-while than it is to grasp that kinda loop.

**Comment by hsutter** [comment]
Editors call: The Guidelines aren't saying that `do` loops aren't useful, but that they tend to be more error-prone. One frequent use of `do` is in macros that use `do ... while(false)` to execute once. We don't feel the current examples are compelling enough to warrant changing this guideline right now.

**Comment by BenjamenMeyer** [comment]
Honestly, I find using `do{}while` and `while{}` loops to be far more readable than trying to force everything in to a `for(;;){}` loop. I had the same issue back in college when they tried to teach only for-loops, and it's honestly far more confusing to force a `do{}while` or `while{}` style loop into a `for(;;){}` loop. Instead, it should be a simple matter of when the condition needs to be tested:
- pre-condition :arrow_right: `while{}` loop
- post-condition :arrow_right: `do{}while` loop
- counter :arrow_right: `for(;;)` loop
- infinite loop :arrow_right: `while(true){}`

People are going to abuse loops no matter what - like in @hsutter 's example of the `do{...}while(false)` done in Macros - if those single execution cases should just be a separate block scope (no loop syntax, just block syntax).

**Comment by jleffler** [comment]
On Wed, Apr 19, 2023 at 12:05 Benjamen Meyer ***@***.***>
wrote:

> People are going to abuse loops no matter what - like in @hsutter
> <https://github.com/hsutter> 's example of the do{...}while(false) done
> in Macros - if those single execution cases should just be a separate block
> scope (no loop syntax, just block syntax).
>

The do{…}while(false) construct is necessary in macros because if you have:

if (condition)
    macro(…);
else
    function(…);

and if the macro just expands to a {…} block instead of a do{…}while(false)
loop, you have a syntax error (orca bug) because the semi-colon after the
macro becomes a null statement.


-- 
Jonathan Leffler ***@***.***>  #include <disclaimer.h>
Guardian of DBD::Informix - v2018.1031 - http://dbi.perl.org
"Blessed are we who can laugh at ourselves, for we shall never cease to be
amused."

**Comment by BenjamenMeyer** [comment]
> On Wed, Apr 19, 2023 at 12:05 Benjamen Meyer ***@***.***> wrote: People are going to abuse loops no matter what - like in @hsutter <https://github.com/hsutter> 's example of the do{...}while(false) done in Macros - if those single execution cases should just be a separate block scope (no loop syntax, just block syntax).
> The do{…}while(false) construct is necessary in macros because if you have: if (condition) macro(…); else function(…); and if the macro just expands to a {…} block instead of a do{…}while(false) loop, you have a syntax error (orca bug) because the semi-colon after the macro becomes a null statement.

Two things:

1. This is why all If blocks should be using braces themselves so it should be - even if it's just a single line:
```
if (condition) {
    macro(...);
} else {
   function(...);
} 
```
There are many bugs that would be resolved by doing just that.
2. It's long be the case that doing things the function body like that is bad form. Since we're talking C++ (and not C), such things should be inline or templatized functions any way, and there's probably other guidelines being violated.

Even so, I would say it's not the best thing to do, but I wouldn't want a linter rejecting it either.
