### ISSUE TITLE
Rule F.54 not clear about capturing this and the use of [&] 

### ISSUE THREAD

**Issue by pauljansen42** [isocpp/CppCoreGuidelines#2076]
The synopsis of rule F.54 is "When writing a lambda that captures this or any class data member, don’t use [=] default capture". Note that [&] is not mentioned. The enforcement of the rule is "Flag any lambda capture-list that specifies a capture-default of [=] and also captures this (whether explicitly or via the default capture and a use of this in the body)". Still, [&] is not mentioned.

But in the examples 

 auto lambda = [=] { use(i, x); };   // BAD: "looks like" copy/value capture
        // [&] has identical semantics and copies the this pointer under the current rules
        // [=,this] and [&,this] are not much better, and confusing

we see that [&] or [&,this] is not recommended as well. 

So my question is, should [&] be added to the synopsis and the enforcement, or should the example be adjusted.

**Comment by iglesias** [comment]
> The synopsis of rule F.54 is "When writing a lambda that captures this or any class data member, don’t use [=] default capture". Note that [&] is not mentioned. The enforcement of the rule is "Flag any lambda capture-list that specifies a capture-default of [=] and also captures this (whether explicitly or via the default capture and a use of this in the body)". Still, [&] is not mentioned.
> 
> But in the examples
> 
> auto lambda = [=] { use(i, x); }; // BAD: "looks like" copy/value capture // [&] has identical semantics and copies the this pointer under the current rules // [=,this] and [&,this] are not much better, and confusing
> 
> we see that [&] or [&,this] is not recommended as well.
> 
> So my question is, should [&] be added to the synopsis and the enforcement, or should the example be adjusted.

I think neither, as the the logic concluding that [&], etc. *are* not recommended is missing.

**Comment by pauljansen42** [comment]
Let me be clearer. The example is stating that [&, this] is not good either. Shouldn't that be forbidden then too? Or adjust the example and remove the [&, this] part? Now it is inconsistent.

**Comment by shaneasd** [comment]
My reading of the rule is that `[&]` is fine for capturing `this` so there's not reason to change the rule wording or enforcement.

I do agree the mention of `[=,this]` and `[&,this]` sort of muddy the waters in what would otherwise be a clear rule. Anecdotally this feels like a recurring pattern in the core guidelines where additional (correct and useful) information is thrown in in examples or remarks which distracts from or obfuscates the key message. I think this is evidence that writing universally understandable guidelines is very challenging. You might argue that the rule is clearer by being more focused without the mention of `[=, this]` and `[&,this]` but would it be better for the guidelines not to voice an opinion on these at all? Perhaps we should have a rule specifically targeting `[=,this]` and `[&,this]` which complements this rule but would that be overkill for such a niche usage.

So in answer to the original question I think [&], [&,this], [=,this] shouldn't be added to the synopsis but I'm not sure the solution is as simple as removing them from the example either.

**Comment by pauljansen42** [comment]
Thanks for this comment. You are completely right saying "Anecdotally this feels like a recurring pattern in the core guidelines where additional (correct and useful) information is thrown in in examples or remarks which distracts from or obfuscates the key message". This makes it hard to enforce the standard because the description of the rule sometimes contradicts the synopsis and/or contradicts the enforcement. 

Let's start improving the standard step by step. The first step is to remove the comments:

// [&] has identical semantics and copies the this pointer under the current rules
// [=,this] and [&,this] are not much better, and confusing

This would help me a lot explaining the rule and its enforcement.

**Comment by shaneasd** [comment]
You may get more traction raising this as a simple pull request. I note that there are 242 open issues and only 10 open pull requests.

**Comment by hsutter** [comment]
Closed with PR. Thanks!
