### ISSUE TITLE
F.20 should exclude swap

### ISSUE THREAD

**Issue by PowerStat** [isocpp/CppCoreGuidelines#2167]
The rule F.20 should exclude a standard "void swap( T& a, T& b );" implementation.
Or it should be made clearer when not to use this rule.

This is also a Problem of the Autosar C++14 A8-4-8 rule (Output parameters shall not be used.)

**Comment by jwakely** [comment]
The parameters to a `swap` function are in-out parameters, not out parameters. So F.17 applies, not F.20.

The enforcement for F.20 says to flag non-const reference parameters that are not read before being written to (because that implies they are out parameters, not in-out parameters). That enforcement won't trigger for a conventional `swap` because you have to read them before writing to them.

What's the concrete problem here?

**Comment by PowerStat** [comment]
Mayben then the problem is that static code analysis tools detect this in a wrong way, or this is not well understand.
