### ISSUE TITLE
How to refer to the guidelines, bibtex preferred?

### ISSUE THREAD

**Issue by VictorEijkhout** [isocpp/CppCoreGuidelines#2193]
More or less what it says in the subject: what's the preferred way to refer to the code guidelines in a bibliography, preferable in bibtex format, but I'll take plain text?

**Comment by iglesias** [comment]
Even though I do not know if there's a preferred way and, furthermore, I doubt it would have been established in relation with TeX, I suggest to refer to either the GitHub repository and/or its webpage view (https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines), based on your preference.

Perhaps drawing inspiration from Rainer Grimm's book "C++ Core Guidelines Explained: Best Practices for Modern C++" may help, since, I assume, it must refer to the guidelines somehow. As a bit of a disclaimer, just in case: I haven't worked with the book, so, please, do not find a recommendation to it per se in this message. It is something I have come across now searching for related bibliographical resources.

Personally, depending on the goal of the reference, I would recommend citing one of the recent (last few years) keynotes by Bjarne Stroustrup where the guidelines are nicely motivated and contextualized.

**Comment by VictorEijkhout** [comment]
So just the URL, no author?

**Comment by hsutter** [comment]
Editors call: Thanks! You can use this :"C++ Core Guidelines" <link> B. Stroustrup, H. Sutter, et al. (eds)

We have no suggestions on bibtex.
