### ISSUE TITLE
Ceil Function in Cpp

### ISSUE THREAD

**Issue by MrCodYrohit** [isocpp/CppCoreGuidelines#2201]
There is an issue when I use the `ceil` function in C++. When I try `ceil(1/15)`, instead of returning 1, it returns 0 because `1/15` evaluates to 0.06. In Python, `ceil(1/15)` correctly returns 1. I believe this behavior in C++ needs improvement.

**Comment by fanyanlv** [comment]
place you inter go CSDN






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pluto ***@***.***&gt;; 
发送时间: 2024年5月21日(星期二) 下午4:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [isocpp/CppCoreGuidelines] Ceil Function in Cpp (Issue #2201)














 
There is an issue when I use the ceil function in C++. When I try ceil(1/15), instead of returning 1, it returns 0 because 1/15 evaluates to 0.06. In Python, ceil(1/15) correctly returns 1. I believe this behavior in C++ needs improvement.

**Comment by jwakely** [comment]
This repository is for guidelines on effective use of C++, not for comments or bug reports on the language itself, so this issue os completely off-topic here.

> because `1/15` evaluates to 0.06

No it doesn't. `1` and `15` are both integers, so `1/15` performs integer arithmetic, and the result is `0`. C++ is not Python, it is silly to expect it to behave the same as Python.

Use `1.0/15` or `1/15.0` or `1.0/15.0` if you want the result to be a floating-point value instead of an integer.

**Comment by mcjurij** [comment]
`#include <cmath>
#include <iostream>

int main()
{
    int x = ceil( 1./15.);
    std::cout << "x= " << x << "\n";
}
`

shows "x= 1".  gcc 13.
