### ISSUE TITLE
clarify C.83: value-like types  and are non-trivially copyable types

### ISSUE THREAD

**Issue by minwang-ai** [isocpp/CppCoreGuidelines#2242]
> C.83: For value-like types, consider providing a noexcept swap function
> Enforcement
> Non-trivially copyable types should provide a member swap or a free swap overload.

The rule itself, and the enforcement, it used two terms interchangeably, which should be the intersaction, isn't it?

I think [C.83](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c83-for-value-like-types-consider-providing-a-noexcept-swap-function) should be:
 For value-like types that are non-trivially copyable, provide a noexcept swap function.

**Comment by hsutter** [comment]
Editors call: Thanks! The enforcement is written this way because trivially copyable types already can be swapped using `std::swap`, so there's usually no need to encourage people to write a redundant swap function that does the same thing. This is in the same spirit as that we tell people not to write their own copy function that does the same thing as the compiler-generated one.
