### ISSUE TITLE
Typo in "Sutter - CppCon 2015 day 2 plenary" page 25 ?

### ISSUE THREAD

**Issue by WilliamTambellini** [isocpp/CppCoreGuidelines#286]
original :       
"ERROR, arg points to gsp', and gsp is modifiable by f"
should nt it be: 
"ERROR, arg points to gsp', and gsp' is modifiable by f"
?
cheers.

**Comment by neilmacintosh** [comment]
Actually, both are true, but the text is correct as it stands. Because gsp is a global, it is modifiable by f(). If f() does modify gsp, then gsp' would (by our definitions) be invalidated.

A different way of thinking about this is: any mutation of x automatically invalidates x' and x'' (as they describe memory reachable through, and "owned" by x).
