### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by GregUtas** [isocpp/CppCoreGuidelines#311]
The Abstract asks what you'd like your code to look like in 5 or 10 years.  In that case, it's time for macros to go.  Yet Enum.5 says, "Don't use ALL_CAPS for enumerators"--the reason being to avoid clashes with macros.  Using #define other than for #include guards is an abomination.  Maybe there are a few exceptions, but the vast majority of uses are execrable even today.

**Comment by lolisa** [comment]
I'd say macro do have bunch of good use - namely using them to generate code to reduce redundancy, and making new syntax for user-defined language construct under TMP. 
In both case boost is a well known example. 
But beyond that, I agree using macro instead of constexpr, function or something similar isn't a good idea.

**Comment by richelbilderbeek** [comment]
Sure, 'macro's are evil' ( http://www.cs.uregina.ca/Links/class-info/210/C++FAQ/misc-technical-issues.html#[34.1] ), but they do have their uses. They are to be written in uppercase. Thus avoid writing non-macro things as uppercase.

**Comment by gdr-at-ms** [comment]
The Core Guidelines are a living document that we expect to evolve taking into account the evolution of the language itself and the majority of our practices.  We are likely to revisit this issue, based on new data, in five years.
