### ISSUE TITLE
C.43 implies you should *always* define a constructor?

### ISSUE THREAD

**Issue by thecoshman** [isocpp/CppCoreGuidelines#344]
It could just be me, but [C.43](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-c43-give-a-class-a-default-constructor) reads to me like you should *always* define a default constructor. It should be "ensure a class has a default constructor", this can either be auto-generated or 'user' defined.

I think the Data example could be expanded to show how initially having only `Date(int year, int month, day);` would prevent the user in something like a vector, and how providing `Date():year{1970}, month{1}, day{1}{};`  fixes these issues.

**Comment by villasv** [comment]
> It could just be me, but C.43 reads to me like you should always define a default constructor.

Probably this guideline works in the assumption that you will have at least one user-defined constructor following [C.40](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-c40-define-a-constructor-if-a-class-has-an-invariant), hence the auto-generated default won't be there.

Otherwise, it would contradict [C.45](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-c45-dont-define-a-default-constructor-that-only-initializes-data-members-use-in-class-member-initializers-instead) which says that for member initializing only its better to just let the auto-generated constructor work.

Would be good to put this assumption in the title. I think "ensure a class has a default constructor" is a better title indeed.

**Comment by villasv** [comment]
What do you think of this, @thecoshman ?


### <a name="Rc-default0"></a> C.43: Ensure a class has a default constructor

##### Reason

Many language and library facilities rely on default constructors, e.g. `T a[10]` and `std::vector<T> v(10)` default initializes their elements.

##### Example, bad

    class Date { // BAD: no default constructor
    public:
        Date(int dd, int mm, int yy);
        // ...
    };

    vector<Date> vd1(1000);	// default Date needed here
    vector<Date> vd2(1000, Date{Month::october, 7, 1885});	// alternative

There is no "natural" default date (the big bang is too far back in time to be useful for most people), so this example is non-trivial.
`{0, 0, 0}` is not a valid date in most calendar systems, so choosing that would be introducing something like floating-point's NaN.
However, most realistic `Date` classes has a "first date" (e.g. January 1, 1970 is popular), so making that the default is usually trivial.

##### Enforcement

* Flag classes without a default constructor

**Comment by JaminGrey** [comment]
The guideline as written seemingly contradicts C. 45. Experienced C++ users know otherwise, but if the guidelines are targeted towards beginners, C.43 should explicitly mention making MyClass() = default; if your constructor is only initializing values.

**Comment by thecoshman** [comment]
You probably could get away with always explicitly stating your class should have a default constructor, I don't think explicitly stating it changes that constructor (presuming you haven't done something that would normal prevent the default constructor being provided). But that sort of encourages people to be ignorant and not understand why they need it, and we should be aiming to remove the smoke and mirrors.

@villasv I think that your updated rule is looking good there, but should also have a proper 'good' example, with constructor such as 

    Date():year{1970}, month{1}, day{1}{}

And yes, really month should be an enum thus preventing any arguments about it being zero or one indexed, but that's another debate.

**Comment by JaminGrey** [comment]
The proper default constructor would be: `Date() {}`
Which is `Date() = default;`

Though stylistically, I like ignoring explicit constructors for PODs.

The initialization should be preferred in the members themselves, otherwise you have to remember to initialize each variable for every constructor (or else chain constructors), and may forget one.
```
class Date
{
public:
     //...
private:
    year = 1970;
    month = 1;
    day = 1;
};
```

**Comment by BjarneStroustrup** [comment]
I have added a note about default initialization and modified the Date example as suggested.
