### ISSUE TITLE
C.35 == C.127, C.67 == C.130, ...

### ISSUE THREAD

**Issue by cdkrot** [isocpp/CppCoreGuidelines#410]
C.35 and C.127 are the same.

Consider merging.

**Comment by cdkrot** [comment]
C.67 and C.130 are also about the same things.

**Comment by cdkrot** [comment]
C.150 and C.151 are almost identical, and the title of C.150 claims to include C.151 too.

**Comment by cdkrot** [comment]
C.161 and C.86.

**Comment by cdkrot** [comment]
R.2 is an example in P.6

**Comment by cdkrot** [comment]
R.3 and I.11

**Comment by cdkrot** [comment]
I.2 and R.6

**Comment by cdkrot** [comment]
R.22, R.23 and C.150, C.151

**Comment by cdkrot** [comment]
ES.9 and Enum.5: merge them.

**Comment by cdkrot** [comment]
ES.103 and ES.104: better to be merged.

**Comment by cdkrot** [comment]
T.81 and C.152

**Comment by cdkrot** [comment]
SL.50: "Apart from the (occasionally important) issue of performance, the choice between "\\n" and endl is almost completely aestetic"

In case of the terminal output. If output stream connected to file this makes a huge difference, because flush is slow....

**Comment by villasv** [comment]
I've seen the adms commenting that some duplication is intentional, don't know to what extent though.

**Comment by andyprowl** [comment]
[Here](https://github.com/isocpp/CppCoreGuidelines/issues/354#issuecomment-153485588) Bjarne mentions that duplication is intentional - at least to some degree.

For the record, I do not like this. It complicates maintenance, as is often the case with redundancy. If these guidelines are meant to be read as a book, perhaps it would be more sensible to devise a tool that processes the raw information and presents it like a book. 

My personal opinion is that the source should be free of redundancy.

**Comment by BjarneStroustrup** [comment]
We don't particularly like duplication, but many people read sets of related rules, rather than all the rules. People don't always follow cross references. We care more for readers than for maintainers (being the maintainers, we can says that). We considered alternative organizations, such as several groupings of rules pointing to or including unique rules. We rejected that approach partly out of a desire not to rely on non-common tools. We will review the sets of rules regularly.
