### ISSUE TITLE
Suggestion: when using a library, follow its philosophy, instead of your own

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#492]
Edit: Thanks @galik for correcting me!
Edit: More focus on the word 'framework', thanks to @galik

# ?.1: when working within a framework of a library, follow its philosophy, instead of your own

**Reason**: 

The C++ Core Guidelines give a set of general rules. Existing libraries may have different philosophies (and good reasons for this). When within a framework of a library, follow its philosophy, instead of bending it to follow your own (or the C++ Core Guidlines its) guidelines. Doing so will increase your productivity.

**Example**s:

**_memory management**_

The STL supplies the std::unique_ptr and std::shared_ptr for memory management.
The Qt library facilitates a parent-child architecture, in which a parent deletes it children.

When writing your own Qt class (a class that inherits from QObject), stay within that Qt framework: instead of using STL smart pointers (for example, `std::shared_ptr`), use the Qt mechanism instead (for example, `QSharedPointer`).

**_signal-slot mechanism**_

The Boost libraries have a library (Boost.Signals2) to implement a signal-slot mechanism.
The Qt library has a custom own signal-slot mechanism.

When writing your own Qt class (a class that inherits from QObject), stay within that Qt framework: instead of using Boost.Signals2 classes, use the Qt signal-slot machanism.

**Alternative**s: 

**Exception**s: 

**Enforcement**: 

**See also**s:

**Note**s: 

The libraries given in the examples are just examples.

**Discussion**:

**Comment by galik** [comment]
This confused me at first because I wondered how do you select which of the libraries to follow the philosophy of? Why does `Qt` win over `boost`? But I think maybe your point is to follow the philosophy of the **framework** you are using when integrating code into that **framework**? Otherwise how to select between libraries philosophies when using multiple libraries?

**Comment by richelbilderbeek** [comment]
Thanks @galik for correcting me! I edited the original message.

**Comment by AndrewPardoe** [comment]
This is good advice in general, but maybe not for the Core Guidelines. It's counter to the rest of the Guidelines to recommend a particular style just because it's the locally preferred style. It may be the right thing to do, if even temporarily, but not something we can recommend in the Guidelines.

**Comment by hsutter** [comment]
I think this is good but redundant for two reasons: First, it's already necessary to follow a framework's conventions (whether they are modern or not). Second, the Guidelines already recommend "good conventions" to follow. -- Implicit in those two things is the guidance we would give, "follow the good modern conventions, but wrap/adapt it as needed to work with what the existing code requires." I think leaving that as implicit is sufficient rather than writing it more explicitly than we already do (e.g., in places like Con.2).
