### ISSUE TITLE
C.121: Recommend protected destructor for interfaces?

### ISSUE THREAD

**Issue by hpenne** [isocpp/CppCoreGuidelines#524]
I like the technique from C.35 of using protected destructors to prevent destruction of pointers to base (for cases when such prevention is what you need).  It seems to me that this would be an ideal technique for interfaces.  Wouldn't it be a good idea to recommend protected destructors for interfaces in C.121, instead of the public virtual destructor that the example uses now?

That would prevent clients from destroying a service by calling delete on a pointer to the service's interface.  It would probably also prevent clients from putting interfaces into smart pointers (you should not own a service through it's interface).

**Comment by Pazns** [comment]
I'm not really sure I see the point of this "protected destructor" practice. I probably missed something.
Can someone give me an example ?

**Comment by hpenne** [comment]
Imagine you have an interface A and a class B that implements the interface.  If you declare a public virtual destructor in A, then client code that holds a pointer to the interface will be able to call delete on the pointer to the interface.  That will result in the destruction of the implementation.  This is bad, as the client code does not own the implementation, it only holds a pointer or reference to the interface, and the implementation will be owned by other code.  Generally, you never own an implementation through an interface.

Making the destructor of A protected prevents client code from calling delete on the interface A, as the destructor of A is not visible.  It will however be visible to the implementation B, so the owner of B will be allowed to call delete on that (B will have a public destructor).

This is very different from normal polymorphism, where the destructor of a super class needs to be virtual to ensure that resources of sub classes are properly cleaned up when someone calls delete on a super class.

Making the destructor of an interface protected has two advantages:
- It prevents accidental deletion of an implementation by clients (non-owners).  This will be enforced by the compiler, no static analysis necessary.  In fact, I think the compiler will also prevent developers from putting the interface in a shared_ptr or unique_ptr.  This is also good, as these imply ownership and are thus inappropriate for interfaces.
- The protected destructor can also serve as a sign to the reader that the class is an interface and not a "normal" base class in a class hierarchy.  I don't really see any other cases where a protected destructor makes sense (although that does of course not mean that such cases do not exist).

C++ lacks interfaces like Java and C# etc. have.  If C++ had interfaces then I think the standard would prohibit delete operations on them, as access to an interface should never imply ownership of the implementatio.  Making their destructors protected achieves the same thing.

**Comment by Pazns** [comment]
Hm, okay, I see.

But, is this really what we want *everytime* ?

**Comment by hpenne** [comment]
When what you are declaring is an interface, then yes I think it is. I
reserve the right to be proven wrong, of course. :-)

**Comment by hpenne** [comment]
In fact, one could perhaps turn this around and propose that one adopts the convention that an abstract class with no data, only pure virtual member functions, and a protected destructor is the very definition of an Interface in C++

It defines only a public interface, has no data and no implementation and has the (for an interface) extremely useful property that it cannot be deleted.

**Comment by Pazns** [comment]
I'm not sure ; the destruction is a very important part of an object life.
Cases where something can not be destroyed are rare.

**Comment by hpenne** [comment]
You may be missing the point. Consider my A and B example above. There are
two class definitions, but only one object. It can be destroyed by calling
delete on a pointer of the sub class (implementation) type, but not through
a pointer to the interface type. That is precisely what well behaved code
will want to do, and by declaring the interface type's destructor
protected, the compiler will enforce it for us.

**Comment by galik** [comment]
Sometimes the caller wants to own a resource without knowing its specific type. I don't see how this rule covers those cases. Making the base destructor protected forces the author of the implementation to be responsible for its deletion which puts the responsibility back on to client code to hand the pointer over to be deleted. Isn't that as bad as calling `delete` manually?

**Comment by villintehaspam** [comment]
IMHO, whether or not a class hierarchy should be deletable through a pointer to base is part of the interface, i.e. the designer needs to decide what the use case is. In some cases you absolutely want that, in other cases you don't. I do not think that there should be a general rule recommending one or the other, at least not without further clarifications. Your assumption that client code will not own something just because it only holds a pointer to an interface does not hold in general. So I would recommend declining this proposed rule.

**Comment by hpenne** [comment]
I think the key point in this discussion is what we mean by the term "interface".  I tend to define "interface" like in C# and Java.  To me, an interface provides a named collection of callable methods to clients, but no ownership.  If there is ownership then the class is a base class, but not an interface.  Others might see this differently, of course.  This would be an interesting discussion in itself.

Java and C# have interfaces, but as those languages have garbage destruction they do not need to define the ownership semantics for interfaces.   In C++ we need to be specific about ownership, and the use of a protected destructor is one way of doing that.

I see that the Cpp Core Guidelines uses the term "interface" very broadly to mean just about any contract (any single function or collection of functions, whether they are classes or not).  Perhaps my definition is more specific than the one currently used by the Guideline.

However, C.121 talks about a base class "used as an interface".  It then goes on to say that the class should have a virtual destructor.

Many, perhaps most or even all, interface classes do not intend to allow client code ownership of the object.  The text in C.121 current seems to require a public virtual destructor, even though the protected destructor technique from C.35 would be much better for the common case where an interface does not provide ownership, as this would make the non-ownership explicit and enforced.

Even if protected destructors is not made mandatory for interface classes, it seem very unfortunate to let C.121 stand as it is, when it recommends (or even requires, depending in interpretation) a type of destructor that is less useful than the alternative for most cases.  It should at least refer to C.35 and mention that a protected destructor is recommended for cases where the interface does not provide ownership to the client.

The genius of the two alternative destructors of C.35 is that they provide a way to communicate ownership, and even enforce this ownership using the compiler.  C.121 should take advantage of that.  It currently seems oblivious to C.35, which is very unfortunate.

**Comment by galik** [comment]
@hpenne  It seems to me that you are *defining* the term *interface* to include *non ownership* as part of the *definition*. It would seem, then, that we disagree only on terminology. I accept what you are proposing a *one* possible methodology that utilizes *pure virtual base classes*.

**Comment by hpenne** [comment]
@galik Agreed.  Terminology is important, though.
The term "interface" is used very broadly in the Guidelines, but perhaps in a more specific way in C.121.  For my original idea to work, perhaps one would need to make a more narrow definition, and perhaps give this a separate name, like "interface class".  This definition would need to include non-ownership to allow a rule to mandate a protected destructor.

That would work very well in my opinion.  Others may disagree, of course.  I only offer the suggestion, it is not for me to decide.

Still, would you not agree that the current text in C.121 is suboptimal?  It does recommend a type of destructor that is wrong for many or most interfaces (at least interface classes).  A lot of interfaces are non-owning, and C.121 recommends the type of destructor that is right for object that clients own, and wrong for non-owning interfaces.

**Comment by villintehaspam** [comment]
@hpenne: I would agree that C.121 could refer to C.35 to nuance things a bit. I agree with you that an interface does not necessarily need to include a public virtual destructor (i.e C.35 trumps C.121) and that the current wording does seem to imply that it should always have one. (In addition, the destructor is incorrect in the example).

I do not believe that it is a good idea to add a specific name for "non-owning interface classes", but like yourself I reserve the right to be proven wrong/be persuaded of something else of course.

**Comment by Pazns** [comment]
Wrong or right, it is tightly coupled to the goal of the developer.

Here, your proposition depends a lot on the context, and restrain the very natural way multiple inheritance and polymorphism work.

**Comment by galik** [comment]
@hpenne 

> "This definition would need to include non-ownership to allow a rule to mandate a protected destructor."

There I have to disagree. I don't see the need. It seems you are creating a definition that suits your specific purpose.

To me an *interface class* is a class that defines the exact terms in which the object may be addressed entirely separated from any implementation details.

In `C++` one might express it like this:
```cpp
struct Interface
{
    virtual void method_1() = 0;
    virtual void method_2() = 0;
};
```
The only caveat with this is that many uses for an *interface class* in `C++` require at least one *implementation detail* to be present in order to make the *interface class* function properly.

So typically the above might be defined:
```cpp
struct Interface
{
    virtual ~Interface() {} // necessary implementation detail
    virtual void method_1() = 0;
    virtual void method_2() = 0;
};
```

I have a some major use cases that involve client code *owning* an object without knowing its exact type. I don't want to abandon the terminology "*interface class*" simply because other cases use *interface classes* differently.

I think it is better to keep the definition more general to facilitate the various legitimate use case scenarios that need that the terminology to express their ideas.

To my mind the territory you are embarking on is more *object design methodology* and in a given *design methodology* I think it is perfectly reasonable to stipulate that *interface classes* should be implemented using a `protected` destructor. But at the end of the day the *destructor* is an *implementation detail* and different situations need to it to be *implemented* differently.

I suppose all I am saying is keep the term *interface class* to express the concept of *interface* **only** and leave *destructor implementation* details to be determined by whatever *design methodology* is being employed.

Maybe something could be written in the guidelines mentioning the relative benefits of *public* vs *protected* destructors. But there is the danger of turning the guidelines into a "howto" on Object Design that is perhaps beyond the scope of the mission. 

> "Still, would you not agree that the current text in C.121 is suboptimal? It does recommend a type of destructor that is wrong for many or most interfaces (at least interface classes)."

I don't know the relative usage numbers for on how projects are using *interface classes* and I am not an expert on all the various *object design methodologies* out there.

However I actually think the advice is good because it works in **all cases** and doesn't get involved in a lot of detail about object design. If you changed it to specify a `protected` destructor then it would not work for a lot of things people are using *interface classes* for.

Perhaps your *specific* use case could/should be mentioned? My own feeling is that these guidelines are already a little too detailed with a lot of *ifs and buts* that are probably better addressed through books dedicated to the specific subject.

And my *suspicion* is that telling people to add a *virtual destructor* saves a lot of bugs whereas telling them when to make the destructor *protected* saves relatively few bugs and at the cost of a lot of explanation.

But, like I say, I don't consider myself an expert and I would be interested in what the guideline maintainers have to say.

**Comment by BjarneStroustrup** [comment]
public virtual destructors is a tried and true technique

**Comment by hpenne** [comment]
Tried and true? Yes, definitely.  Appropriate in all cases?  I respectfully disagree, and C.35 seems to support that view.

I agree with @galik that defining the term "interface class" as non-owning is probably going a bit too far.  Thinking about it, it is also unnecessary.  The benefit can be achieved simply through adjusting C.121 to advise the developer to use the choice between public virtual and protected non-virtual to make it clear to the user of the class what the ownership rules for the class are.  As C.121 stands now, we're missing a good opportunity.

@BjarneStroustrup, I think C.35 applies to C.121 and that this kind of (minor) update/clarification of C.121 will both achieve consistency with C.35 and help make ownership explicit and enforceable.  That does not mean that public virtual destructors are wrong.  Just perhaps not the optimal solution in all cases.  Please have another think about this.

**Comment by avakar** [comment]
I'm a bit late to the party, and realize that no maintainers are probably going to read this; still I'd like to give some support to you, @hpenne.

The problem with virtual public destructors in interfaces is the coupling of two separate concerns -- the function the interface is supposed to provide and the lifetime management of the object that provides the interface.

This coupling is a non-issue most of the time, since ending the object's lifetime usually only involves `delete obj` and our objects are well prepared for it. In more complex scenarios however, in which for instance you also want to release a shared library when the object dies, these couplings introduce problems that can only be fixed by [ugly hacks][1].

  [1]: https://msdn.microsoft.com/en-us/library/windows/desktop/ms683153(v=vs.85).aspx

We'd be better off having protected destructors in interfaces and passing `shared_ptr<my_interface>` objects around, however tried and true the other approach is.

**Comment by Pazns** [comment]
What is the link between this "coupling issue" and your example case ("release a shared library when the object dies") ?

**Comment by hpenne** [comment]
Thanks to everyone who contributed to an interesting discussion, and to @galik in particular who really seemed to understand the issue.

My original idea was probably taking things a little too far, but I believe that the idea of harmonizing C.121 with C.35 by mentioning that the type of destructor should be chosen according to ownership policy has a lot going for it.  Or one could simplify C.121 by removing all talk of destructor types in C.121 and refer the reader to C.35 instead.  As C.121 current stands, it contradicts C.35 (and C.35 is much better advice in many cases).

Too bad the discussion was terminated early.  It would seem that my time is probably better spent elsewhere, so I'll be leaving.

"So long, and thanks for all the fish".

**Comment by Pazns** [comment]
> It would seem that my time is probably better spent elsewhere, so I'll be leaving.

That is a silly thing to write. The very existence of this discussion proves that your time was not so badly spent.

Maybe try to open a new subject with a simpler, more precise, request like this : 
"Make C.121 references C.35 on the Destructor matter in the case of interfaces."

**Comment by avakar** [comment]
@Pazns,

> What is the link between this supposedly coupling issue and your example case ("release a shared library when the object dies") ?

if you have

    struct my_interface {
        virtual ~my_interface() {}
        virtual void foo() = 0;
    };

and an object `obj` implementing that interface that lives in a shared library, calling

    delete obj

will not be able to unload the library. Objects cannot unload libraries they live in. If on the other hand you have

    struct my_interface2 {
        virtual void foo() = 0;
    };

and a `shared_ptr<my_interface2>`, you can have `foo` live in the library and the shared_ptr's deleter in the caller's module. This way, the deleter can unload the library after freeing the object.

The point is, by separating the main functionality of the interface from object's lifetime management, you get more flexibility. This is nothing world-shattering, the concept of [separation of concerns][1] has been around for ages. It's just that up until recently we didn't have the tools (shared_ptr in particular) to do it conveniently and our minds became used to seeing destructors in interfaces. Now that the tools are in place, we might want to start changing our minds about this.

  [1]: https://en.wikipedia.org/wiki/Separation_of_concerns

**Comment by hpenne** [comment]
@Pazns I appreciate your honesty.  I did consider what you suggest, but the argument used to close this issue would apply equally to such a new request.  @BjarneStroustrup seems to be against using protected destructors in abstract classes used as interfaces, and if so then there really does not seem to be any point in pursuing this any further.

**Comment by tiagobonetti** [comment]
This discussion was very elucidating on the on the relation of ownership and interfaces; I was trying to force a non owning interface and @hpenne described exactly what I want.  
Since it seem that standard practice that interfaces can be owning I'm moving forward in my projects using `view` as a shorthand for a non owning `interface`.
