### ISSUE TITLE
overloading operator `<`

### ISSUE THREAD

**Issue by vladon** [isocpp/CppCoreGuidelines#532]
Can we add the guideline that in overloading operator `<` or in comparison predicate (for example for standard sorting algorithm) the overloaded operator or the predicate must return `true` for equal values (not `false`)? It is non-intuitive (equal left *not* less than right), but it must return `true` for them.

**Comment by gdr-at-ms** [comment]
You want ` 2 < 2` to evaluate `true`?

**Comment by galik** [comment]
Can you the reasoning behind this?

I would have thought returning `<=` instead of `<` would make sorting *less* efficient causing *equal* values to be swapped *in addition* to all the genuinely *less than* values.

Furthermore how will *algorithms* detect `==` based solely on the *less than* operator? It seeme they can currently do `if(!(a < b) && !(b < a))` which means only the *less than* operator is required to be defined.

**Comment by vladon** [comment]
My fault, didn't sleep good, sorry :-)
