### ISSUE TITLE
I.6: Prefer Expects() for expressing preconditions

### ISSUE THREAD

**Issue by koja** [isocpp/CppCoreGuidelines#539]
I was interested in advices I.5-I.9 about pre/post-conditions and unfortunately I am not able to understand the reasoning behind I.6. My usual strategy about pre/post-conditions is to design suitable interface, use proper types for arguments and return values and document everything else and I am comparing the advice to best practice I currently know about.

Maybe I am confused by the example:

```
int area(int height, int width)
{
    Expects(height > 0 && width > 0);            // good
    if (height <= 0 || width <= 0) my_error();   // obscure
    // ...
}
```

My first thought was that there are incorrect types in interface (low level without guarantees) and would look for solution in a direction of type with invariant:

```
struct ExceptionNegativeOrZeroInt {};

struct PositiveInt {
    PositiveInt(const int i)
    :   i_(i) 
    {
        if(i_ <= 0) { throw ExceptionNegativeOrZeroInt(); }
    }

    const int i_;
};

int area(NonNegativeInt height, NonNegativeInt width);
```

I don't think `Expects()` is needed there. It is definitely possible to be used but not necessary.

I would be grateful if someone knowledgeable could enlighten me.

**Comment by MojaveWastelander** [comment]
In my opinion all these are wrong because essentially they hide the problem.
Let's start with first example:
```
int area(int height, int width)
{
    Expects(height > 0 && width > 0);            // good
    if (height <= 0 || width <= 0) my_error();   // obscure
    // ...
}
```
What exactly does negative width and height means? The width and height should be unsigned as they represent unsigned quantities, in which case the check for preconditions is not needed and it goes to postconditions:
```
int area(int height, int width)
{
    auto res = height * width;
    Ensures(res > 0);
    return res;
}
```
The postcondition here is wrong for height and width equal to numeric_limits<int>::max(), still the problem in this cases is not with the postconditons but the fact that the function accepts overflow for area calculation, meaning that according to above area <= numeric_limits<int>::max() is acceptable, but anything higher is wrong. Solution for this case might be to use a type that fits the whole height * width range. My advice is to not hide overflows behind "use int instead of unsigned int", but to use bound_integers in case overflow is an error or types that would fit results if whole output range is required.

**Comment by jwakely** [comment]
> What exactly does negative width and height means? The width and height should be unsigned as they represent unsigned quantities, in which case the check for preconditions is not needed 

But now if you subtract two widths then instead of a negative value (which can be caught by preconditions and checks for negative values) you get a huge unsigned number, which can only be caught by checking for some arbitrarily large "this is too big" value.

This is covered in [ES.102: Use signed types for arithmetic](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-signed)

**Comment by AndrewPardoe** [comment]
Per our editors' discussion, `unsigned` is not a solution as @jwakely comments above. We should add the references to ES.102 and ES.103 in this item.

**Comment by BjarneStroustrup** [comment]
Ref to ES.102 added.
Whether to have a Nonnegative or Subrange type in the GSL is a separate question.
