### ISSUE TITLE
E.27 could incorporate F.21

### ISSUE THREAD

**Issue by SaintDubious** [isocpp/CppCoreGuidelines#568]
E.27 suggests using a pair to incorporate error code and msg, but also highlights that "first" and "second" aren't very descriptive. F.21 suggests using a tuple instead of returning a pair. Perhaps E.27 could be changed to follow the advice of F.21?

**Comment by galik** [comment]
Sounds like this may be relevant: https://github.com/isocpp/CppCoreGuidelines/issues/364 (suggests returning a `struct`.) I agree that `std::pair` is not very descriptive, but *tuples* are even less descriptive. I think currently `F.41` suggests either a tuple or a struct.

**Comment by SaintDubious** [comment]
Thanks for the reference, that discussion is very interesting. I think the use of tuples and tie is _neat_, but I can see that it might not be good for writing maintainable code. I still think E.27 should be updated to follow the advice of F.21.... when that advice is fully agreed upon.

**Comment by galik** [comment]
Hah! I deleted my post because I realized that `F.41` is now `F.21` so you already were referencing the relevant rule that I was thinking of. I forgot the discussion may be interesting to others so I'll put the link back in here: https://github.com/isocpp/CppCoreGuidelines/issues/364

I'm still trying to figure this stuff out having previously been a fan of using *out parameters* with either a `bool` or other error/status return value. So now I am looking at how to organize code around the idea of always returning the value. I still favor `struct` as I would rather do a little more typing to create a function to make life a little easier using it. But this is all still a little experimental for me.

**Comment by AndrewPardoe** [comment]
Per our discussion, we have multiple reasons to keep these separate. Primarily, the topics are different. Out parameters represent work that is done--this is an item about returning multiple values. Error handling represents work that is failed to be done. Secondarily, we try to not eliminate rules as people do deep link into the rules. 

Per the original comment, a `pair` is a `tuple`. F.21 uses `pair` in an example.

**Comment by hsutter** [comment]
I did push a commit to add a note in the F.21 Reason that `pair` is a `tuple`, just so it's nearer the top of the item.
