### ISSUE TITLE
C.129 and C.136 are harmful

### ISSUE THREAD

**Issue by jonathantims** [isocpp/CppCoreGuidelines#578]
For C.129 I agree with a commenter (called Herb) who believes implementation inheritance is an anti-pattern and that tacitly approving its use is damaging.

I think that implementation inheritance is the sort of pattern that requires an apology in code, is sometimes required; for example, “/\* base class provided because this interface we’re stuck with is horrible to implement correctly and using this base class takes away most of the pain */”. But certainly recommending its use seems wrong.

Similarly for C.136

**Comment by borissmidt** [comment]
Maybe it could be usefull to wrap some new functinality to a struct? 
for example you have a protocol struct (all with public variables) and you have multiple types of packadges. So then you could write a header struct and extend it to the protocol structs for each type of message. Then you could write 

```
protocol_type1.length 
protocol_type2.length 
```

Instead of creating a composite of a body struct and header struct 
where you would get .
```
protocol_type1.header.length 
protocol_type2.header.length 
```
I think the inheretance struct could be fully packed with compiler extentions while the composition cannot be packed. (i.e. no padding) 

a more complex example which would be better solved by making an abstract base class or a composition but might require more work.
You have created a 2D game and want to extend it to a 2.5D game. which is just a 2D game but with multiple layered in discrete planes.
So then you could extend the 2D library. So then you could just extend most classes to a 2.5D class.
For example you could just extend the 2D point class to a 2.5D point class which will have a new int which defines you layer. The 2.5D class could reuse all the functions from the 2D point.  
Then you have to extend the collision detection aswell. 
This extended collision detection would then check if both points are on the same plane and call its parents function as if they where 2D points.   
The main benefit is that you could then reuse most game code as if it was doing 2d logic.

**Comment by neilmacintosh** [comment]
Regarding C.129: it would be overkill to describe implementation inheritance as an anti-pattern. Like many techniques that have been abused or overused, it does have valid uses (especially in "classic" object oriented designs). If a particular codebase wants to avoid a specific technique Iike this, then that's a localized design choice.

I think the item actually does a good job of describing both the benefits and shortcomings of the technique. I certainly don't think it recommends the technique. As the title explicitly states: it just recommends being clear about what the technique is and when it is being used.

Regarding C.136: This item does more explicitly talk about choosing to use implementation inheritance. However, as you observe, there is an active discussion occurring there currently.

I'll ask @BjarneStroustrup  to take a look at C.136 and follow-up to the comments from @hsutter so that we resolve whether the item should stand as-is (but get some content added), be modified or removed.

**Comment by hsutter** [comment]
FWIW my note is in C.136, not in C.129.

I'm okay with C.129 as is.

For C.136, do consider: (a) that item isn't even written yet, (b) its lone sentence acknowledges it will be rare, and (c) I think it's reasonable to be most leery of all of *multiple implementation* inheritance.

Having said that, I'm happy to go either way. I would suggest one of the the following two resolutions:

Resolution 1: Remove my note but also actually write up C.136 with at least brief guidance and a "good" example.

Resolution 2: Remove my note along with the rest of stub item C.136.

**Comment by AndrewPardoe** [comment]
Discussed, will leave with Bjarne to flesh out the item and remove Herb's note.

**Comment by cubbimew** [comment]
Regarding a potential "good example" for _C.136 "Use multiple inheritance to represent the union of implementation attributes"_, would `std::enable_shared_from_this` or various bases from boost.intrusive (e.g. `list_base_hook` or `intrusive_ref_counter` work as an example?

Co-inheriting from such bases in addition to whatever class hierarchy dictates is not really a "union of implementations", it's more like a trait/policy that happens to inject data members, but it is still multiple implementation inheritance.

**Comment by hsutter** [comment]
Nice -- IMO that's a convincing example. Thanks.
Bjarne, when you write this up please remove my note and include that nice example. Thanks.

**Comment by BjarneStroustrup** [comment]
Added cubbimew's example to C.136
