### ISSUE TITLE
C.120 harmful?

### ISSUE THREAD

**Issue by jonathantims** [isocpp/CppCoreGuidelines#580]
Because it emphases mapping of “ideas” and “concepts” onto a class hierarchy. I have never seen an example where this was beneficial; and I’ve seen many examples where it made a codebase much worse by coupling structures that represented mathematically-related things, while being unrelated (or not usefully related) within the code.

**Comment by MikeGitb** [comment]
Can you give an example of such a case? Maybe something that could be added to the **Example, bad** section?
While the text mentions the mapping of ideas and concepts, it also presents additional restrictions, so maybe they already cover those cases and only need more emphasis.

**Comment by AndrewPardoe** [comment]
Once we have formalized a domain, it may be regular enough to be expressed in a hierarchy. Maybe we should have a "good" example as well. Possibly a GUI example?

**Comment by lbrandy** [comment]
Just to be clear though, as stated, this issue seems to be written to contend that there are no good examples of inheritance hierarchies? 

I'm happy to write a small (relatively canonical) example that is as uncontroversial as I can, but I'm not sure we want to go as far as saying "all inheritance hierarchies are bad".
