### ISSUE TITLE
FAQ.55 is now outdated

### ISSUE THREAD

**Issue by cubbimew** [isocpp/CppCoreGuidelines#583]
FAQ.55 says

> string_view in the Library Fundamentals 1 Technical Specification?

and

> Because string_view is still undergoing standardization, and is in a state for public review input to improve it. Types that appear in Technical Specifications (TSes) are not yet part of the International Standard (IS)

`std::string_view` is now part of the ISO C++ standard working paper.

> a discussion of the differences between string_view and string_span, as a paper for the next ISO meeting for consideration

If that is referring to http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0123r1.pdf , it is a proposal (it has wording) rather than than just a discussion piece at this point.

Perhaps this FAQ could say something like 

The consensus on the taxonomy of views for the C++ standard library was that "view" means "read-only", and "span" means "read/write". The read-only string_view was the first such component to complete the standardization process, while span and string_span are currently being considered for standardization.

**Comment by AndrewPardoe** [comment]
Agreed. @cubbimew, can you write this as a PR?

**Comment by jimvonmoon** [comment]
Sorry for digging up this old issue, but if `std::string_view` is read-only, and `gsl::string_span` is read-write, then what is the purpose of `gsl::cstring_span`?

**Comment by johelegp** [comment]
`std::string_view`'s API is consistent with that of `std::string`'s and is supposed to be a common ground to all strings. `gsl::cstring_span` is an arbitrary array of characters. For example, you could have a view to a buffer with the latter, but not with the former.

**Comment by MikeGitb** [comment]
As far as I remember, the Idea behind  `gsl::cstring_span` was very similar to `std::string_view` and if you really just want to refer to an arbitrary array of characters I'd strongly recommend to use `gsl::span<const char>` instead. 
Aside from the differences in the API, a notable property of `gsl::cstring_view` is that each operation (including de-referencing an iterator) is bounds checked.

**Comment by jimvonmoon** [comment]
@MikeGitb
>As far as I remember, the Idea behind gsl::cstring_span was very similar to std::string_view and if you really just want to refer to an arbitrary array of characters I'd strongly recommend to use gsl::span<const char> instead.

That's what I would imagine. `gsl::cspan<char>` seems more suitable for character arrays/buffers.

>Aside from the differences in the API, a notable property of gsl::cstring_view is that each operation (including de-referencing an iterator) is bounds checked.

Nice, I didn't know about bounds checking.

@johelegp 
> For example, you could have a view to a buffer with the latter, but not with the former.

Wouldn't that work?

    char buffer[10];
    std::string_view my_view{&buffer, sizeof(buffer)};

A similar example can be found here: http://en.cppreference.com/w/cpp/string/basic_string_view/basic_string_view

Right now I can think of following classes for wrapping strings:
- `std::string_view` (and its variants, e.g. `std::wstring_view`)
- `gsl::string_span` and `gsl::cstring_span` (and their variants)

FAQ.55 explains `std::string_view` and `gsl::string_span` (as in immutable vs mutable), but it leaves out `gsl::cstring_span`, which is also an immutable string view. I would be very interested in a bit more precise guidelines on when to use which wrapper.

My current understanding of them right now is:
- Use `std::string_view` where you would previously use `const std::string&`.
- Since `gsl::string_span` is the only mutable wrapper then it's a no-brainer when to use it. There's no alternative when we want to change a viewed string.
- `gsl::cstring_span` is still a bit of a mystery to me. At a first glance it looks like it duplicates some of `std::string_view`'s functionality. Bounds checking is a nice touch though.

Thanks for explanation, guys. I would be very interested in further guidelines on the topic.

**Comment by johelegp** [comment]
I said that `gsl::cstring_span` is an arbitrary array of characters, but that's `gsl::span<const char>`. Sorry, I got that wrong.
```C++
char buffer[10];
std::string_view my_view{&buffer, sizeof(buffer)};
```
You're getting a view over uninitialized memory. `std::string_view` should only be used for array of characters that conceptually are a string (contiguous characters with some meaning.) The same applies to `gsl::string_span` and `gsl::cstring_span`. The correct choice in this case would be to use `gsl::span<char>` to initialize the memory before using a string wrapper.

Here's part of the [`string_span` proposal](http://wg21.link/p0123) on `std::string_view`:
> _basic_string_span_ is presented as complementary type to the _basic_string_view_ of N3762 [1]. Each fulfills an important but different aim. _basic_string_view_ focuses on compatibility with the interface of _basic_string_ and support for null-termination. _basic_string_span_ is explicitly not null-terminated, and
provides a simpler interface that is closer to a “view over a sequence of characters” model.
