### ISSUE TITLE
F.27 and asynchronous programming

### ISSUE THREAD

**Issue by duneroadrunner** [isocpp/CppCoreGuidelines#606]
Regarding "F.27: Use a shared_ptr<T> to share ownership":

I've already harped enough about the unnecessary cost of std::shared_ptr in cases that do not involve sharing between asynchronous threads. Given its provided example, this rule seems to be concerned with the asynchronous threads case so I'll just address that. Since it's so short, I'll just recite the given example here:

```
shared_ptr<const Image> im { read_image(somewhere) };
std::thread t0 {shade, args0, top_left, im};
std::thread t1 {shade, args1, top_right, im};
std::thread t2 {shade, args2, bottom_left, im};
std::thread t3 {shade, args3, bottom_right, im};
// detach threads
// last thread to finish deletes the image
```

Sharing an object between asynchronous threads can be divided into two categories - one where the access is strictly read-only, and the other where it isn't. These are two completely separate categories that should not be conflated. They have very different risk profiles and call for very different safety mechanisms.

So let's consider the strictly read-only case. By far the safer of the two. But even in this case std::shared_ptr is insufficiently safe for general use. In particular it needs to disable its "get()" member, it needs to ensure that its template parameter is a "const" type, and ideally, that type would have its `&` (address of) operator disabled. Raw pointers to objects shared between asynchronous threads are bad. The mechanism used to share the object should not be one that readily provides such a raw pointer.

What I'm saying is that when you use std::shared_ptr in this case, you are relying on the programmer, and every future programmer that has to maintain the code, to recognize that it's a "strictly read-only case", and then still to use the std::shared_ptr mechanism in a safe manner. But there is no need for this reliance on the astuteness and vigilance of the programmers. You could easily construct a safer mechanism that, first of all, makes it clear that it is a "strictly read-only" situation, and, like I said, enforces "const"ness and does not so easily yield raw pointers to the shared object.

And then there's the fact that in C++, you cannot even rely on "const"ness because the type in question may have "mutable" members. So you can see how easy it could be to assume you're in a "strictly read-only" situation when you really aren't. (Static analyzers could help, but we really need an "std::has_mutable_member<>".)

So std::shared_ptr does not have nearly the safety features called for when sharing objects between asynchronous threads. Even in the ostensibly safer "read-only" case.

The non-"read only" case is of course even worse. I'm sure we can agree that std::shared_ptr is wholly inadequate for that job.

Let me make a point here about the practice of "casually" sharing objects between asynchronous threads (using std::shared_ptr or any other insufficiently safe mechanism). This is a primary source of so-called "data race" bugs. If we consider the four factors that make a bug problematic

i) frequency/unpredictability of occurrence
ii) severity of consequences
iii) difficulty in reproducing/debugging
iv) ability to evade detection during testing

we note that "data race" bugs are the worst bugs in all of computer programming. The worst. So if there's any situation that calls for prudence and abundance of safety mechanisms, this is it.

But these guidelines, as they currently stand, actually encourage the practice of "casually" sharing objects between asynchronous threads. Now this may sound a bit extreme, but in my opinion, this alone makes these guidelines, in their current form, a net detriment to the practice of coding. Imo, there is no amount of good that these guidelines could do that would make up for even the implicit condoning of the practice. It's a little harsh, but imo, that's the situation.

...

But more than just these technical issues, I think there needs to be more thought about the whole attitude being taken with respect to parallel programming. Now, I understand the idea of wanting to take full advantage of our multi-core future (and present), but are we sure we want to encourage the practice of reflexive, habitual manual thread creation by programmers? I mean there are multiple strategies for taking advantage of multiprocessing hardware, some safer than others and some more efficient than others. 

In terms of safety, the best way, of course, is to let the compiler (or some other tool) do the parallelization for you. This is not my area of expertise, but my understanding is that there's plenty of room for improvement in the current state of automatic parallelization. But presumably there is pressure for that improvement to occur, and if these guidelines are meant to be forward looking perhaps we should be thinking more about "parallelizable" code, rather than "parallelized" code.

Even apart from safety considerations (although in the case of asynchronous programming, safety should be the overwhelmingly dominant consideration), we might want to be careful not to encourage "premature parallelization", which is just a specific case of premature optimization. 

We can step back even further and ask ourselves why are we engaging in parallel processing at all? Well, because this is C++, the answer is often to increase performance. But if we think about the priorities of today's mobile computing, users (client and server side) value:

i) security
ii) reliability
iii) energy efficiency (on battery powered devices as well as in the data center)
iv) maybe performance? maybe?

in that order. So increased performance is great, as long as it's achieved in a way that doesn't compromise the other priorities.

Ok, so back to std::shared_ptr. I actually like std::shared_ptr. I have no problem with the fact that it's the only reference counting pointer in the standard library. But it's not really appropriate as a recommendation for general use. It's unnecessarily expensive for non-asynchronous use, and it isn't safe enough for asynchronous use. I can understand wanting to pick a standard type for the sake of having a standard, but in the case of std::shared_ptr I think the compromises are a little too costly and would condemn these guidelines to be yet another burdensome legacy that C++ has to deal with instead of the step toward the better coding future we want it to be.

Noah

**Comment by galik** [comment]
I think you may be reading more into [F.27](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f27-use-a-shared_ptrt-to-share-ownership) than is intended. I don't see that example as illustrating how *multi-threading* can be safely performed. Its purely about *ownership*.

The `std::shared_ptr` is the correct *smart pointer* to share *ownership* across threads. It is **not** something that will solve your concurrency issues. Those are orthogonal to *whatever* pointer you use. Indeed, those can not be solved with a *smart pointer* of any type.

So that example is not suggesting a way to solve multi-threading issues it is purely there to solve the *ownership* issue across threads - determining which thread eventually destroys the object - nothing else.

For *that* purpose the *only* part that needs to be *thread-safe* is the reference counter.

Now with respect to *raw pointers* I could not disagree with you more. Given that no pointer *however smart* can solve the concurrency problem and given that the *ownership* problem is fully solved by `std::shared_ptr` then we should be aiming to use *raw pointers* (from a call to `get()`) as much as possible. 

The concurrency example given:

```cpp
shared_ptr<const Image> im { read_image(somewhere) };

std::thread t0 {shade, args0, top_left, im};
std::thread t1 {shade, args1, top_right, im};
std::thread t2 {shade, args2, bottom_left, im};
std::thread t3 {shade, args3, bottom_right, im};

// detach threads
// last thread to finish deletes the image
```

Each thread's `shade()` function has *one* `std::shared_ptr` that jointly manages the image's life-span. Given that we have guaranteed that the image will be released *only* after all threads have ended there is no danger in passing round *raw pointers* to processing functions that will complete within the lifetime of the thread. Or even to objects that will never outlive the thread.

The only dangerous activities to perform on a *raw pointer* are to:

**1)** delete them (we should **never** delete a raw pointer)

**2)** use them after the resource has been deleted.

Item **1)** is easily solved by ***never*** deleting a *raw pointer*.

Item **2)** can be just as problematic with *smart pointers* as *raw pointers*. Use them after they have released their object and you have a problem. But in threading examples like this they are particularly safe because the *resource* is guaranteed to outlive the *thread* by the `std::smart_ptr`.

**Comment by duneroadrunner** [comment]
Uh yeah, I don't have a problem with the intended point. std::shared_ptr can handle shared ownership across threads. Fine.

The problem is the implications being made beyond that point. Consider the following example:

    {
        shared_ptr<const Image> im { read_image(somewhere) };
        std::thread t0 {shade, args0, top_left, im};
        std::thread t1 {shade, args1, top_right, im};
        std::thread t2 {shade, args2, bottom_left, im};
        std::thread t3 {shade, args3, bottom_right, im};
        // detach threads
        // last thread to finish deletes the image
    }
    {
        shared_ptr<Image> im { read_image(somewhere) };
        std::thread t0 {shade2, args0, top_left, im};
        std::thread t1 {shade2, args1, top_right, im};
        std::thread t2 {shade2, args2, bottom_left, im};
        std::thread t3 {shade2, args3, bottom_right, im};
        // detach threads
        // last thread to finish deletes the image
    }

Did you catch the problem? The two blocks look very similar, but the second block is going to have race-condition bugs because the `shade2` function is writing to the `Image`, not just reading from it. So what I'm suggesting is that the example should instead look like this:

    {
        gsl::read_only_shared_ptr<const Image> im { read_image(somewhere) };
        std::thread t0 {shade, args0, top_left, im};
        std::thread t1 {shade, args1, top_right, im};
        std::thread t2 {shade, args2, bottom_left, im};
        std::thread t3 {shade, args3, bottom_right, im};
        // detach threads
        // last thread to finish deletes the image
    }
    {
        gsl::read_only_shared_ptr<Image> im { read_image(somewhere) }; //compile error either here
        std::thread t0 {shade2, args0, top_left, im}; // or here
        std::thread t1 {shade2, args1, top_right, im};
        std::thread t2 {shade2, args2, bottom_left, im};
        std::thread t3 {shade2, args3, bottom_right, im};
        // detach threads
        // last thread to finish deletes the image
    }

See? `read_only_shared_ptr` either enforces that its template parameter type is a `const` type, or it only provides `const` access to its target. Either way will work. (To help ensure that your shared object is not being accessed in a way you did not intend or expect.) Now, this still doesn't contradict the intended point of F.27. In fact, `read_only_shared_ptr` was probably implemented using std::shared_ptr. But the user/programmer doesn't deal with std::shared_ptr directly.

See, you're suggesting that ownership issues are independent from "multi-threading issues". But what I'm saying is that the "proper" ways to address the "multi-threading issues" will all incorporate the ownership issue, and thus hide the std::shared_ptr inside a more comprehensive type. So by having F.27 in the guidelines, you're implying that the programmer will often have to deal with `std::shared_ptr`s directly. I'm saying that if you're dealing with `std::shared_ptr`s directly you're doing it wrong. The ownership issue should be handled (by an `std::shared_ptr`) inside another type that is helping to address the "multi-threading issues".

Now, you say that "concurrency issues" "can not be solved with a smart pointer of any type". I agree that you cannot solve both race-conditions and deadlocks with any type of smart pointer (or indeed any mechanism). But I suggest that you actually can solve one of those categories (possibly at the expense of the other, and maybe some performance). And as I argued in the OP, race-condition bugs are worse so we should eliminate them (and leave the deadlock bugs to the programmers and testers). And more ambitious smart pointers and other smart types can go a long way, if not all the way, to eliminating race-condition bugs.

As for raw pointers, can someone explain the attachment to these things? You say "Item 1) is easily solved by never deleting a raw pointer." Ok, but why are we _telling_ people never to do that. Why not just enforce it by embedding the pointer in a thin wrapper type that `delete` doesn't accept? And if you're paranoid that the compiler won't optimize the wrapper out, then you can conditionally eliminate the wrapper in release mode (you know, with `#ifdef NDEBUG` or whatever).

And finally "Item 2) can be just as problematic with smart pointers as raw pointers. Use them after they have released their object and you have a problem." Ok, so this makes my point. That is true for the "already aging" smart pointers in the standard library. But you could imagine more modern "safety oriented" smart pointers that either throw an exception upon invalid dereference attempts, or more ideally, always point to a validly allocated object. That is, smart pointers that don't support "releasing their object". (And as I pointed out in the previous issue post, you [don't need](http://www.codeproject.com/Articles/1093894/How-To-Safely-Pass-Parameters-By-Reference-in-Cplu) much imagination.)

I mean, you're defending raw pointers by pointing out similar short-comings of the standard library's smart pointers. And then you're defending the guidelines' directives to standardize on these defective smart pointers.

Presumably because they are the only standard ones available? That's not really a good enough reason. I think we need to recognize that while the standard library's smart pointers may be an upgrade from raw pointers for many uses, they have significant short-comings and are suboptimal, in design and implementation, for a lot of the uses we are trying to apply them to. And imo, these guidelines should stop trying to push for them to be used in cases where other (hypothetical in some cases) smart pointers would be more optimal. Now this might gut a large portion of these guidelines, so maybe we should take a step back and try to unambiguously identify what exactly it is we are trying to achieve with these guidelines. And whether this "ownership" concept is really the only relevant factor in choosing a smart pointer implementation. (Hint: It's not.)

**Comment by galik** [comment]
I think F.27 is (and should be) only concerned about the *ownership* problem. You seem to feel we need to teach about solving the concurrency problems at the same time. I believe that over-complicates things. 

There are many different scenarios with different optimal solutions to the concurrency problem so wouldn't that be better dealt with in the concurrency section?

I don't see the value in using that example to suggest that some of the concurrency problem could be solved with a  different smart pointer. If the programmer wants to solve it by writing a different smart pointer then great, they can do that using the advice and techniques found in the section dealing with *concurrency*. It just doesn't really make sense to me to provide examples using hypothetical smart pointers that the programmer has to locate/write for themselves.

Also I don't see the advantage of your proposed smart pointer because the original one in the example already enforces read-only access:

    std::shared_ptr<const Image> im; // only allows read-only access

Furthermore sometimes you want to be have read-write access to the resource. The potential race conditions can't be prevented with *smart pointers*. So there is no point trying to address them in an example that is purely about *ownership*.

I do agree with you regarding the enforcement of non-null-ness. These guidelines provide for a smart pointer that does just that (`gsl::not_null`) and it is available in the support library that is being developed alongside the guidelines.

Regarding the standard library smart pointers I actually think they are very good. Together, `unique_ptr` and `shared_ptr` properly address core programming problems of *ownership*. I do think *shared pointer* gets over-used. I think a lot of people try to use *smart pointers* for everything as if they are some kind of panacea. Personally I think smart pointers should be used for as little as possible. They should *only* deal with the*ownership* problem (and maybe too the *nullable* problem). Once the ownership problem is addressed then *raw pointers* can be safely used.

I suspect if you have too many *smart pointers* each with their own particular semantics then it could be a lot more confusing for the programmer and the potential for selecting the wrong *smart pointer* for the task increases. As it is we have the two *basics* of ownership covered with *unique* and *shared* ownership. I suspect teaching how these two can be used *effectively* and *safely* is probably easier than conveying the various nuances embodied in a myriad of different *smart pointers* that each provide some niche benefit in certain situations.

**Comment by Pazns** [comment]
@duneroadrunner : 
I don't understand how `gsl::read_only_shared_ptr<Image>` resolves anything, either if it enforces at compile-time or proxies the object through `const`.

If you can easily forget to use a `const` argument with the `shared_ptr` version, why would you magically remember to use the `read_only_shared_ptr` version in case you could forget the first one ?
It is non-sense.

Regarding "It is wrong to use directly `shared_ptr`", people often say that Hiding isn't Solving.
Since C++ can't really enforce such abstract issues (as far as I understand it from my apprentice point of view), a bad dev is a Data Race Condition spawning machine, no matter what.

**Comment by duneroadrunner** [comment]
Ok, so `shared_ptr`s can ensure that the object they're providing access to is valid (in the sense of not having been deallocated) because they have "ownership" of the object's lifespan. In particular, they "own" the right to extend the object's lifespan to at least the lifespan of the `shared_ptr`. So when we're talking "ownership" here we're talking ownership of the object's lifespan. Right?

When you're providing access to an object shared among threads, and it is not a "read-only" scenario (i.e. some parties are allowed to modify the object), in order to ensure it's providing valid access to an object a (smart) pointer would want ownership of both it's lifespan and it's "access lock" (i.e. mutex or whatever). Ownership of the "access lock" in non-read-only asynchronous sharing scenarios is very analogous to ownership of the lifespan. That is, it's required to ensure that access to the shared object is valid, and, like lifespan ownership, the pointer itself doesn't have to have the ownership. I mean, the ownership could be managed on the pointer's behalf by external code. But it's just a way better idea to have the pointer itself have the ownership. I mean, the premise of `shared_ptr` is that it is just better if the pointer itself has ownership of, and manages the object's lifespan, rather than relying on external code to do it.

So the same reasoning applies in the non-read-only asynchronous sharing scenario. You'd want a smart pointer, `async_non_read_only_shared_ptr` or whatever, that has ownership of, and manages both the object's lifespan and "access lock" (rather than relying on external code to do the owning and managing).

So you could imagine a directive in the concurrency section of the guidelines: "CP.27 Use an `async_non_read_only_shared_ptr<T>` to share ownership of both lifespan and access lock between threads in non-read-only scenarios."

Everybody ok with it so far?

So my quibble is that F.27 and CP.27 conflict because F.27 doesn't restrict it's edict to read-only scenarios when the object is shared between threads. If you read F.27 literally, you might think that it's better to use `shared_ptr` to share ownership of the lifespan, and use external code to own and manage the "access lock" in non-read-only scenarios.

So I guess my question is, "Is that literal reading the intended interpretation?" Do you recommend using `shared_ptr` to share ownership of the lifespan, and using external code to own and manage the "access lock" in non-read-only scenarios?

**Comment by cubbimew** [comment]
`std::shared_ptr` exists to share ownership, not to linearize access to the managed object. That kind of feature set would have made it even less useful that it already is.

**Comment by Pazns** [comment]
@duneroadrunner : 
Are you sure it is really the responsibility of `shared_ptr` to manage a mutex ?
A pointer doesn't have to care about mutexes. It is an internal object mecanism.

If you need such thing, implement it for your own needs. But it seems a bit feature-creep to be pushed into GSL.

**Comment by AndrewPardoe** [comment]
Closing based on @cubbimew's comments.
