### ISSUE TITLE
Question: span with multiple and heterogeneous arrays of the same length?

### ISSUE THREAD

**Issue by ilpropheta** [isocpp/CppCoreGuidelines#653]
It's common to declare functions taking many arrays of the same length and possibly of different types. For example (see [here](https://github.com/saulwiggin/Numerical-Recipies-in-C/blob/master/Chapter12.Fast-Fourier-Transforms/twofft.c)):

`void twofft(float data1[], float data2[]. float fft1[], float fft2[], unsigned long len);`

Or examples involving different types:

`void SetValues(const double* vals, const int* ids, int len);`

Using a span is clearly inconvenient because the size would be repeated multiple times.

What's your advice here?

Thanks,

Marco

**Comment by Amaroker** [comment]
My advice is to consider these core guidelines:

> Per.3: Don't optimize something that's not performance critical

If this really is a performance-critical part of a program, then consider keeping your declaration.

> I.13: Do not pass an array as a single pointer.

If not performance-critical, you should consider using spans since it's less error-prone.

> C.1: Organize related data into structures.

If the pointers are related, the parameter can be a range of structures. No need to repeat the size.

**Comment by MikeGitb** [comment]
> Using a span is **clearly inconvenient** because the size would be repeated multiple times.

Actually, I don't see, how using span here would be inconvenient compared to the plain pointer and size version. You can simply replace each array/pointer parameter with a span and you still have to pass at most 5 parameters and maybe even only 4.

Of course, one could envision a class like `template<size_t N, class ... TS> class span;` that holds a single size and multiple pointers, but I'm not sure if the overhead of a few additional ints is really a big and common enough problem to warrant the additional complexity in span.

**Comment by neilmacintosh** [comment]
We have discussed in the past the idea of having a `tied_span` (maybe with a better name ;-)) class that was essentially one length with multiple pointers.

I think @Amaroker makes an excellent point: if this is performance-critical code, and you have measured the overhead of passing multiple `span`s as being a bottleneck (because you always want to measure to be sure of a cost), then you could certainly just create a class like that and use it in that instance.

**Comment by ilpropheta** [comment]
Hi guys, thanks for the answers.

Actually when I said "inconvenient ", rather than a performance issue (that obviously should be measured in any case), I mostly intended that the interface of the function loses the common size requirement.

I agree on what you are about to reply: the interface requirement is still very poor because nothing really makes an enforcement. However, let's be pragmatic: this is the current standard "de facto" for passing around sequences of the same length. C and C++ programmers know that "idiom". In an ideal world I would express the requirement through contracts, but they are quite far to come into the language, so I am looking for an effective (and pragmatic) alternative now.

We may set up an expectation (e.g. Expects, from the GSL or something else). However, this is still an implementation detail and not really an interface contract.

I have used kind of tied_span for some time working on a project involving legacy code and C libraries. I got two shared feedbacks from my co-workers: "we have lost the name of the parameters" and "declaring such tied_span is too complicated with more than 2 arrays of different type". And worse, many times they just ignored the tied_span and fell back to the old pointers + length approach.

What do you think?

Thanks for your time.

Marco

**Comment by AndrewPardoe** [comment]
Thank you for the suggestion. We will consider this for the next version. Based on @neilmacintosh's comment above, you can write your own in the interim.
