### ISSUE TITLE
Example in Pro.safety.Type.3 contradicts F.17 and NL.16

### ISSUE THREAD

**Issue by Amaroker** [isocpp/CppCoreGuidelines#668]
Example as shown in Pro.safety.Type.3:
```
class foo {
    bar mybar;

    template<class T>           // good, deduces whether T is const or non-const
    static auto get_bar_impl(T& t) -> decltype(t.get_bar())
        { /* the complex logic around getting a possibly-const reference to mybar */ }

public:                         // good
          bar& get_bar()       { return get_bar_impl(*this); }
    const bar& get_bar() const { return get_bar_impl(*this); }
};
```
However, a warning will be enforced in this case, as per F.17:

> Enforcement
> •(Moderate) ((Foundation)) Warn about functions with reference to non-const parameters that do not write to them

**Comment by Amaroker** [comment]
Oh, and it also contradicts NL.16:

> Use the public before protected before private order.

**Comment by neilmacintosh** [comment]
Thanks for the feedback @Amaroker. I corrected the order of declarations so that NL.16 is satisfied. I don't believe there is a contradiction to F.17, as we cannot be sure what happens inside `get_bar_impl()`, it's implementation is purposefully elided. But F.17 would not be particularly helpful if it only respected direct writes as a "use" of a non-const parameter. Calling non-const member functions, or returning non-const members would seem to also satisfy it. So I think this issue can be safely closed.

**Comment by Amaroker** [comment]
@neilmacintosh 

Thank you for the explanation!

I agree with your reasoning, but I think the enforcement text can be clearer. I suggest:

"Warn about functions with reference to non-const parameters that do not write to them and do not access their non-const member data/functions."
