### ISSUE TITLE
NL.15: Use spaces sparingly

### ISSUE THREAD

**Issue by Amaroker** [isocpp/CppCoreGuidelines#669]
There is a note in NL.15:
> Some IDEs have their own opinions and add distracting space.

It's not clear - what is considered a distracting whitespace?

Regarding the example, I don't think `#include<map>` is a good example. That's like writing `std::vector<int>vec;`. Why would anyone be distracted by `#include <map>`?

Whitespace improves readability over text that floats together without spaces.

In order to make this section more meaningful, can we add some guidelines that most programmers, by far, can agree on? Many have strong opinions about coding style, so I guess such guidelines would need to be very basic.

A few suggestions for starters:
- Put space after comma
- Put space between a type and variable
- Put space on both sides of an operator
- Avoid writing two or more adjacent whitespaces (except if used for indention).

Would that be too controversial?

**Comment by Sydriax** [comment]
From my own personal experience writing C++, I have found that OP's suggestions tend to result in the most readable code. While I personally agree with OP's last point, I think that it might be a bit much to impose on programmers and rarely affects readability - if someone wants, for example, two spaces between their parenthesis and curly bracket, I see no reason to stop them.

**Comment by Amaroker** [comment]
But even if your exeample doesn't affect readability much, is that to "use spaces sparingly"?

Perhaps we need to consider a better title.

**Comment by TinoDidriksen** [comment]
The example in NL.15 does go one space too far. Removing the space after `#include` looks really bad. All the other removed spaces can and should be removed, but not that one.

It is also inconsistent with other preprocessor directives. You can't remove the space after `#define` or `#ifdef`, so shouldn't do it after `#include` either.

**Comment by qis** [comment]
I am pretty sure that virtually nobody uses "#include<" without a space. Sadly, we cannot search for this exact sequence of characters on GitHub. Could somebody with database access check and compare it to the normal notation (with space)?

**Comment by johnmcfarlane** [comment]
@Amaroker 's examples could be valuable if they were justified on grounds of readability and consistency:

* Put space after comma

Commas look like periods so adding a space helps differentiate `a.b` (membership) from `a,b` (list items). Also, this is consistent with use of commas in written English and other natural languages.

* Put space between a type and variable

For consistency alone, you shouldn't write `atomic<int>x;` because you cannot write `intx;`.

* Put space on both sides of an operator

This is too broad. Perhaps it relates to things like binary arithmetic operators. Still, I cannot think of a compelling reason to question the choice of the many people whose preference is `a+b` or `a + v` so would feel uncomfortable imposing a choice. That said, mixing both styles in a single code base should probably be discouraged - and certainly can be automated.

Might examples such as these help clarify when a space is justified?

**Comment by amdn** [comment]
With apologies in advance if Google's Style Guide has been mentioned,
perhaps a reference to it would be appropriate.  Here's the section on
horizontal and vertical whitespace:

https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace
On Aug 18, 2016 11:13 AM, "John McFarlane" <notifications@github.com> wrote:

@Amaroker <https://github.com/Amaroker> 's examples could be valuable if
they were justified on grounds of readability and consistency:

   - Put space after comma

Commas look like periods so adding a space helps differentiate a.b
(membership) from a,b (list items). Also, this is consistent with use of
commas in written English and other natural languages.

   - Put space between a type and variable

For consistency alone, you shouldn't write atomic<int>x; because you cannot
write intx;.

   - Put space on both sides of an operator

This is too broad. Perhaps it relates to things like binary arithmetic
operators. Still, I cannot think of a compelling reason to question the
choice of the many people whose preference is a+b or a + v so would feel
uncomfortable imposing a choice. That said, mixing both styles in a single
code base should probably be discouraged - and certainly can be automated.

Might examples such as these help clarify when a space is justified?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/isocpp/CppCoreGuidelines/issues/669#issuecomment-240774466>,
or mute the thread

**Comment by galik** [comment]
Just my 2 pence.

This is probably about what you are used to looking at as much as anything. But I find if you omit the spaces between operators it gets harder to parse the expression because it appears visually as a block of text:

Just looking at the three extremes of how to space expressions:

```cpp
// wall of characters
x=(((a+b)/c)-((a-b)/d))/(((a-b)/d)+((a+b)/c)); 
```

```cpp
// just right for me
x = (((a + b) / c) - ((a - b) / d)) / (((a - b) / d) + ((a + b) / c)); 
```

```cpp
// way too spacey
x = ( ( ( a + b ) / c ) - ( ( a - b ) / d ) ) / ( ( ( a - b ) / d ) + ( ( a + b ) / c ) ); 
```

The first and the last examples both have equal spacing (or lack of) between each character. I feel this prevents the eye from falling naturally towards relevant groupings as quickly as in the middle example. In each case the *parens* give guidance but that seems to get lost for me in the third example when the *parens* don't 'hug' the expressions they group.

I agree that imposing a choice is likely to be unproductive. I think the best philosophy is to code the using the same style as the code you are working on. If you are being paid to code a particular way - do that. Otherwise just stay neat, consistent and readable.

**Comment by Amaroker** [comment]
In reply to @johnmcfarlane :
> Might examples such as these help clarify when a space is justified?

Yes, justifications are welcome. A few examples should be enough. I just don't want this guideline to imply that spaces should be used too sparingly. I think it should be somewhat consistent with natural languages where you add spaces between every word, which is undoubtedly easy to read.

> This is too broad. Perhaps it relates to things like binary arithmetic 

Yes, a bit too broad I guess. However, I think it's fine to add spaces around most operators that involves two arguments. It doesn't need to be recommended, but at least should not be considered distracting.

As opposed to operators that only operates on a single variable, for example postfix increment. In such cases, I don't expect any space between the variable and the operator. That, I think, can possibly be distracting.

**Comment by MikeGitb** [comment]
What about "don't use white space excessively"? 

I Think the important thing about white space is that it is used to structure, group and highlight parts of the code and as e.g. galik's math example demonstrates, it can't fulfill this purpose if it is evenly distributed all over the code.

**Comment by Amaroker** [comment]
> What about "don't use white space excessively"? 

I like it, but either way I think it's important to show some good examples to make it clear what is the meaning of "excessively" (or "sparingly").

In galik's example, all it takes is to write spaces around the operators without adding any other spaces. That seems to be the underlying principle that leads to galik's middle example. 

In my opinion, for consistency, you should always write code like that.

But I don't know how else to justify it. All I can say is that I personally find it much easier to read, but obviously many people have the preference "a+b" like johnmcfarlane said. That leads to galik's first example.

**Comment by Pazns** [comment]
> In my opinion, for consistency, you should always write code like that.

It's like code indentation, with accolades, `if`-line feed, etc.
We are not robots, we sometimes need readability and aesthetic to ease the flow of code in our eyes.

When you have a lot of `a + b` everywhere, maybe a contraction in `a+b` could be more helpful than consistency. It doesn't break anything visually, nor is ambiguous, nor distinct from `a + b` , so why forbid it ?

**Comment by Amaroker** [comment]
I don't mean to forbid it. It's just a guideline we're discussing. 

Well, I shouldn't have used the word "always". For example, I think `(a*a + b*b)` is fine. But at least trying to be consistent most of the time.

**Comment by BjarneStroustrup** [comment]
It's an issue on which everybody seems to have a strong opinion. Aesthetic issues are hard to grapple with. The odds are that we will refrain from being too specific. We refer to http://www.stroustrup.com/Programming/PPP-style.pdf (written for students) in which you can find some specifics.
