### ISSUE TITLE
Do we want "STL" to remain a live term?

### ISSUE THREAD

**Issue by tkoeppe** [isocpp/CppCoreGuidelines#68]
The glossary at the beginning of the document defines "STL" as "Standard Library". Do we want to give the abbreviation this new meaning? Will there be danger of confusion with Stepanov's historic Standard Template Library?

**Comment by galik** [comment]
Personally I think `STL` is an important term because it stands for a library whose philosophy revolutionized modern programming. Therefore we need to be able to refer to that library/philosophy with a well defined term. I mean it is so good it became part of the `Standard Library`. But it is not the same thing as the `Standard Library`. I think keeping the distinction is very important.

**Comment by erip** [comment]
This is a very interesting question. I agree with @galik that `STL` is quite important to the history of the language. However, it is just that: history. 

@galik hit the nail on the head. The `STL` did, indeed, become *part* of the C++ Standard Library. As such, it is a subset of the C++ Standard Library. Confusing these terms is as spurious as confusing "numbers" and "integers".

**Comment by AndrewPardoe** [comment]
Thank you! We've changed references from STL to standard library as appropriate.
