### ISSUE TITLE
Samples should follow best/better advice rather than good advice from guidelines.

### ISSUE THREAD

**Issue by ParadineG** [isocpp/CppCoreGuidelines#699]
Reason:
If guidelines does not try it best to follow its own advice, then users will be even less likely to follow it.
Also seeing best advice in action, is one way to get used to it.
Example:
Rule "ES.23 Prefer the  {}  initializer syntax" is rather loosely followed.
How to do:
When adding new sample of problem or solution, one should not think about it, as one might forget the basic idea. But after adding it, community should refactor/iterate it closest to ideal form according to current guidelines.

**Comment by BjarneStroustrup** [comment]
We are trying to get better at that, but we deal with lots of real-world code and don't yet have tools that catch all departures from the recommendations. The "prefer" guidelines are particularly tricky because we know they can rarely be followed 100% in real-world code, e.g., you cannot use one consistent naming style when using many libraries from different sources (each with its own style).
