### ISSUE TITLE
Idea: CppCoreGuidelines as a template for company specific guidelines.

### ISSUE THREAD

**Issue by ParadineG** [isocpp/CppCoreGuidelines#702]
Create solution (script) for companies to use current guideline as a template.
1. Automatically creates one version for companies.
2. Is automatically updated and notified about changes.
3. Can override specific rules, with companies own rule (why they cant follow it and alternative solution).
4. Tools that are tied to guidelines ignore overwritten rules.
5. Add new rules.
6. It should be simple and easy to use.

If C++ programmer views this as default guideline. Then changing companies would mean that he would only would need to read changes for specific company, rather than whole new guideline.

**Comment by BjarneStroustrup** [comment]
We are trying to devise something like that. It's necessary to accommodate specific needs and to manage incremental adoption.

**Comment by ParadineG** [comment]
Good to know, that steps are made towards that end.

**Comment by AndrewPardoe** [comment]
Some companies have started doing this. The template that seems to work best is:

For each section (e.g., Philosophy or Interfaces)
- Specify any guidelines that are rejected, with a reason specific to your organization
- List any guidelines that have been added in the format of S.XXXX.N

where S stands for the section (e.g., Interfaces), XXXX represents your organization (e.g., MSFT, GOOG, etc.), and N is a unique rule number starting at 1. 

Of course any organization can do what works best for their organization. We do encourage that any local rules be raised as Issues here so that we can consider them for global adoption.

**Comment by BjarneStroustrup** [comment]
It would be good if we could produce and example or template for that. I'll have a look at that (in my copious spare time :-( )

**Comment by AndrewPardoe** [comment]
Closing this issue as some companies have already done this. If anyone would like to clone and adapt this for their own organization, please contact me directly and we can advise on how that was done in other organizations.
