### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by patrickullmann** [isocpp/CppCoreGuidelines#71]
What about exceptions? This is sometimes an enigma for the correctly use in C++ (like in constructors / destructors with using inheritance). In this topic I see much code with memory leaks or runtime errors.

**Comment by MalcolmMcLean** [comment]
A function can fail if a) an attached hardware device fails, b) it runs out of memory, c) it is called with invalid arguments d) it is coded incorrectly.

c) and d) are programming errors, so there can be by definition no correct behaviour, we need to look at least damaging fallbacks. a) is largely beyond the scope of a language specification - programs will want to react in many ways to hardware failure, though we can maybe consider how to design streams. b) is the difficult one. A modern hosted system is probably more likely to break down electrically than to fail to fulfil a request for a small amount of memory, requests for large amounts of memory can legitimately fail in normal operation, memory leaks can cause  small requests to eventually fail. So if an allocation request for a string to hold the user's name fails, it's either a bug or a DoS attack. If an allocation request for several megabytes to hold a video clip fails, you'd expect the program to inform the user in a normal way that he needs more memory to carry out the operation.

**Comment by cubbimew** [comment]
Section E already has a number of guidelines on error handling, including "E.5: Let a constructor establish an invariant, and throw if it cannot" and "E.6: Use RAII to prevent leaks" (which includes a discussion ending with "Prefer to use exceptions.")

**Comment by GregUtas** [comment]
A system of even moderate complexity should define a base Exception class derived directly from std::exception, and all of the system's exceptions should then derive from Exception.  Exception's constructor allocates an ostringstream in a unique_ptr and invokes a platform specific function that traverses the stack frames and writes the function call chain into this stream.  This is invaluable for debugging purposes, so much so that std::exception should support it as a plug-in, along the lines of terminate_handler.  Were this done, all STL exceptions should derive from std::exception so that the stack could be captured.  Note that the stack needs to be captured when the exception is thrown; once it has been caught, the stack has unwound to that level, and useful debugging information has been lost.

**Comment by AndrewPardoe** [comment]
Reviewed 11/30/2105.

It looks like @cubbimew's answer addresses the original question. @patrickullmann, do you have any additional questions to specific points?
