### ISSUE TITLE
C26481 & C26485 generated for code that doesn't appear to use pointers

### ISSUE THREAD

**Issue by Dave-Lowndes** [isocpp/CppCoreGuidelines#771]
The following code with VS 15 preview 5 generates the warnings shown with the core checks.

static const int MyArray[] = {1,2,3};
static void Fn()
{
// Warning	C26481	Don't use pointer arithmetic. Use span instead. (bounds.1: http://go.microsoft.com/fwlink/p/?LinkID=620413)
// Warning	C26485	Expression '<range>$L0': No array to pointer decay. ( bounds.3: http://go.microsoft.com/fwlink/p/?LinkID=620415)
	for ( const auto item : MyArray )
	{
	}
}

Is this a bug?

**Comment by neilmacintosh** [comment]
Hello @Dave-Lowndes! These are tool-specific questions and belong with the tool vendor, rather than at this repository. Given I happen to work at that particular tool vendor, consider the bug report accepted ;-) In future, sending these reports to cppcorecheck@microsoft.com is the most direct method of bringing them to our attention (or using the VS Feedback mechanism).
