### ISSUE TITLE
Does the suggestion for using span for "Bounds.2: Only index into arrays using constant expressions." make code maintainence/analysis harder?

### ISSUE THREAD

**Issue by Dave-Lowndes** [isocpp/CppCoreGuidelines#772]
The suggestion for using span for "[Bounds.2: Only index into arrays using constant expressions](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Pro-bounds-arrayindex)." says:

// ALTERNATIVE A: Use a span
void f1()
{
    int arr[COUNT];
    span<int> av = arr;
    for (int i = 0; i < COUNT; ++i)
        av[i] = i;
}

The problem I foresee with this is that you're making existing code harder to analyse by introducing the av variable.

The example is simplistic, but consider instead if the array were global and used in several places. Imagine searching code to find places that reference it... you won't necessarily spot that it's being referenced indirectly via the pseudonym "av" in the loop.

I feel this suggestion could be detrimental to code maintenance.

A better choice in this respect (but uglier IMO) is // ALTERNATIVE B: Use at() for access

**Comment by rianquinn** [comment]
At first we used `gsl::at` and then switched to `span` purely because of aesthetics, but we are using `gsl::at` instead now for this very reason, or we have tried to find ways to use `std::vector` so that we can use `std::vector.at()` instead of `std::vector.operator[]`.

**Comment by Dave-Lowndes** [comment]
Thanks for that Rian, it's good to know I'm not alone.

**Comment by rianquinn** [comment]
@Dave-Lowndes I would hope that in the future there is no need for `span` and that the std containers are updated to have the needed bounds checks (which I think would require the addition of a `std::array` like container that can have it's bounds defined at runtime). 

I really hope there is no need for `span` in the future, but if there is, there should probably be a discussion on naming conventions as it's hard to figure out what name to give things here that others would understand as the code looks something like this everywhere:

```
std::array<int, 5> m_array;
gsl::span<int> m_???;
```

What's also concerning is the extra needed memory to do this, which really shouldn't be needed if the std containers already had the needed bounds checks. In our case, we have tried to remove as many of these as possible by using `gsl::at` and `std::vector`, but where they still exist, we use this scheme:

```
std::array<int, 5> m_array_owner;
gsl::span<int> m_array;
```

But I could see others naming it `m_array` and `m_array_view`.

**Comment by AndrewPardoe** [comment]
Per our discussion this week, we should mention that when you're doing range checking you should do a loop that can check at the beginning and the end. If you're not using the loop index, you can focus more on what you're going to do to the elements. Neil, could you please add a bit?

**Comment by neilmacintosh** [comment]
I'm rather unconvinced by the example of wanting to textually search for a global variable's name. If that is seriously a problem, wouldn't you just have a global `span` that "goes with" the global variable? Aren't global variables something you try to minimize (rather than write guidelines around) anyway? The example in "alternative A" there uses a local array anyway.

I would suggest the vast majority of uses of `span` would be as a parameter/return type. When `span` is used to guard access to a member/global/local then I don't see it reducing readability. I do see it reducing the likelihood that a programmer forgets to use an `at` in the right place ;-).

What I think this issue has highlighted though is that the example given in Bounds.2 is not a particularly good one. So I'll go fix it, because for that simple case you'd get the same safety from just using a range-for loop (see ES.71) or `std` algorithm.
