### ISSUE TITLE
Bad example for E.6: Use RAII to prevent leaks

### ISSUE THREAD

**Issue by rianquinn** [isocpp/CppCoreGuidelines#775]
The titles says to use RAII, but then uses a unique_ptr in the example. Granted, this is RAII, but I think it's misleading. The title should say something like "Use std::unique_ptr to prevent memory leaks" or we could do something like update the example to use `gsl::finally` to perform the `delete` and state that a `std::unique_ptr` would have ben a better choice. 

My reason for stating this is a leak can occur regardless of `new`. For example, `fopen` and `fclose` could cause a resource leak on some systems and `std::unique_ptr` is not the right way to handle that, but the intent of this guideline still applies. RAII is really the only way to prevent state corruption when using exceptions, and examples like this really should better illustrate the [ScopeGuard](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4189.pdf) problem 

I'd be happy to provide a PR but wanted some input first.

**Comment by cubbimew** [comment]
TC++PL introduced RAII using the fopen//fclose example (in 13.3), with an actual RAII class that acquires/throws in constructor and releases in destructor: I'd love to see that for the benefit of the people who focus on cleanup more than acquisition, but I think E.6 is already doing a good job, showing both a full RAII class (std::vector) and a popular building bloc (std::unique_ptr).

**Comment by MikeGitb** [comment]
Using `gsl::finally` to perform some cleanup is imho not raii. You're still have to write manual cleanup cleanup code and you are not really initializing anything at the point of ressource acquisition. 
It is rather a different technique to achieve the same thing (guarantee cleanup on all possible code paths) with different tradeoffs.

**Comment by rianquinn** [comment]
@MikeGitb I might have my understanding of RAII incorrect, but this certainly seems like it to me

```
auto p = new int[5];

auto donotcare = gsl::finally([&]{
    delete[] p;
});

<do stuff that might throw>
```

@cubbimew I agree that it shows a good example of RAII, but the title is not about how to use RAII, but rather how to prevent leaks, and I think that the example should really focus on more than just memory leaks as it's an extremely common problem to see people acquiring resources in the presence of exceptions.

**Comment by Sqeaky** [comment]
That is not RAII because you did not fully initialize the resource, including a plan for cleanup on initialization. If for some reason the gsl::finally line fails then then p still leaks. 

A likely cause for this being more error prone is other programmers. If some other programmer on the team puts something that fails occasionally between the two lines without realizing he interrupted your design pattern then bugs will happen.

Though unique_ptr and vector use RAII internally the existing example does not convey what is going on underneath. Here is an example I would consider more a more demonstrative example of RAII:
`
class R {
   resource* r;
   public:
      R() : r{ get_resource_from_system() } {}
      ~R() { free_system_resource(r); }
};

int main() { 
    R p; 
    // Do stuff that might throw
}
`
This is not fully formed, it needs its move and copy constructors deleted at a minimum. Presuming this is fixed...

No matter what happens the pointer to the system resource pointer cannot leak, because either the constructor will succeed or the will not be allocated (presuming the function system functions are sane) and once the destructor is called the resource is freed.

The resources are acquired on the initialization of p and and a plan for cleanup is in place immediately. Not the line after, right there, and just as importantly they are freed automatically on destruction.

Another clumsy programmer can still break this by going and tinkering with R but in practice they would need to go to another file and do that. Hopefully this would add enough of a barrier that it wouldn't happen until that programmer asked if it was a good idea.

**Comment by MikeGitb** [comment]
Maybe my definition of RAII is just to narrow. I'm certainly not the authority on that, but in any case, I wouldn't make a scope guard the main example foR RAII.

**Comment by rianquinn** [comment]
@Sqeaky I like that example a lot more.

**Comment by AndrewPardoe** [comment]
Finally and scope_guards are the last resort. Bjarne, please update this.

**Comment by BjarneStroustrup** [comment]
Clarified that finally() is a last resort
