### ISSUE TITLE
C.21: Maybe relax statement? (Rule of Three?)

### ISSUE THREAD

**Issue by maikel** [isocpp/CppCoreGuidelines#794]
Imagine you do not have a DefaultConstructible type because there happens to be no valid empty state. Furthermore one can manually define copy instructions. Moving would be cheap but leave the object in an invalid state.

We have the rule

> C.21: If you define or =delete any default operation, define or
> =delete them all

Now I seem to have the choice

- Delete move assignment and constructor. Apply rule of six but move-expressions will raise compiler errors.
- Rely on implicit definitions. Violates rule of six but move-expressions will compile while being copies (making them Semiregular?). (as with std::array)
- Manually define move constructor and assignment. Copy-pastes my copy constructor and assignment, might not be exception safe. Bad, bad, bad ?
- Leave it in an invalid state after moving. Possibly add functions to check the state. (as with optional, variant, ...?) Seems to me like a burden.

Is it really "correct" to delete them instead of implicit-copying just to fulfill the rule of six? I see pro's and con's for both approaches.
The implicit defined default operations might lure the developer into thinking moving is cheap.
On the other hand aren't we  used to MoveConstructible types (see std::array or other stack-based vectors for this dilemma) which are not cheap to move?

I have such a type in my hand right now which i apply up-to-now "Rule of Three" for this case (implicit move is copy thing). 

  [1]: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-five

**Comment by MikeGitb** [comment]
What about just forwarding move to copy?:

	struct Foo {
		Foo& operator=(const Foo& other) { std::cout << "Copy assignment\n"; return *this; }
		Foo& operator=(Foo&& other) { return *this = other; }
	};

I think the main advantage of the rule of 0 & 5/6 is that 

- it leaves an explicit trail in the code that you thought about the semantics of all the special member functions 
- you are not at the mercy of the changing rules, about what functions are automatically generated or deleted by the compiler.
- it can be easily verified by a tool

On the otehr hand it also introduces some unnecessary boilerplate (in particular the destructor can almost always be defaulted)

**Comment by maikel** [comment]
This makes the third option much better. I forgot forwarding and I really like it being explicit. That is what I was relying on implicitly anyway so I would prefer that over the implicit definition.

But I think as long as the copy-constructor can throw, I should delete the Move semantics? Imagine I copy an unique pointer (pimpl idiom or similar). A nullptr would be invalid. Forwarding move to copy would imply an allocation, but swapping on the other hand might be well-defined.

I tend to delete move semantics right now and define swap function. 

But what are the consequences of not being MoveConstructible (while being CopyConstructible) in other contexts? Should I bother?

**Comment by shaneasd** [comment]
Not sure if you still care about the answer to your question 6 years later but I happen to have recently encountered both the same question and this discussion so I'll answer in case it's helpful to you or a future reader.

One implication I've noticed is on the following code
```
X MakeX()
{
    X x;
    return x;
}
```

In the return statement overload resolution will act as if x is an rvalue. This means we can take advantage of more efficient move semantics since x is about to reach the end of its life anyway. What if your class doesn't have a move constructor though? Apparently it depends why not. If it doesn't have one because the language rules meant one didn't get generated for you then the copy constructor will get used instead and you're fine. However if you explicitly =deleted it it's the =deleted move constructor which gets selected by overload resolution and your code doesn't compile.

I don't know how NRVO interacts with this. Certainly this is a candidate for NRVO but I don't recall if NRVO is permitted if the selected constructor is =deleted. Either way I don't think you want to rely on NRVO for your code to compile.

Note that the move constructor can be forwarded just like move assignment as MikeGitb pointed out.
