### ISSUE TITLE
C.5 Where to put helper functions for classes that are in the global namespace?

### ISSUE THREAD

**Issue by daviddoria** [isocpp/CppCoreGuidelines#807]
The example given is:

    namespace Chrono { // here we keep time-related services

        class Time { /* ... */ };
        class Date { /* ... */ };

        // helper functions:
        bool operator==(Date, Date);
        Date next_weekday(Date);
        // ...
    }

Presumably this is not recommended, as then the functions pollute the global namespace:

    // global namespace
    class Date { /* ... */ };

    // helper functions:
    bool operator==(Date, Date);
    // ...

What is recommended instead?

**Comment by cubbimew** [comment]
Why would it make a difference? If the class is in the global namespace (for whatever reason), the rest of its interface should be there as well (for ADL).

There's a technique of defining non-members as inline friends so that they disappear from the enclosing namespace and are *only* found by ADL, but it seems obscure because 'friend' has another meaning.

**Comment by daviddoria** [comment]
I'm just thinking about organization. If you have:

    namespace MyLib {
        class Date { /* ... */ };

        // helper functions:
        Date next_weekday(Date);
    }

    int main()
    {
        Date nextDay = MyLib::next_weekday(Date(...));
    }

that doesn't feel as "organized" as:

namespace MyLib {
        class Date { /* ... */ };

        // helper functions:
        namespace DateHelpers {
            Date next_weekday(Date);
        }
    }

    int main()
    {
        Date nextDay = MyLib::DateHelpers::next_weekday(Date(...));
    }

**Comment by cubbimew** [comment]
You could make that an `inline namespace DateHelpers`, then both programs may use 

    auto nextDay = next_weekday(MyLib::Date(...)); 

Is that a canonical use for inline namespaces, though?

**Comment by daviddoria** [comment]
It sounds like this would be totally an abuse of the intended purpose: http://stackoverflow.com/questions/11016220/what-are-inline-namespaces-for

I'm just trying to point out that this seems like a pretty common situation (where the namespace is very much "bigger" than the class + helpers (i.e. the MyLib namespace relationship to the Date class, versus the original example's Chrono namespace relationship to the Date class), so it seems like something that the guideline could indicate a standard practice for.

**Comment by MikeGitb** [comment]
I think functions belong in the same namespace, as the classes they are supposed to operate on, because they form (together with the public member functions) the interface of your class / module.  In your example, `next_weekday` clearly belongs into the same namespace as Date. If MyLib vecomes too big, I'd rather divide the different parts into separate namespaces (e.g. put Date and next_weekday into `Mylib::Dates`).
I only use helper/impl/detail namespaces only for implementation details that I want to hide from the user.

**Comment by AndrewPardoe** [comment]
Thank you for the suggestion and good discussion. We've discussed this amongst the editors, and based on that discussion and comments here we're going to leave the text as-is.
