### ISSUE TITLE
C.35: There are special cases that tooling should recognize

### ISSUE THREAD

**Issue by AndrewPardoe** [isocpp/CppCoreGuidelines#812]
The enforcement "A class with any virtual functions should have a destructor that is either public and virtual or else protected and nonvirtual." is a bit strong.

**Comment by jwakely** [comment]
The rule already covers the case I was concerned about (protected and nonvirtual) and I don't have any counterexamples.

**Comment by hsutter** [comment]
The reason is that you either destruction should be polymorphic or it shouldn’t.

 

If yes (it should be), the destructor must be public (so that it can be called) and must be virtual (so that it is type-correct).

 

Otherwise (it should not be), then the destructor should be nonpublic (to prevent it from being called accidentally; but it cannot be private since it must be invokable by the derived class, and therefore it must be protected) and has no reason to be virtual (it is invoked directly by the derived class on its own base subobject).

 

I don’t know of any other combination that makes sense. For example, a base class destructor can’t be private (as noted above). So that leaves only public+nonvirtual which is just a design bug, and protected+virtual which is unnecessarily virtual (unless someone knows a legitimate example). That covers all combinations, and only these two make sense.

 

The rule should apply to all base classes, but “has any virtual functions” is a simple way to mechanically identify nearly all base classes.

**Comment by neilmacintosh** [comment]
I can't see that there is any tension between the enforcement as currently specified and any of the comments on this thread, so I'm closing the issue.
