### ISSUE TITLE
I.23 enforcement suggestion

### ISSUE THREAD

**Issue by JonasToth** [isocpp/CppCoreGuidelines#827]
The rule suggests to keep the amount of arguments low.

There is no enforcement suggestion to flag all functions above a certain limit.
clang-tidy has a check called `readability-function-size`. I think this check could be handle the number of arguments as well.

**Comment by hsutter** [comment]
Discussed by the editors on 3/20. We believe this is a good suggestion, although any specific number will cause a lot of false positives in legacy code; the text suggests aiming for fewer than 4 parameters.

The Guidelines' primary purpose is to encourage good modern style to help write new code correctly, and I think what's most missing here is to state the main two reasons why functions with lots of parameters exist: Because they're missing an abstraction, or because the function is trying to do more than one job.

I'll add explicit coverage of those reasons and another example illustrating that.

Thanks!
