### ISSUE TITLE
High-level concurrency guideline question (related to CP1)

### ISSUE THREAD

**Issue by nnathan** [isocpp/CppCoreGuidelines#850]
I'm not sure if this is an appropriate venue to ask but I read the CP guidelines and still remain lost.

I'm reviewing C++ code that builds classes that implement a "threading interface" where there is a `run()` and `stop()` method. I'm not sure if this is really necessary as it seems that threading should be decoupled from the class, but this might be some standard concurrency design I'm not aware of. CP1 seems to use an example for a function, but I feel that it should also apply to classes - in that they should be aware that concurrency can be used, but it should be agnostic to whether it is run within a thread or not, and not "hijack" control-flow (which is the underlying essence of having a `run()` function).

Please let me know if this is unclear or off-topic.

**Comment by jwakely** [comment]
It's unclear to me what you're asking. Are you pointing out a problem with the guidelines? Or asking how they relate to the codebase you're looking at? Problems with the guidelines are on-topic here, questions about how they apply to your code are not.

CP.1 is talking about code that might be _used_ in a multithreaded program, but is not talking about how a multithreaded program creates and manages its threads. In a typical multithreaded program the entire system can't be agnostic about the presence of threads, otherwise nothing would ever create new threads. It seems like the `run()` and `stop()` functions you're referring to are part of how the program manages its threads, so they _can't_ be agnostic to threads, and CP1 doesn't apply to those functions (except that obviously functions that create and manage threads assume they are part of a multithreaded program!)

**Comment by nnathan** [comment]
I am not pointing out a problem with the guidelines.

I was asking how they relate to the codebase and verifying if I understood CP1.

I think what I _want_ is for more solid guidelines on how a program should be designed with concurrency/parallelism in mind - beyond what CP currently offers. I like CP1, but I think it is a very basic and obvious (write reentrant functions). 

I would _like_ more guidelines on how to write an overall program that will evolve to using concurrency/parallelism. How to break up the software components, make it work without concurrency/parallelism if possible, and finally break it into tasks (per CP4) and add the threading last. This allows easier testability (in the case of single-threaded) and easier reasoning (in the case of breaking it into tasks). At least that is my experience, but I would much prefer experts on these issues weigh in. 
The reason I'm asking here is that most resources on threading is either pthreads and doesn't really cover the design of an overall program but rather how to use threading as a feature.

On a side note, in the past few years I've been programming in Go which has a highly-opinionated threading/concurrency system. The language designers/authors spent a lot of time educating users of the language (as part of official blog series and talks) on how to design programs that implement concurrency/parallelism. I'm not asking the same exact rigor from the guidelines, but just some food for thought.

**Comment by jwakely** [comment]
OK, thanks for clarifying. The guidelines on concurrency are definitely incomplete and need more work. Partly that's because the ideal tools don't exist in C++ yet, or are not widely available. A guideline for high-level program design using the low-level C++ tools like `std::thread` and `std::mutex` facilities is "don't". See [CP.4](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconc-task), which is incomplete.

For better approaches that may be included in the guidelines some day, see [Extensions for Parallelism](http://en.cppreference.com/w/cpp/experimental/parallelism) and [Extensions for Concurrency](http://en.cppreference.com/w/cpp/experimental/concurrency) for some existing pieces, and the work-in-progress proposals for high-level features like coroutines and executors.

**Comment by jwakely** [comment]
This was discussed among the editors and we all agree that we need better concurrency guidelines, and plan to add them, but the precise form they'll take is not clear yet. Since there's nothing immediately actionable in this issue report we've decided not to keep it open. We won't forget that we need better concurrency guidelines though! Thanks for the input.
