### ISSUE TITLE
C.21 and C.81 appear to be in conflict

### ISSUE THREAD

**Issue by rriggs** [isocpp/CppCoreGuidelines#876]
My naive reading of these two items have them in conflict.  Some reference among these two items and common guidelines would be helpful.  C.21 seems overly broad.  C.81 seems vague and incomplete.

C.21 If you define or =delete any default operation, define or =delete them all
C.81 Use =delete when you want to disable default behavior (without wanting an alternative)

C.81 just deletes the copy constructor to create a movable type.  (I think the assignment operator should also be deleted in C.81 to be correct.)

**Comment by jwakely** [comment]
They don't conflict. The "// ..." parts in the C.81 examples are where you'd define or delete the other operations, in order to follow C.21.

Nowhere in C.81 does it say _not_ to follow the advice of C.21.

> (I think the assignment operator should also be deleted in C.81 to be correct.)

Even if you don't follow C.21 it would be implicitly deleted. If you want to be correct w.r.t the guidelines you'd delete it, but it would be deleted anyway.

**Comment by jwakely** [comment]
C.21 says:

> If you don't want a default operation, suppress it with `=delete`.

And C.81 covers that same point, but going into more detail about why you wouldn't want a default operation. I see no conflict at all.

We could add "see C.81" to the end of the above sentence, and in C.81 we could add a note saying the other special member functions should be defined or deleted, referring to C.21. That might be an improvement, but isn't necessary to resolve any conflict.

**Comment by AndrewPardoe** [comment]
Thank you for the clarification, Jonathan. Closing per our editor's discussion.
