### ISSUE TITLE
header file rule: prefer #pragma once over include guards

### ISSUE THREAD

**Issue by a-teammate** [isocpp/CppCoreGuidelines#903]
Reason:
Include guards are more to write and are sometimes even error-prone (each file needs a unique include guard. there is sometimes no way to really ensure this when working bottom-up. Or when cloning files and you forgot to change the include guards).
Modern compilers supporting C++14 also support `#pragma once`.
https://en.wikipedia.org/wiki/Pragma_once

Exception:
old/exotic compilers need to be supported.
Then use include guards.

This will also change SF.8 to "Use `#pragma once` for all header-files"

**Comment by cubbimew** [comment]
Having experienced both guard name collisions and commit-time tool enforcement of header guard naming, counter-proposal is to strengthen SF.8 with a recommendation on naming and tool use. It's currently showing FILENAME_H which invites collisons. I've used LIBNAME_FILENAME_H, and I've seen REALLY_LONG_PATH_FILENAME_H and even FILENAME_H_reallylonguuid). A note about pragma #once could help, too, if this issue is resolved in favor of include guards.

Also, this might be moot because "[what would you like your code to look like in 5 years' time](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#abstract)" is modules.

**Comment by lbrandy** [comment]
I don't think we want to "prefer" pragma once since it's not standard. See: P.2: Write in ISO Standard C++.

I'd be generally in favor of a note talking about `#pragma once` since it's widely supported but not standard and therefore not portable. In our internal standards we definitely allow it, use it, and occasionally prefer it. 

I also agree @cubbimew that we should shy away from just `basename.h` as an example as it's easily a source of collision. In any large codebase, grepping for `"ifndef UTIL_H"` tends to produce scary results.

**Comment by viboes** [comment]
As any macro the macro must be prefixed by LIBNAME_. If you have issues with the include guard following this rule there is chances that you could have issues with other macros (if your library has those).
