### ISSUE TITLE
Add guideline for writing loops

### ISSUE THREAD

**Issue by jwakely** [isocpp/CppCoreGuidelines#913]
As discussed in the editors' meeting, we don't have a rule specifically about how to write good loops.

Should have a clearly defined loop invariant, etc.

(IIRC Andy Koenig has written some excellent advice on this topic that influenced my thinking.)

**Comment by richelbilderbeek** [comment]
Just adding [an earlier Issue](https://github.com/isocpp/CppCoreGuidelines/issues/246) about the conditional in a for-loop.

**Comment by Sheila69** [comment]
_**__Loops__ always should have safe end-conditions.**_ In your [earlier issue](https://github.com/isocpp/CppCoreGuidelines/issues/246)  @richelbilderbeek you say that both operators are same good. That is right for your case where you ensure that the "for-loop counter" is not changed. But if the code gets more complex later, additional code inbetween may be inserted, which might affect the for-control counter. So then its not always safe to use the != operator. You even go the risk of an endless loop. There's no compiler warning I know of, which would warn you.
So generally its safe always to use the < operator in this case. Any unexpected changed "for-loop counter" values then directly stops the loop immediately. And so no out-of-range scenarios can happen.

End-conditions should be checked very carefully cause the most endless-loops and access violations occur from memory overrun/underun caused by loops. 
When using != 0 as end-condition, its more safe to use it on a loop which runs towards 0.


_**Loops generally should be easy to read.**_
Do not put all conditions into one line. It is more clear to use some "if (..) break;" blocks.
Be aware of the use of "continue". If at the end of the loop is another memory increment, that must be respected on the use of "continue".
complex **_while_** loops always have the risk, that there is no defined end-condition, so move some parts of the loop to __forceinline sub functions. The compiler will merge them altogether during optimization.




**_Write { } braces with same indent_**
example:
```
for (int i = 0; i < MAX_VALUE; ++i)
{
   // code
}
```

Do NOT use this style, cause its hard to read in very complex code:
```
for (int i = 0; i < MAX_VALUE; ++i)  {
   // code
}

```

_**Name the For-Control Counter**_
when for example in your code context the loop processes "Levels" then call it "Level" instead of "i"
```
for (int Level = 0; Level < MAX_LEVEL; ++Level)
{
      for (int light = 0; light < N_LIGHTS; ++lights)
      {
         float this_light = LightArray[Level * N_LIGHTS + light];
        // so here in deeper nested loops the var name already avoids confusion about 
        // the purpose of the var
      }
}
```

_**Use #defines for the End-condition Value**_
This way you later simply know quickly the purpose. And if used in many loops a change is simply possible by changing only the #define line instead of change in each loop.

_**Loop Invariant**_
A loop invariant is a condition [among program variables] that is necessarily true immediately before and immediately after each iteration of a loop. [Source here](http://www.cs.uofs.edu/~mccloske/courses/cmps144/invariants_lec.html)
For most developers these theoretical things are not important, cause they focus on the results instead of theory. So complicated definitions don't help. Explain it easy.

_**Use Data Alignment.**_
When using 16byte data alignment the faster version of the SSE2 instructions can be used.
movdqa instead of movdqu (and some more) 
Unaligned instructions always took longer in my memory speed tests:
```
    Intel QuadCore 4x2.83GHz:      
    test started. max_iterations=4000000000
     MOVUPS SSE1 msec used=4260    // unaligend move
     MOVDQU SSE2 msec used=4240  //  unaligned move
     MOVAPS SSE1 msec used=2840    // aligned move
     MOVDQA SSE2 msec used=similar to MOVAPS  // aligned move
```


_**Use the latest version of the compiler**_
When using the latest compilers any new optimizations for loops are implemented.

**_Start For-Loop Counter from nearest element affected._**
@jwakely  Andy Koenig talks about using starting a loop with 0 or 1. Generally a loop should start from the nearest element which is affected. So when reading/writing from/to the beginning of an array, using 0 seems to be the best option in most cases, cause then the "for-loop-counter" directly can be directly used as index to the array. 
So a general advice could be always to try to use 0-based vars/Arrays, which then would lead to always start a for-loop-counter with 0.



**_Use PREFETCH instructions on arrays with known strides:_**
it can provide higher performance : it updates cache lines only, no destination register
(See [Intel Optimization Guide 7.3.1](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-optimization-manual.pdf))

**_Use "goto" only when there's no real other way to exit deep nested loops_**. However, in some cases
the use of "goto" really can make the code more clear. (for example in a deep nested loop when used as "goto failed" where the "failed" Label is the general error handling for a function)


**_Use code alignment on loop entry_**
If the compiler does not already do it for you, this can improve speed on many occasions. Also here extreme use is to avoid.

**_Avoid extreme loop unrolling_**
If there is an optimization the compiler will do it for you. Only unroll loops when you use inline assembler instructions.   see more in 3.4.1.7 Loop Unrolling [Intel Optimization Guide](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-optimization-manual.pdf)
However unrolling in HLSL shaders can be really effictive.

**Comment by TBBle** [comment]
I was considering making a suggestion for the Performance section, but it might be better here:

If the editors feel this doesn't really belong with this 'good loops' proposal, I'm happy to separately propose an addition to the Performance section.

Prefer pre-increment/decrement operators when you don't require the post-increment behaviour
---

Although it doesn't make a large difference for simple types when not using the result, it's a good habit to be in, to avoid paying the cost of an object copy needlessly.

**Comment by BjarneStroustrup** [comment]
I have looked at this and can't think of appropriate concrete rules to add. When we get to look at performance issues again, we should  look at alignment, cache lines, and unrolling. If someone want a rule relating to loop invariants, I suggest they open an issue specifically for that because what I have thought of it blah. "Have a loop invariant" by itself is not helpful, nor is a long discussion. What makes a good invariant? Which loops requires one? (the ones that are too long?) How might a rule be enforceable?
