### ISSUE TITLE
Incorrect final function recommendation in 'C.139: Use final sparingly'

### ISSUE THREAD

**Issue by tmoers** [isocpp/CppCoreGuidelines#915]
Overriding final method gives compiler error. This makes the recommendation from the section [C.139: Use final sparingly](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c139-use-final-sparingly) incorrect because the final can't be overlooked as it is caught by the compiler.

**Comment by AndrewPardoe** [comment]
§ 10.3 2.4 If a virtual function f in some class B is marked with the virt-speciﬁer final and in a class D derived from B a function D::f overrides B::f, the program is ill-formed.

**Comment by AndrewPardoe** [comment]
Per our discussion, we may be able to get a better "bad" example. The assumption is that because the base is marked `final` that this isn't an override. There's more debate about the usefulness of `final` than just `override`. 

The intention of this issue is that people naively sprinkle `final` around to make code fast. The text in "Reason" may need modification as well. The guideline is solid, the text around it needs revision.

**Comment by tmoers** [comment]
Maybe I should clarify what I meant with the issue. The following line, in particular, seems erroneous to me:

> Capping an individual virtual function with final is error-prone as that final can easily be overlooked when defining/overriding a set of functions.

Shouldn't the compiler catch this very problem? I may be missing something, but if the compiler behaves as I expect, then there is nothing error prone about marking a function final.

**Comment by jwakely** [comment]
You're correct. The example and text is going to be updated.

**Comment by BjarneStroustrup** [comment]
I have replaced the bad example with a note.
