### ISSUE TITLE
Spaces

### ISSUE THREAD

**Issue by BjarneStroustrup** [isocpp/CppCoreGuidelines#948]
Do we have a "house style" that require spaces around operators?
Consider:
      // copy from [p:p+n) to [q:q+n)
was changed to
      // copy from [p:p + n) to [q:q + n)
I consider the former more readable.

**Comment by galik** [comment]
There was this discussion: https://github.com/isocpp/CppCoreGuidelines/issues/669

**Comment by MikeGitb** [comment]
Although I'm not a fan of hard whitespace rules, what about codifying whatever you consider the house style into a clang-format file and encouraging contributors to use it (although clang format wouldn't have touched that particular example of course)?

**Comment by martinmoene** [comment]
"Consider [visual thinking](http://visualmess.com/)".

**Comment by cubbimew** [comment]
We have a travis CI check that enforces whitespace around comparison operators in source code ("whitespace/operators", found in cpplint,py), but it does not trigger for addition, and also does not trigger for comments; in other words, changing that line to

     void copy_n(const T* p, T* q, int n); // copy from [p:p+n) to [q:q+n)

passes the check. It appears https://github.com/isocpp/CppCoreGuidelines/commit/9cc50836 was a bit excessive..

**Comment by tkruse** [comment]
I added many of the whitespaces between operators, also outside the multiline code snippets. I opted for consistency.

While I generally believe whitespaces around operators help readability, I do not believe this to be true in every single case.
But I believe as long as there is no objective guideline to follow, consistency is better than case-by-case decisions. 
Case-by-case decisions would incur repeated discussions of the matter, often about the same places by different people.


In the given example, there is also the alternative of applying whitespaces around the colons (or right-hand side only) for readability.

´´´
// copy from [p : p + n) to [q : q + n)
// copy from [p: p + n) to [q: q + n)
´´´

And apart from that, the mathematical notation for ranges uses comma instead of colons anyway (https://en.wikipedia.org/wiki/Bracket_(mathematics)#Intervals), so there is also this to consider

´´´
// copy from [p, p + n) to [q, q + n)
´´´

That would be my personal preference, throughout the document. Not sure where the colon notation comes from.

**Comment by tkruse** [comment]
I opened a PR to change the notation throughout the document at #959. 

To assess readability, the rendered result can be looked at here: https://github.com/tkruse/CppCoreGuidelines/blob/interval-notation/CppCoreGuidelines.md
and searching e.g. for "[p,".

**Comment by AndrewPardoe** [comment]
As noted in #959, we prefer the colon to denote intervals to not emphasize our American bias :)

Also, per our editors' discussion, we'd prefer to not have a hard-and-fast rule about whitespace around mathematical operators.

**Comment by tkruse** [comment]
It might be helpful to add this decision (non-enforcement of any style) to the document itself, for future reference in pull requests.
I recommend some formulation that emphasizes both benefits of consistency and readability.

Based on the Google styleguide which seems to chime in with the editors decisions, I would propose something like:
```
// Assignment operators always have spaces around them.
x = 0;

// Other binary operators usually have spaces around them, but it's
// OK to remove spaces around factors following operator precedence.
v = w * x + y / z;
v = w*x + y/z;
v = w * (x + z);

// No spaces separating unary operators and their arguments.
x = -5;
++x;
if (x && !y)
```

After all this, we'd still need a ruling for how to format interval notations:
```
A: ... // copy from [p:p+n) to [q:q+n)
B: ... // copy from [p: p+n) to [q: q+n)
C: ... // copy from [p : p+n) to [q : q+n)

E: ... // copy from [p:p + n) to [q:q + n)
F: ... // copy from [p: p + n) to [q: q + n)
G: ... // copy from [p : p + n) to [q : q + n)
```
I can make a PR for that, since I am the culprit who changed the original layout.
