### ISSUE TITLE
Is there a recommended order for #includes ?

### ISSUE THREAD

**Issue by benignbala** [isocpp/CppCoreGuidelines#981]
Hi,

When including header files in an implementation file (.cpp file), what is the recommended order of inclusion ? 

For eg. if `implementation.cpp` is the implementation of the interface defined in `interface.h`, and uses

1. a set of headers from std lib (for eg. <vector> and <map>), and 
2. other 3rd party library(for eg.  <boost/algorithm/string.hpp>) , 

what is the recommended order of inclusion ? Thanks

**Comment by vcato** [comment]
What I personally like is to have `interface.h` included first.  This helps make sure there is at least one place where the header has been included before anything else, which helps make sure the header includes everything it depends on.

**Comment by lbrandy** [comment]
This probably ends up too close to a style discussion rather than a core guideline. There's lots of sensible ways to do it but I'm not sure we could craft a useful guideline.

**Comment by benignbala** [comment]
@lbrandy I had raised this because, there are multiple arguments in favour of the following two styles.

*Style 1*
* Include `interface.h`
* Include all standard headers
* Include 3rd party headers
* Include all other necessary headers from the current project

*Style 2*
* Include all standard headers
* Include 3rd party headers
* Include `interface.h`
* Include all other necessary headers from the current project

The argument in favour of style 2 is that, any #defines and conditionals from the `interface.h` or other header files of the current project shouldn't mess with the standard header files. 

Are there other common styles apart from these two ? And is there a general recommended way followed by members of the ISOCPP ?

**Comment by galik** [comment]
I follow essentially *Style 2* but additionally I list all headers in alphabetical order *within their group*.

The rational is that a header that comes before other headers can cause subtle bugs if it, itself, has a bug. Therefore I put the most stable headers at the top.

Standard headers should get the most testing and should be the most hardened so they go first.

Third party headers are generally "release quality" so they come next.

Project headers come last because those are headers you are actively working on and therefore are *developmental* and by nature unstable.

I don't know how much following *Style 2* actually saves bugs so I don't know how worth while it might be as a recommendation. Which I guess is the primary goal of the guidelines.

**Comment by MikeGitb** [comment]
The point about ordering stable before unstable becomes imho a bit moot when you consider that the interface header most likely includes other headers of all categories. Essentially you'll always end up with a mixed order.

I think including the interface header first is a reasonable guideline for the reason vcato named (although you could argue that that should also be checked by your unit test)  the rest is imho a pure stylistic matter. 

Would be glad however, if there was a style that makes it easier to identify headers that are no longer needed or missing.

**Comment by tlanc007** [comment]
I mostly agree with @lbrandy this may be more of a style.  

Personally,  I tend to follow @galik 's ordering.  I find this ordering tends to introduce less surprises.  
For example, (I'm not sure if it this is still true),  for at time at least, one couldn't include the gmock/gtest headers before the standard headers without messing up the STL.

However,  I suppose there are those that diverge from this ordering and probably have a good reason for doing so.

**Comment by lbrandy** [comment]
FWIW, we use, essentially `style 1` internally for the reason that @vcato lays out. If you follow it throughout your codebase it helps ensure, to some extent, modularity of your headers (and with discipline it avoids the problem of #defines messing with standard headers etc because those should never occur before including said headers, even in your interface headers). 

Even that rule, which does provide some protective value (IMO) on your code, doesn't feel guidelines worthy and IMO the rest of the relative ordering rules are almost purely questions of style.

**Comment by cubbimew** [comment]
> Are there other common styles apart from these two ?

There's the Bloomberg style, where the standard headers come last, or, to be precise, as a part of the third group in the list:

1. Headers from the same package (library)
2. Headers from other libraries in the same project
3. 3rd Party + OS Specific + Standard

(the style guide makes an exception for the third group that a bad third-party header may require a standard header to be included first, but in practice the last header is usually the most general, like string, iosfwd or assert)

**Comment by MikeGitb** [comment]
Maybe I'm missunderstanding you, but how does style 1 lead to
> and with discipline it avoids the problem of #defines messing with standard headers etc because those should never occur before including said headers, even in your interface headers

Lets look at an example: 
```
// interface.h
#include <string>
#include <boost/algorithm/algorithm.hpp>
#include "../include/my_header1.hpp"
/* My interface code */

// impl.cpp
#include "interface.h"
#include <iostream>
#include <boost/any.hpp>
#include "../include/my_header2.hpp"
/* My impl code */
```
which then effectively becomes
```
// TU
#include <string>
#include <boost/algorithm/algorithm.hpp>
#include "../include/my_header1.hpp"
/* My interface code */
#include <iostream>
#include <boost/any.hpp>
#include "../include/my_header2.hpp"
/* My impl code */
```
And voila, we have `boost/algorithm/algorithm.hpp` , `../include/my_header1.hpp` and my interface code with all their definines included before `<iostream>`. Style 2 is a bit better in that regard, but it essentially ends up with the same problem, as soon as you include 2 or more of your own headers in a translation unit.

**Comment by lbrandy** [comment]
Yes, you're right. My parenthetical statement doesn't hold.

**Comment by lbrandy** [comment]
Alright, we discussed this issue, and we've decided that we can't really provide enough value as a guideline. We did briefly think about doing the weakest possible guidance ("here's some things that some people do.... ") but even then it's hard to come up with something general enough. As we tried, we started arguing (laugh), and decided this is really hard to codify into something useful.
