### ISSUE TITLE
Character set problem, rule I.25?

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#994]
The words *Shapes* and *Points* look strange on my computer (Ubuntu, Firefox 54.0 (64-bit), Language: English). See screenshot. Probably they contain a character not well supported on all platforms.

![unintended_space](https://user-images.githubusercontent.com/17589466/28492120-54d8a352-6efd-11e7-916a-460f7bb79d16.png)

Maybe you want to check this.

**Comment by galik** [comment]
I think it's because the text contains markup to make the word "Shape" look like code (having a fixed font). The author didn't include the pluralizing "s" inside the code markup because that would have suggested that the `class` name included the pluralizing "s". 

It's a difficult square to round. I suppose one way to deal with it is to talk in terms of *objects* so instead of "`Shape`s" we could say "`Shape` objects".

But that can feel a little *wordy* so something I tend to do is avoid using the actual class names and talk about the types more *conceptually* as simply *shapes*, *colors* and *points*.

For example:
>This will force every derived class to compute a center -- even if that's non-trivial and the center is never used. Similarly, not every *shape* has a *color*, and many *shapes* are best represented without an outline defined as a sequence of *points*. 

The words are italicized to emphasize that they relate to the types in the example without trying to *be* the literal type names used.  The *discussion* talks about *shapes* and it is evident that these *shapes* are represented in the code example with the type called `Shape`.

Probably different people will find different ways more relatable.

**Comment by jwakely** [comment]
There's nothing wrong here, it's exactly as intended.
